//! The `Rotation` enum and `Vector3::rotate`, ported from
//! `AP_Math/rotations.h` and `AP_Math/vector3.cpp`.
//!
//! GENERATED by `tools/parity/gen_rotations.py` -- do not edit. 49
//! rotations over a 246-line switch: one swapped sign would give a
//! rotation that is still orthonormal, still length-preserving, and
//! simply the wrong one. Every case is checked against upstream
//! exhaustively by `tests/rotations_parity.rs`.
//!
//! Upstream compiles with `-fsingle-precision-constant`, so the literals
//! here are single precision and the whole switch evaluates in the
//! element type -- there is no promotion to double, despite what the
//! C source looks like. See the generator's docstring; getting this
//! wrong changed exactly one rotation, in its last bit.

#![allow(
    clippy::excessive_precision,
    reason = "upstream's literals, reproduced verbatim; trimming them \
would be editing upstream's source"
)]
#![allow(
    clippy::approx_constant,
    reason = "HALF_SQRT_2 is near FRAC_1_SQRT_2 but is not it; \
substituting the named constant changes the last bits and breaks the \
bit-exact parity this module is verified against"
)]
#![allow(
    clippy::manual_swap,
    reason = "this file corresponds statement for statement with \
upstream's switch so the two can be diffed; mem::swap would be \
equivalent but would break that correspondence"
)]

use crate::scalar::Real;
use crate::vector3::Vector3;

/// Sensor orientation, upstream `enum Rotation`.
///
/// Discriminants are upstream's: drivers and parameters carry the raw
/// value, and MAVLink's `MAV_SENSOR_ORIENTATION` is expected to match.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum Rotation {
    /// Upstream `ROTATION_NONE`.
    None = 0,
    /// Upstream `ROTATION_YAW_45`.
    Yaw45 = 1,
    /// Upstream `ROTATION_YAW_90`.
    Yaw90 = 2,
    /// Upstream `ROTATION_YAW_135`.
    Yaw135 = 3,
    /// Upstream `ROTATION_YAW_180`.
    Yaw180 = 4,
    /// Upstream `ROTATION_YAW_225`.
    Yaw225 = 5,
    /// Upstream `ROTATION_YAW_270`.
    Yaw270 = 6,
    /// Upstream `ROTATION_YAW_315`.
    Yaw315 = 7,
    /// Upstream `ROTATION_ROLL_180`.
    Roll180 = 8,
    /// Upstream `ROTATION_ROLL_180_YAW_45`.
    Roll180Yaw45 = 9,
    /// Upstream `ROTATION_ROLL_180_YAW_90`.
    Roll180Yaw90 = 10,
    /// Upstream `ROTATION_ROLL_180_YAW_135`.
    Roll180Yaw135 = 11,
    /// Upstream `ROTATION_PITCH_180`.
    Pitch180 = 12,
    /// Upstream `ROTATION_ROLL_180_YAW_225`.
    Roll180Yaw225 = 13,
    /// Upstream `ROTATION_ROLL_180_YAW_270`.
    Roll180Yaw270 = 14,
    /// Upstream `ROTATION_ROLL_180_YAW_315`.
    Roll180Yaw315 = 15,
    /// Upstream `ROTATION_ROLL_90`.
    Roll90 = 16,
    /// Upstream `ROTATION_ROLL_90_YAW_45`.
    Roll90Yaw45 = 17,
    /// Upstream `ROTATION_ROLL_90_YAW_90`.
    Roll90Yaw90 = 18,
    /// Upstream `ROTATION_ROLL_90_YAW_135`.
    Roll90Yaw135 = 19,
    /// Upstream `ROTATION_ROLL_270`.
    Roll270 = 20,
    /// Upstream `ROTATION_ROLL_270_YAW_45`.
    Roll270Yaw45 = 21,
    /// Upstream `ROTATION_ROLL_270_YAW_90`.
    Roll270Yaw90 = 22,
    /// Upstream `ROTATION_ROLL_270_YAW_135`.
    Roll270Yaw135 = 23,
    /// Upstream `ROTATION_PITCH_90`.
    Pitch90 = 24,
    /// Upstream `ROTATION_PITCH_270`.
    Pitch270 = 25,
    /// Upstream `ROTATION_PITCH_180_YAW_90`.
    Pitch180Yaw90 = 26,
    /// Upstream `ROTATION_PITCH_180_YAW_270`.
    Pitch180Yaw270 = 27,
    /// Upstream `ROTATION_ROLL_90_PITCH_90`.
    Roll90Pitch90 = 28,
    /// Upstream `ROTATION_ROLL_180_PITCH_90`.
    Roll180Pitch90 = 29,
    /// Upstream `ROTATION_ROLL_270_PITCH_90`.
    Roll270Pitch90 = 30,
    /// Upstream `ROTATION_ROLL_90_PITCH_180`.
    Roll90Pitch180 = 31,
    /// Upstream `ROTATION_ROLL_270_PITCH_180`.
    Roll270Pitch180 = 32,
    /// Upstream `ROTATION_ROLL_90_PITCH_270`.
    Roll90Pitch270 = 33,
    /// Upstream `ROTATION_ROLL_180_PITCH_270`.
    Roll180Pitch270 = 34,
    /// Upstream `ROTATION_ROLL_270_PITCH_270`.
    Roll270Pitch270 = 35,
    /// Upstream `ROTATION_ROLL_90_PITCH_180_YAW_90`.
    Roll90Pitch180Yaw90 = 36,
    /// Upstream `ROTATION_ROLL_90_YAW_270`.
    Roll90Yaw270 = 37,
    /// Upstream `ROTATION_ROLL_90_PITCH_68_YAW_293`.
    Roll90Pitch68Yaw293 = 38,
    /// Upstream `ROTATION_PITCH_315`.
    Pitch315 = 39,
    /// Upstream `ROTATION_ROLL_90_PITCH_315`.
    Roll90Pitch315 = 40,
    /// Upstream `ROTATION_PITCH_7`.
    Pitch7 = 41,
    /// Upstream `ROTATION_ROLL_45`.
    Roll45 = 42,
    /// Upstream `ROTATION_ROLL_315`.
    Roll315 = 43,
    /// Upstream `ROTATION_MAX`.
    Max = 44,
    /// Upstream `ROTATION_CUSTOM_OLD`.
    CustomOld = 100,
    /// Upstream `ROTATION_CUSTOM_1`.
    Custom1 = 101,
    /// Upstream `ROTATION_CUSTOM_2`.
    Custom2 = 102,
    /// Upstream `ROTATION_CUSTOM_END`.
    CustomEnd = 103,
}

impl Rotation {
    /// From the raw discriminant a driver or parameter carries.
    ///
    /// `None` for a value that names no rotation.
    #[must_use]
    pub fn from_u8(v: u8) -> Option<Self> {
        Some(match v {
            0 => Self::None,
            1 => Self::Yaw45,
            2 => Self::Yaw90,
            3 => Self::Yaw135,
            4 => Self::Yaw180,
            5 => Self::Yaw225,
            6 => Self::Yaw270,
            7 => Self::Yaw315,
            8 => Self::Roll180,
            9 => Self::Roll180Yaw45,
            10 => Self::Roll180Yaw90,
            11 => Self::Roll180Yaw135,
            12 => Self::Pitch180,
            13 => Self::Roll180Yaw225,
            14 => Self::Roll180Yaw270,
            15 => Self::Roll180Yaw315,
            16 => Self::Roll90,
            17 => Self::Roll90Yaw45,
            18 => Self::Roll90Yaw90,
            19 => Self::Roll90Yaw135,
            20 => Self::Roll270,
            21 => Self::Roll270Yaw45,
            22 => Self::Roll270Yaw90,
            23 => Self::Roll270Yaw135,
            24 => Self::Pitch90,
            25 => Self::Pitch270,
            26 => Self::Pitch180Yaw90,
            27 => Self::Pitch180Yaw270,
            28 => Self::Roll90Pitch90,
            29 => Self::Roll180Pitch90,
            30 => Self::Roll270Pitch90,
            31 => Self::Roll90Pitch180,
            32 => Self::Roll270Pitch180,
            33 => Self::Roll90Pitch270,
            34 => Self::Roll180Pitch270,
            35 => Self::Roll270Pitch270,
            36 => Self::Roll90Pitch180Yaw90,
            37 => Self::Roll90Yaw270,
            38 => Self::Roll90Pitch68Yaw293,
            39 => Self::Pitch315,
            40 => Self::Roll90Pitch315,
            41 => Self::Pitch7,
            42 => Self::Roll45,
            43 => Self::Roll315,
            44 => Self::Max,
            100 => Self::CustomOld,
            101 => Self::Custom1,
            102 => Self::Custom2,
            103 => Self::CustomEnd,
            _ => return None,
        })
    }
}

/// Why a rotation could not be applied.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BadRotation {
    /// `ROTATION_CUSTOM_1` or `_2`, which upstream delegates to
    /// `AP_CustomRotations` -- a separate library that is not ported, and
    /// which upstream itself compiles out unless
    /// `AP_CUSTOMROTATIONS_ENABLED`.
    CustomUnsupported,
    /// `ROTATION_MAX`, `ROTATION_CUSTOM_OLD` or `ROTATION_CUSTOM_END`:
    /// enum bookkeeping, not orientations. Upstream reports
    /// `INTERNAL_ERROR(bad_rotation)` and leaves the vector alone.
    NotARotation,
}

/// Rotate `v` in place, upstream `Vector3<T>::rotate`.
///
/// # Errors
///
/// See [`BadRotation`]. Upstream returns `void` and reports an internal
/// error; here the caller is told, and the vector is left unrotated
/// either way.
pub fn rotate<T: Real>(v: &mut Vector3<T>, rotation: Rotation) -> Result<(), BadRotation> {
    match rotation {
        Rotation::None => {}
        Rotation::Yaw45 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.x = tmp;
        }
        Rotation::Yaw90 => {
            let tmp = v.x;
            v.x = -v.y;
            v.y = tmp;
        }
        Rotation::Yaw135 => {
            let tmp = -T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.x = tmp;
        }
        Rotation::Yaw180 => {
            v.x = -v.x;
            v.y = -v.y;
        }
        Rotation::Yaw225 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.y - v.x);
            v.y = -T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.x = tmp;
        }
        Rotation::Yaw270 => {
            let tmp = v.x;
            v.x = v.y;
            v.y = -tmp;
        }
        Rotation::Yaw315 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.y - v.x);
            v.x = tmp;
        }
        Rotation::Roll180 => {
            v.y = -v.y;
            v.z = -v.z;
        }
        Rotation::Roll180Yaw45 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.x = tmp;
            v.z = -v.z;
        }
        Rotation::Roll180Yaw90 | Rotation::Pitch180Yaw270 => {
            let tmp = v.x;
            v.x = v.y;
            v.y = tmp;
            v.z = -v.z;
        }
        Rotation::Roll180Yaw135 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.y - v.x);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.y + v.x);
            v.x = tmp;
            v.z = -v.z;
        }
        Rotation::Pitch180 => {
            v.x = -v.x;
            v.z = -v.z;
        }
        Rotation::Roll180Yaw225 => {
            let tmp = -T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.y - v.x);
            v.x = tmp;
            v.z = -v.z;
        }
        Rotation::Roll180Yaw270 | Rotation::Pitch180Yaw90 => {
            let tmp = v.x;
            v.x = -v.y;
            v.y = -tmp;
            v.z = -v.z;
        }
        Rotation::Roll180Yaw315 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.y = -T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.x = tmp;
            v.z = -v.z;
        }
        Rotation::Roll90 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
        }
        Rotation::Roll90Yaw45 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.x = tmp;
        }
        Rotation::Roll90Yaw90 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            let tmp = v.x;
            v.x = -v.y;
            v.y = tmp;
        }
        Rotation::Roll90Yaw135 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            let tmp = -T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.x = tmp;
        }
        Rotation::Roll270 => {
            let tmp = v.z;
            v.z = -v.y;
            v.y = tmp;
        }
        Rotation::Roll270Yaw45 => {
            let tmp = v.z;
            v.z = -v.y;
            v.y = tmp;
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.x = tmp;
        }
        Rotation::Roll270Yaw90 => {
            let tmp = v.z;
            v.z = -v.y;
            v.y = tmp;
            let tmp = v.x;
            v.x = -v.y;
            v.y = tmp;
        }
        Rotation::Roll270Yaw135 => {
            let tmp = v.z;
            v.z = -v.y;
            v.y = tmp;
            let tmp = -T::from_f64(0.70710678118654752440084436210485) * (v.x + v.y);
            v.y = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.y);
            v.x = tmp;
        }
        Rotation::Pitch90 => {
            let tmp = v.z;
            v.z = -v.x;
            v.x = tmp;
        }
        Rotation::Pitch270 => {
            let tmp = v.z;
            v.z = v.x;
            v.x = -tmp;
        }
        Rotation::Roll90Pitch90 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            let tmp = v.z;
            v.z = -v.x;
            v.x = tmp;
        }
        Rotation::Roll180Pitch90 => {
            v.y = -v.y;
            v.z = -v.z;
            let tmp = v.z;
            v.z = -v.x;
            v.x = tmp;
        }
        Rotation::Roll270Pitch90 => {
            let tmp = v.z;
            v.z = -v.y;
            v.y = tmp;
            let tmp = v.z;
            v.z = -v.x;
            v.x = tmp;
        }
        Rotation::Roll90Pitch180 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            v.x = -v.x;
            v.z = -v.z;
        }
        Rotation::Roll270Pitch180 => {
            let tmp = v.z;
            v.z = -v.y;
            v.y = tmp;
            v.x = -v.x;
            v.z = -v.z;
        }
        Rotation::Roll90Pitch270 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            let tmp = v.z;
            v.z = v.x;
            v.x = -tmp;
        }
        Rotation::Roll180Pitch270 => {
            v.y = -v.y;
            v.z = -v.z;
            let tmp = v.z;
            v.z = v.x;
            v.x = -tmp;
        }
        Rotation::Roll270Pitch270 => {
            let tmp = v.z;
            v.z = -v.y;
            v.y = tmp;
            let tmp = v.z;
            v.z = v.x;
            v.x = -tmp;
        }
        Rotation::Roll90Pitch180Yaw90 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            v.x = -v.x;
            v.z = -v.z;
            let tmp = v.x;
            v.x = -v.y;
            v.y = tmp;
        }
        Rotation::Roll90Yaw270 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            let tmp = v.x;
            v.x = v.y;
            v.y = -tmp;
        }
        Rotation::Roll90Pitch68Yaw293 => {
            let tmpx = v.x;
            let tmpy = v.y;
            let tmpz = v.z;
            v.x = T::from_f64(0.14303897231223747232853327204793) * tmpx
                + T::from_f64(0.36877648650320382639478111741482) * tmpy
                + -T::from_f64(0.91844638134308709265241077446262) * tmpz;
            v.y = -T::from_f64(0.33213277779664740485543461545603) * tmpx
                + -T::from_f64(0.85628942146641884303193137384369) * tmpy
                + -T::from_f64(0.39554550256296522325882847326284) * tmpz;
            v.z = -T::from_f64(0.93232380121551217122544130688766) * tmpx
                + T::from_f64(0.36162457008209242248497616856184) * tmpy
                + T::from_f64(0.00000000000000002214311861220361) * tmpz;
        }
        Rotation::Pitch315 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.z);
            v.z = T::from_f64(0.70710678118654752440084436210485) * (v.x + v.z);
            v.x = tmp;
        }
        Rotation::Roll90Pitch315 => {
            let tmp = v.z;
            v.z = v.y;
            v.y = -tmp;
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.x - v.z);
            v.z = T::from_f64(0.70710678118654752440084436210485) * (v.x + v.z);
            v.x = tmp;
        }
        Rotation::Pitch7 => {
            let sin_pitch = T::from_f64(0.1218693434051474899781908334262);
            let cos_pitch = T::from_f64(0.99254615164132198312785249072476);
            let tmpx = v.x;
            let tmpz = v.z;
            v.x = cos_pitch * tmpx + sin_pitch * tmpz;
            v.z = -sin_pitch * tmpx + cos_pitch * tmpz;
        }
        Rotation::Roll45 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.y - v.z);
            v.z = T::from_f64(0.70710678118654752440084436210485) * (v.y + v.z);
            v.y = tmp;
        }
        Rotation::Roll315 => {
            let tmp = T::from_f64(0.70710678118654752440084436210485) * (v.y + v.z);
            v.z = T::from_f64(0.70710678118654752440084436210485) * (v.z - v.y);
            v.y = tmp;
        }
        Rotation::Custom1 | Rotation::Custom2 => {
            return Err(BadRotation::CustomUnsupported);
        }
        Rotation::Max | Rotation::CustomOld | Rotation::CustomEnd => {
            return Err(BadRotation::NotARotation);
        }
    }
    Ok(())
}
