//! Parity test: matrix inversion against upstream `AP_Math/matrix_alg.cpp`.
//!
//! Inputs and outputs both travel as raw bit patterns. The LU path is a long
//! chain of multiply-accumulate whose last bits depend on the order of
//! operations, so a decimal round-trip on either side would force a tolerance —
//! and a tolerance is exactly what would hide a reordered expression.
//!
//! Generated by `tools/parity/gen_matrix_alg_fixture.py`; regenerate after an
//! upstream re-baseline.

#![allow(
    clippy::indexing_slicing,
    reason = "indexes fixture rows whose field count is asserted; in a test an \
index fault is a test failure, which is the desired outcome"
)]
#![allow(
    clippy::float_cmp,
    reason = "bit-exact comparison against upstream is the point of the test"
)]

use ap_math::matrix_alg::{mat_inverse, mat_mul, scratch_len, MatError};

fn fixture_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("fixtures/matrix_alg_parity.csv"))
        .expect("workspace root")
}

fn bits(field: &str) -> Vec<f32> {
    field
        .split_whitespace()
        .map(|s| f32::from_bits(s.parse::<u32>().expect("bit pattern")))
        .collect()
}

struct Row {
    section: String,
    f: Vec<String>,
}

fn parse(text: &str) -> Vec<Row> {
    let mut rows = Vec::new();
    let mut section = String::new();
    let mut header_pending = false;
    for line in text.lines() {
        if line.is_empty() {
            continue;
        }
        if let Some(name) = line.strip_prefix('#') {
            section = name.to_string();
            header_pending = true;
            continue;
        }
        if header_pending {
            header_pending = false;
            continue;
        }
        rows.push(Row {
            section: section.clone(),
            f: line.split(',').map(str::to_string).collect(),
        });
    }
    rows
}

#[test]
fn matrix_inverse_matches_upstream() {
    let path = fixture_path();
    if !path.exists() {
        eprintln!("skipping: {} not present", path.display());
        return;
    }
    let rows = parse(&std::fs::read_to_string(&path).expect("read fixture"));

    let mut inverted = 0usize;
    let mut rejected = 0usize;
    let mut multiplied = 0usize;

    for r in &rows {
        match r.section.as_str() {
            "cases" => {
                assert_eq!(r.f.len(), 6, "case row: {:?}", r.f);
                let kind = &r.f[0];
                let n: usize = r.f[1].parse().expect("n");
                let rep = &r.f[2];
                let upstream_ok = r.f[3] == "1";
                let a = bits(&r.f[4]);
                let want = bits(&r.f[5]);
                assert_eq!(a.len(), n * n, "input length for {kind} n={n}");

                let mut inv = vec![0.0f32; n * n];
                let mut scratch = vec![0.0f32; scratch_len(n)];
                let got = mat_inverse(&a, &mut inv, n, &mut scratch);

                match (upstream_ok, got) {
                    (true, Ok(())) => {
                        assert_eq!(
                            inv, want,
                            "{kind} n={n} rep={rep}: inverse differs from upstream"
                        );
                        inverted += 1;
                    }
                    (false, Err(MatError::Singular)) => {
                        rejected += 1;
                    }
                    (false, Ok(())) => {
                        panic!("{kind} n={n} rep={rep}: upstream rejected, port inverted")
                    }
                    // BadDimensions and ScratchTooSmall would mean this test
                    // set up the call wrong, not that the port disagrees.
                    (_, Err(e)) => {
                        panic!("{kind} n={n} rep={rep}: upstream ok={upstream_ok}, port {e:?}")
                    }
                }
            }
            "mul" => {
                assert_eq!(r.f.len(), 4, "mul row");
                let n: usize = r.f[0].parse().expect("n");
                let a = bits(&r.f[1]);
                let b = bits(&r.f[2]);
                let want = bits(&r.f[3]);
                let mut c = vec![0.0f32; n * n];
                mat_mul(&a, &b, &mut c, n).expect("mul");
                assert_eq!(c, want, "mat_mul n={n}");
                multiplied += 1;
            }
            other => panic!("unhandled section {other}"),
        }
    }

    println!(
        "{inverted} inverses and {multiplied} products matched upstream exactly; \
         {rejected} singular matrices rejected by both"
    );

    // A parity test that matched nothing would pass. Both outcomes must be
    // represented, or the test is only exercising one branch of the dispatch.
    assert!(inverted >= 20, "too few successful inversions: {inverted}");
    assert!(rejected >= 20, "too few singular cases: {rejected}");
    assert!(multiplied >= 5, "too few products: {multiplied}");
}
