//! Parity test: `VectorN` and `MatrixN` against upstream's own code.
//!
//! Values travel as raw bit patterns, so every comparison is exact.
//! Generated by `tools/parity/gen_vector_n_fixture.py`.
//!
//! # What this fixture cannot cover
//!
//! * **`VectorN::operator==`** — instantiating it for a float type fails
//!   upstream's own `-Werror=float-equal`, which means no upstream code
//!   instantiates it either. Its semantics are read from the source and pinned
//!   by a unit test rather than observed here.
//! * **D-013, the `float` dot-product accumulator** — it only bites when `T` is
//!   `double`, and `matrixN.cpp` explicitly instantiates `<float,4>` only, so
//!   there is no double instantiation to compare against. For `float` the port
//!   and upstream agree exactly, which this fixture does check.
//!
//! # What it does pin
//!
//! **D-014** precisely: upstream's `force_symmetry` is compared element by
//! element, and the test asserts the two agree everywhere upstream actually
//! symmetrises, that upstream leaves exactly the sub-diagonal asymmetric, and
//! that the port leaves nothing asymmetric.

#![allow(
    clippy::indexing_slicing,
    reason = "indexes fixture rows whose length is asserted; in a test an index \
fault is a test failure, which is the desired outcome"
)]
#![allow(
    clippy::float_cmp,
    reason = "bit-exact comparison against upstream is the point of the test"
)]

use ap_math::vector_n::{MatrixN, VectorN};
use std::collections::HashMap;

fn fixture_path() -> std::path::PathBuf {
    std::path::PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .map(|p| p.join("fixtures/vector_n_parity.csv"))
        .expect("workspace root")
}

fn bits(field: &str) -> Vec<f32> {
    field
        .split_whitespace()
        .map(|s| f32::from_bits(s.parse::<u32>().expect("bit pattern")))
        .collect()
}

/// Rows keyed by `(section:op, n)`.
///
/// The section prefix matters: `#mat4` also carries `in_a` and `in_b` at n=4,
/// which would otherwise overwrite the `#vec` entries of the same name and
/// silently compare the wrong vectors.
fn parse(text: &str) -> HashMap<(String, usize), Vec<f32>> {
    let mut out = HashMap::new();
    let mut section = String::new();
    let mut header_pending = false;
    for line in text.lines() {
        if line.is_empty() {
            continue;
        }
        if let Some(name) = line.strip_prefix('#') {
            section = name.to_string();
            header_pending = true;
            continue;
        }
        if header_pending {
            header_pending = false;
            continue;
        }
        let f: Vec<&str> = line.split(',').collect();
        match section.as_str() {
            "vec" => {
                let n: usize = f[1].parse().expect("n");
                out.insert((format!("vec:{}", f[0]), n), bits(f[2]));
            }
            "mat4" => {
                out.insert((format!("mat4:{}", f[0]), 4), bits(f[1]));
            }
            other => panic!("unhandled section {other}"),
        }
    }
    out
}

fn load() -> Option<HashMap<(String, usize), Vec<f32>>> {
    let path = fixture_path();
    if !path.exists() {
        eprintln!("skipping: {} not present", path.display());
        return None;
    }
    Some(parse(
        &std::fs::read_to_string(&path).expect("read fixture"),
    ))
}

/// Drive one `N` through every vector operation the fixture recorded.
fn check_vec<const N: usize>(fx: &HashMap<(String, usize), Vec<f32>>) -> usize {
    let get = |op: &str| -> Vec<f32> {
        fx.get(&(format!("vec:{op}"), N))
            .unwrap_or_else(|| panic!("fixture has no {op} for n={N}"))
            .clone()
    };
    let vec_of = |v: &[f32]| -> VectorN<f32, N> {
        let arr: [f32; N] = v.try_into().expect("length");
        VectorN::new(arr)
    };

    let a = vec_of(&get("in_a"));
    let b = vec_of(&get("in_b"));
    let s = get("in_s")[0];

    let mut checked = 0usize;
    let mut expect = |op: &str, got: VectorN<f32, N>| {
        assert_eq!(got.as_slice(), get(op).as_slice(), "{op} n={N}");
        checked += 1;
    };

    expect("neg", -a);
    expect("add", a + b);
    expect("sub", a - b);
    expect("mul", a * s);
    expect("div", a / s);

    let mut c = a;
    c += b;
    expect("add_assign", c);
    c = a;
    c -= b;
    expect("sub_assign", c);
    c = a;
    c *= s;
    expect("mul_assign", c);
    c = a;
    c /= s;
    expect("div_assign", c);

    assert_eq!(a.dot(&b), get("dot")[0], "dot n={N}");
    checked += 1;

    checked
}

#[test]
fn vector_n_matches_upstream() {
    let Some(fx) = load() else { return };

    let mut checked = 0usize;
    checked += check_vec::<2>(&fx);
    checked += check_vec::<3>(&fx);
    checked += check_vec::<4>(&fx);
    checked += check_vec::<5>(&fx);
    checked += check_vec::<9>(&fx);

    println!("{checked} VectorN operations matched upstream exactly");
    assert!(checked >= 50, "expected the whole fixture, got {checked}");
}

#[test]
fn matrix_n_matches_upstream() {
    let Some(fx) = load() else { return };
    let get = |op: &str| -> Vec<f32> {
        fx.get(&(format!("mat4:{op}"), 4))
            .unwrap_or_else(|| panic!("fixture has no mat4 {op}"))
            .clone()
    };
    let mat_of = |v: &[f32]| -> MatrixN<f32, 4> {
        let mut m = MatrixN::<f32, 4>::zero();
        for i in 0..4 {
            for j in 0..4 {
                m[i][j] = v[i * 4 + j];
            }
        }
        m
    };
    let flat = |m: &MatrixN<f32, 4>| -> Vec<f32> {
        (0..4)
            .flat_map(|i| (0..4).map(move |j| (i, j)))
            .map(|(i, j)| m[i][j])
            .collect()
    };

    let a: [f32; 4] = get("in_a").try_into().expect("len");
    let b: [f32; 4] = get("in_b").try_into().expect("len");

    let mut outer = MatrixN::<f32, 4>::zero();
    outer.set_mult(&VectorN::new(a), &VectorN::new(b));
    assert_eq!(flat(&outer), get("outer"), "outer product");

    let p = mat_of(&get("in_p"));
    let q = mat_of(&get("in_q"));

    let mut r = p;
    r += q;
    assert_eq!(flat(&r), get("add"), "matrix +=");
    let mut r = p;
    r -= q;
    assert_eq!(flat(&r), get("sub"), "matrix -=");

    println!("MatrixN outer product, += and -= matched upstream exactly");
}

/// D-014, pinned against upstream's recorded output rather than only against
/// the source reading.
///
/// Three claims, all checked here:
/// 1. upstream leaves exactly the sub-diagonal pairs asymmetric,
/// 2. the port leaves nothing asymmetric,
/// 3. the two agree on every element upstream does symmetrise, so the
///    divergence is confined to the pairs upstream skips.
#[test]
fn d014_force_symmetry_divergence_is_exactly_the_sub_diagonal() {
    let Some(fx) = load() else { return };
    let get = |op: &str| -> Vec<f32> {
        fx.get(&(format!("mat4:{op}"), 4))
            .unwrap_or_else(|| panic!("fixture has no mat4 {op}"))
            .clone()
    };

    let input = get("sym_in");
    let upstream = get("sym_out");

    let mut port = MatrixN::<f32, 4>::zero();
    for i in 0..4 {
        for j in 0..4 {
            port[i][j] = input[i * 4 + j];
        }
    }
    port.force_symmetry();

    // 1. upstream leaves exactly (1,0), (2,1), (3,2) asymmetric
    let upstream_asym: Vec<(usize, usize)> = (0..4)
        .flat_map(|i| (0..i).map(move |j| (i, j)))
        .filter(|&(i, j)| upstream[i * 4 + j] != upstream[j * 4 + i])
        .collect();
    assert_eq!(
        upstream_asym,
        vec![(1, 0), (2, 1), (3, 2)],
        "upstream's `j < i - 1` bound should skip exactly the sub-diagonal"
    );

    // 2. the port symmetrises everything
    assert!(
        port.is_symmetric(),
        "the port must leave no asymmetric pair"
    );

    // 3. and agrees with upstream everywhere upstream did the work
    let skipped = [(1usize, 0usize), (2, 1), (3, 2)];
    for i in 0..4 {
        for j in 0..4 {
            let is_skipped = skipped.contains(&(i, j)) || skipped.contains(&(j, i));
            if is_skipped {
                continue;
            }
            assert_eq!(
                port[i][j],
                upstream[i * 4 + j],
                "({i},{j}) should match upstream; the divergence is only the sub-diagonal"
            );
        }
    }

    println!(
        "D-014 confirmed: upstream leaves 3 of 6 off-diagonal pairs asymmetric, \
         the port leaves none, and they agree elsewhere"
    );
}
