#!/usr/bin/env python3
"""Generate the CRC parity fixture by running upstream's own crc.cpp.

Two things this avoids, both of which have already cost time on this port:

  * Hand-written expected values. The published "check" constant for a named
    CRC is easy to misremember and easy to attach to the wrong variant.
    ArduPilot's crc_crc16_ibm is the MSB-first 0x8005 form, not the CRC-16/ARC
    that "IBM" usually names; crc16_ccitt_GDL90 indexes its table differently
    from every other CCITT implementation; crc8_rds02uf uses a vendor table
    matching no polynomial at all. Running the C is not a matter of opinion.

  * Hand-copied tables. crc.cpp holds five distinct lookup tables, 1,280
    constants between them. A single mistyped byte would corrupt one input in
    256 and pass any spot check.

Output is CSV, not JSON, so the Rust side needs no deserialisation crate --
matching ap-replay, which parses its fixtures by hand for the same reason: a
test-support dependency that can break the build is not worth the convenience.

The harness compiles crc.cpp untouched, apart from an empty stub for the one
AP_HAL header it includes but does not use.
"""
import json
import re
import subprocess
import sys
from pathlib import Path

UP = Path("/srv/ardumaster/upstream/plane-4.7.0/libraries/AP_Math")
OUT = Path("/srv/ardumaster/ports/plane-fw-rust/fixtures")
BUILD = Path("/tmp/crc_parity")

HARNESS = r'''
// Parity harness: prints upstream crc.cpp's output over a fixed input set.
// Generated by tools/parity/gen_crc_fixture.py -- do not edit by hand.
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include "crc.h"

// The buffers every byte-oriented function is run over.
//   empty     - length zero, the case most likely to be mishandled
//   check     - "123456789", the standard CRC check string
//   allbytes  - 0x00..0xFF, so every table entry is exercised at least once
//   pseudo    - 64 bytes from a fixed LCG, to catch order-dependent errors
static const uint8_t buf_empty[1] = {0};
static const uint8_t buf_check[9] = {'1','2','3','4','5','6','7','8','9'};
static uint8_t buf_allbytes[256];
static uint8_t buf_pseudo[64];

static void init_buffers(void)
{
    for (int i = 0; i < 256; i++) {
        buf_allbytes[i] = (uint8_t)i;
    }
    // deterministic, and emitted into the fixture so the Rust side uses the
    // same bytes rather than reimplementing the generator
    uint32_t s = 12345;
    for (int i = 0; i < 64; i++) {
        s = s * 1103515245u + 12345u;
        buf_pseudo[i] = (uint8_t)(s >> 16);
    }
}

struct buf { const char *name; const uint8_t *p; uint32_t len; };

// fn,buf,seed,seed2,out -- seed columns empty where the function takes none
#define EMIT(fn, bufname, seeds, val) \
    printf("%s,%s,%s,%llu\n", fn, bufname, seeds, (unsigned long long)(val))

int main(void)
{
    init_buffers();
    const struct buf bufs[] = {
        { "empty",    buf_empty,    0   },
        { "check",    buf_check,    9   },
        { "allbytes", buf_allbytes, 256 },
        { "pseudo",   buf_pseudo,   64  },
    };
    const int nbufs = sizeof(bufs)/sizeof(bufs[0]);

    printf("#buffers\n");
    printf("name,hex\n");
    for (int b = 0; b < nbufs; b++) {
        printf("%s,", bufs[b].name);
        for (uint32_t i = 0; i < bufs[b].len; i++) {
            printf("%02x", bufs[b].p[i]);
        }
        printf("\n");
    }

    printf("#cases\n");
    printf("fn,buf,seed,seed2,out\n");

    for (int b = 0; b < nbufs; b++) {
        const uint8_t *p = bufs[b].p;
        const uint32_t n = bufs[b].len;
        const char *nm = bufs[b].name;

        // the uint8_t length parameters cannot express 256
        if (n <= 255) {
            EMIT("crc_crc8", nm, ",", crc_crc8(p, (uint8_t)n));
            EMIT("crc_sum8_with_carry", nm, ",", crc_sum8_with_carry(p, (uint8_t)n));
        }
        EMIT("crc8_maxim", nm, ",", crc8_maxim(p, (uint16_t)n));
        EMIT("crc8_sae", nm, ",", crc8_sae(p, (uint16_t)n));
        EMIT("crc8_rds02uf", nm, ",", crc8_rds02uf(p, (uint16_t)n));
        EMIT("crc_xor_of_bytes", nm, ",", crc_xor_of_bytes(p, (uint16_t)n));
        EMIT("crc_xmodem", nm, ",", crc_xmodem(p, (uint16_t)n));
        EMIT("calc_crc_modbus", nm, ",", calc_crc_modbus(p, (uint16_t)n));
        EMIT("crc_fletcher16", nm, ",", crc_fletcher16(p, n));
        EMIT("crc_crc24", nm, ",", crc_crc24(p, (uint16_t)n));
        EMIT("crc_sum_of_bytes", nm, ",", crc_sum_of_bytes(p, (uint16_t)n));
        EMIT("crc_sum_of_bytes_16", nm, ",", crc_sum_of_bytes_16(p, (uint16_t)n));

        // seeded forms get a zero seed and two non-zero ones: a seed that is
        // ignored, or applied at the wrong point, only shows up on the latter
        static const uint32_t seeds32[] = { 0u, 0xFFFFFFFFu, 0x12345678u };
        for (int s = 0; s < 3; s++) {
            char ss[32]; snprintf(ss, sizeof(ss), "%u,", seeds32[s]);
            EMIT("crc_crc32", nm, ss, crc_crc32(seeds32[s], p, n));
            EMIT("crc32_small", nm, ss, crc32_small(seeds32[s], p, n));
        }
        static const uint16_t seeds16[] = { 0u, 0xFFFFu, 0x1234u };
        for (int s = 0; s < 3; s++) {
            char ss[32]; snprintf(ss, sizeof(ss), "%u,", seeds16[s]);
            EMIT("crc16_ccitt", nm, ss, crc16_ccitt(p, n, seeds16[s]));
            EMIT("crc16_ccitt_GDL90", nm, ss, crc16_ccitt_GDL90(p, n, seeds16[s]));
            EMIT("crc16_ccitt_r", nm, ss, crc16_ccitt_r(p, n, seeds16[s], 0xFFFF));
            uint8_t tmp[256]; memcpy(tmp, p, n);
            EMIT("crc_crc16_ibm", nm, ss, crc_crc16_ibm(seeds16[s], tmp, (uint16_t)n));
        }
        static const uint8_t seeds8[] = { 0u, 0xFFu, 0x5Au };
        for (int s = 0; s < 3; s++) {
            char ss[32]; snprintf(ss, sizeof(ss), "%u,", seeds8[s]);
            EMIT("crc8_dvb_s2_update", nm, ss, crc8_dvb_s2_update(seeds8[s], p, n));
            EMIT("crc8_dvb_update", nm, ss, crc8_dvb_update(seeds8[s], p, (uint16_t)n));
            EMIT("crc8_generic_07", nm, ss, crc8_generic(p, (uint16_t)n, 0x07, seeds8[s]));
            EMIT("crc8_generic_d5", nm, ss, crc8_generic(p, (uint16_t)n, 0xD5, seeds8[s]));
        }
        // FNV-1a is an accumulator seeded with a mandated offset basis
        uint64_t h = FNV_1_OFFSET_BASIS_64;
        hash_fnv_1a(n, p, &h);
        EMIT("hash_fnv_1a", nm, ",", h);
    }

    // the single-byte forms, sampled across the whole input space
    for (int c = 0; c < 256; c += 37) {
        for (int a = 0; a < 256; a += 53) {
            char ss[64]; snprintf(ss, sizeof(ss), "%d,%d", c, a);
            EMIT("crc8_dvb_s2", "pair", ss, crc8_dvb_s2((uint8_t)c, (uint8_t)a));
            EMIT("crc8_dvb_07", "pair", ss, crc8_dvb((uint8_t)c, (uint8_t)a, 0x07));
            EMIT("crc_xmodem_update", "pair", ss,
                 crc_xmodem_update((uint16_t)(c*257), (uint8_t)a));
        }
    }
    // parity over its entire domain
    for (int i = 0; i < 256; i++) {
        char ss[32]; snprintf(ss, sizeof(ss), "%d,", i);
        EMIT("parity", "byte", ss, parity((uint8_t)i));
    }

    // the word-oriented forms
    {
        uint16_t d4[8] = {0x1234,0x5678,0x9abc,0xdef0,0x0f1e,0x2d3c,0x4b5a,0x6978};
        EMIT("crc_crc4", "words", ",", crc_crc4(d4));
        uint16_t z4[8] = {0,0,0,0,0,0,0,0};
        EMIT("crc_crc4", "zeros", ",", crc_crc4(z4));
        uint32_t d64[4] = {0x00000000u, 0xFFFFFFFFu, 0x12345678u, 0xdeadbeefu};
        EMIT("crc_crc64", "words4", ",", crc_crc64(d64, 4));
        EMIT("crc_crc64", "words1", ",", crc_crc64(d64, 1));
        EMIT("crc_crc64", "words0", ",", crc_crc64(d64, 0));
    }

    return 0;
}
'''


def build_and_run():
    BUILD.mkdir(parents=True, exist_ok=True)
    # crc.cpp includes one AP_HAL header it does not use; stub it rather than
    # pulling in the whole HAL include tree
    (BUILD / "AP_HAL").mkdir(exist_ok=True)
    (BUILD / "AP_HAL" / "AP_HAL_Boards.h").write_text("#pragma once\n")
    (BUILD / "crc.h").write_text((UP / "crc.h").read_text())
    (BUILD / "crc.cpp").write_text((UP / "crc.cpp").read_text())
    (BUILD / "harness.cpp").write_text(HARNESS)

    cmd = ["g++", "-O0", "-Wall", "-I", str(BUILD),
           str(BUILD / "crc.cpp"), str(BUILD / "harness.cpp"),
           "-o", str(BUILD / "harness")]
    r = subprocess.run(cmd, capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("compile failed:\n" + r.stderr)
    if r.stderr.strip():
        print("compiler warnings:\n" + r.stderr.strip())

    r = subprocess.run([str(BUILD / "harness")], capture_output=True, text=True)
    if r.returncode != 0:
        sys.exit("harness failed:\n" + r.stderr)
    return r.stdout


def extract_tables():
    src = (UP / "crc.cpp").read_text()
    tables = {}
    for m in re.finditer(
            r"static const (uint\d+_t) (\w+)\s*\[[^\]]*\]\s*=\s*\{(.*?)\};",
            src, re.S):
        ty, name, body = m.group(1), m.group(2), m.group(3)
        tables[name] = {
            "type": ty,
            "values": [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\b\d+\b", body)],
        }
    # the crc_crc16_ibm table is function-local; the pattern above finds it
    # under the name crc_table, which is too generic to keep
    if "crc_table" in tables:
        tables["crc_table_ibm"] = tables.pop("crc_table")
    for name, t in sorted(tables.items()):
        if len(t["values"]) != 256:
            sys.exit("table %s has %d entries, expected 256" % (name, len(t["values"])))
        print("  table %-22s %s x %d" % (name, t["type"], len(t["values"])))
    return tables


def main():
    text = build_and_run()
    OUT.mkdir(parents=True, exist_ok=True)
    (OUT / "crc_parity.csv").write_text(text)

    lines = text.splitlines()
    ncase = sum(1 for i, l in enumerate(lines)
                if i > lines.index("#cases") + 1 and l.strip())
    nbuf = lines.index("#cases") - 2
    print("wrote crc_parity.csv: %d cases over %d buffers" % (ncase, nbuf))

    tables = extract_tables()
    (OUT / "crc_tables.json").write_text(json.dumps(tables, indent=1, sort_keys=True))
    print("wrote crc_tables.json: %d tables" % len(tables))


if __name__ == "__main__":
    main()
