#!/usr/bin/env python3
"""Generate the scalar-helpers parity fixture from upstream's AP_Math.cpp.

These helpers -- wrap_360, constrain_value, safe_sqrt, linear_interpolate and
friends -- were ported early, before the parity harness existed, and have never
been compared against upstream. They are also used by nearly everything else,
so an error here would be inherited widely and would look like a defect in
whatever module surfaced it.

D-015 is the specific reason to check them now. The port implements the wrap
family by widening to f64, doing the arithmetic there and narrowing back:

    T::from_f64(res.to_f64() + 360.0)

while upstream is entirely single precision. That is *probably* equivalent for
a single addition -- the exact sum of two f32 values is representable in f64,
so there is no double rounding -- but "probably" is not a verification, and the
argument does not obviously extend to fmod or to the 2*pi cases. The fixture
settles it.

Inputs are swept across the awkward regions rather than sampled comfortably:
around the wrap discontinuities, across zero, at the domain edges of asin and
sqrt, and at values where a rounding difference would actually show.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/ardumaster-rust/fixtures/scalar_parity.csv")
BUILD = Path("/tmp/scalar_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math.cpp's scalar helpers.
// Generated by tools/parity/gen_scalar_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// constrain_value reports constraining_nan, which the fixture covers, so this
// records rather than aborts.
static bool saw_internal_error = false;
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t)
{
    saw_internal_error = true;
}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_HAL::panic(const char *m, ...) { fputs(m, stderr); abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// Angles chosen around the discontinuities the wrap functions exist to handle,
// not comfortably in the middle of a range.
static const float angles[] = {
    0.0f, -0.0f, 1.0f, -1.0f, 179.9f, 180.0f, 180.1f, 359.9f, 360.0f, 360.1f,
    -179.9f, -180.0f, -180.1f, -359.9f, -360.0f, -360.1f, 720.0f, -720.0f,
    1e6f, -1e6f, 0.001f, -0.001f, 45.5f, -45.5f, 1e-8f, 123456.789f,
};
static const int nangles = sizeof(angles)/sizeof(angles[0]);

// Radians, likewise around 0, pi and 2*pi.
static const float radians_in[] = {
    0.0f, 1.0f, -1.0f, 3.14159265f, -3.14159265f, 3.2f, -3.2f,
    6.28318531f, -6.28318531f, 6.3f, -6.3f, 12.5f, -12.5f, 1e-8f, 1e6f,
};
static const int nradians = sizeof(radians_in)/sizeof(radians_in[0]);

int main(void)
{
    printf("#wrap\n");
    printf("fn,in,out\n");
    for (int i = 0; i < nangles; i++) {
        const float a = angles[i];
        printf("wrap_360,%u,%u\n", fbits(a), fbits(wrap_360(a)));
        printf("wrap_180,%u,%u\n", fbits(a), fbits(wrap_180(a)));
    }
    for (int i = 0; i < nradians; i++) {
        const float r = radians_in[i];
        printf("wrap_2PI,%u,%u\n", fbits(r), fbits(wrap_2PI(r)));
        printf("wrap_PI,%u,%u\n", fbits(r), fbits(wrap_PI(r)));
    }

    printf("#unary\n");
    printf("fn,in,out\n");
    {
        static const float vals[] = {
            0.0f, -0.0f, 1.0f, -1.0f, 0.5f, -0.5f, 2.0f, -2.0f, 1e-8f, -1e-8f,
            1e20f, -1e20f, 0.9999999f, -0.9999999f, 1.0000001f, -1.0000001f,
            3.0f, 1e-30f, 123.456f,
        };
        const int n = sizeof(vals)/sizeof(vals[0]);
        for (int i = 0; i < n; i++) {
            const float v = vals[i];
            printf("safe_sqrt,%u,%u\n", fbits(v), fbits(safe_sqrt(v)));
            printf("safe_asin,%u,%u\n", fbits(v), fbits(safe_asin(v)));
            printf("sq,%u,%u\n", fbits(v), fbits(sq(v)));
            printf("degrees,%u,%u\n", fbits(v), fbits(degrees(v)));
            printf("radians,%u,%u\n", fbits(v), fbits(radians(v)));
        }
    }

    printf("#predicate\n");
    printf("fn,in,out\n");
    {
        // around FLT_EPSILON, which is where is_zero and friends switch
        static const float vals[] = {
            0.0f, -0.0f, 1e-8f, -1e-8f, 1.1920929e-7f, -1.1920929e-7f,
            1.1920928e-7f, 1.1920930e-7f, 1e-6f, -1e-6f, 1.0f, -1.0f,
        };
        const int n = sizeof(vals)/sizeof(vals[0]);
        for (int i = 0; i < n; i++) {
            const float v = vals[i];
            printf("is_zero,%u,%u\n", fbits(v), is_zero(v) ? 1u : 0u);
            printf("is_positive,%u,%u\n", fbits(v), is_positive(v) ? 1u : 0u);
            printf("is_negative,%u,%u\n", fbits(v), is_negative(v) ? 1u : 0u);
        }
    }

    printf("#binary\n");
    printf("fn,a,b,out\n");
    {
        static const float xs[] = { 0.0f, 1.0f, -1.0f, 1e-7f, 1e-8f, 1e20f, 123.456f };
        const int n = sizeof(xs)/sizeof(xs[0]);
        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                printf("is_equal,%u,%u,%u\n", fbits(xs[i]), fbits(xs[j]),
                       is_equal(xs[i], xs[j]) ? 1u : 0u);
                printf("norm2,%u,%u,%u\n", fbits(xs[i]), fbits(xs[j]),
                       fbits(norm(xs[i], xs[j])));
            }
        }
    }

    printf("#constrain\n");
    printf("v,lo,hi,out,reported\n");
    {
        static const float vs[] = { -5.0f, -1.0f, 0.0f, 0.5f, 1.0f, 5.0f };
        static const float bounds[][2] = { {0.0f,1.0f}, {-1.0f,1.0f}, {-10.0f,10.0f}, {1.0f,1.0f} };
        const int nv = sizeof(vs)/sizeof(vs[0]);
        const int nb = sizeof(bounds)/sizeof(bounds[0]);
        for (int i = 0; i < nv; i++) {
            for (int b = 0; b < nb; b++) {
                saw_internal_error = false;
                const float out = constrain_float(vs[i], bounds[b][0], bounds[b][1]);
                printf("%u,%u,%u,%u,%d\n", fbits(vs[i]), fbits(bounds[b][0]),
                       fbits(bounds[b][1]), fbits(out), saw_internal_error ? 1 : 0);
            }
        }
        // and NaN, which upstream reports as an internal error
        const float nan = strtof("NAN", NULL);
        saw_internal_error = false;
        const float out = constrain_float(nan, 0.0f, 1.0f);
        printf("%u,%u,%u,%u,%d\n", fbits(nan), fbits(0.0f), fbits(1.0f),
               fbits(out), saw_internal_error ? 1 : 0);
    }

    printf("#interp\n");
    printf("low_out,high_out,var,low,high,out\n");
    {
        static const float cases[][5] = {
            {0.0f, 1.0f, 0.5f, 0.0f, 1.0f},
            {0.0f, 1.0f, -1.0f, 0.0f, 1.0f},
            {0.0f, 1.0f, 2.0f, 0.0f, 1.0f},
            {-1.0f, 1.0f, 0.0f, -10.0f, 10.0f},
            {100.0f, 200.0f, 5.0f, 0.0f, 10.0f},
            {5.0f, 5.0f, 3.0f, 0.0f, 10.0f},
            {0.0f, 1.0f, 3.0f, 2.0f, 2.0f},   // degenerate input range
        };
        const int n = sizeof(cases)/sizeof(cases[0]);
        for (int i = 0; i < n; i++) {
            const float o = linear_interpolate(cases[i][0], cases[i][1],
                                               cases[i][2], cases[i][3], cases[i][4]);
            printf("%u,%u,%u,%u,%u,%u\n",
                   fbits(cases[i][0]), fbits(cases[i][1]), fbits(cases[i][2]),
                   fbits(cases[i][3]), fbits(cases[i][4]), fbits(o));
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/AP_Math.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)

    counts, section = {}, None
    for line in text.splitlines():
        if line.startswith("#"):
            section = line[1:]
            counts[section] = -1
        elif section:
            counts[section] += 1
    print("wrote %s" % OUT.name)
    for k, v in counts.items():
        print("  %-10s %d rows" % (k, v))


if __name__ == "__main__":
    main()
