#!/usr/bin/env python3
"""Generate the Vector3 geometry parity fixture from upstream's own code.

Covers the members completed in this slice: rotate_xy, rotate_inverse,
row_times_mat, mul_rowcol, distance_to_segment,
point_on_line_closest_to_other_point, closest_distance_between_line_and_point,
segment_plane_intersect and segment_to_segment_closest_point.

The segment cases are chosen to reach every branch of
`segment_to_segment_closest_point`, which has six: near-parallel, the s=0 and
s=1 edges, and the t=0 and t=1 edges, plus the interior case. A fixture that
only used generic crossing segments would exercise one of them and look
thorough.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/plane-fw-rust/fixtures/vector3_geom_parity.csv")
BUILD = Path("/tmp/v3geom_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for the Vector3 geometry members.
// Generated by tools/parity/gen_vector3_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_HAL::panic(const char *m, ...) { fputs(m, stderr); abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static void emit3(const Vector3f &v)
{
    printf("%u %u %u", fbits(v.x), fbits(v.y), fbits(v.z));
}

// Segment pairs chosen to reach every branch of
// segment_to_segment_closest_point: crossing, parallel, collinear, degenerate,
// and pairs whose nearest approach is at each end.
static const float segs[][12] = {
    // s1start, s1end, s2start, s2end
    {0,0,0,  10,0,0,   5,-5,0,   5,5,0},      // crossing at the middle
    {0,0,0,  10,0,0,   0,1,0,    10,1,0},     // parallel
    {0,0,0,  10,0,0,   20,0,0,   30,0,0},     // collinear, disjoint
    {0,0,0,  10,0,0,   0,0,0,    10,0,0},     // identical
    {0,0,0,  0,0,0,    1,1,1,    2,2,2},      // first degenerate
    {0,0,0,  10,0,0,   5,5,5,    5,5,5},      // second degenerate
    {0,0,0,  1,0,0,    -5,1,0,   -4,1,0},     // nearest at the s=0/t=1 ends
    {0,0,0,  1,0,0,    5,1,0,    6,1,0},      // nearest at the s=1/t=0 ends
    {0,0,0,  1,1,1,    1,0,0,    0,1,0},      // skew in 3D
    {-3,2,7, 4,-1,2,   0,0,0,    1,1,1},      // general skew
};
static const int nsegs = sizeof(segs)/sizeof(segs[0]);

static const float pts[][3] = {
    {0,0,0}, {1,2,3}, {-4,5,-6}, {0.5f,0.5f,0.5f}, {100,-100,0.25f},
};
static const int npts = sizeof(pts)/sizeof(pts[0]);

int main(void)
{
    printf("#seg2seg\n");
    printf("case,out\n");
    for (int i = 0; i < nsegs; i++) {
        Vector3f a(segs[i][0], segs[i][1], segs[i][2]);
        Vector3f b(segs[i][3], segs[i][4], segs[i][5]);
        Vector3f c(segs[i][6], segs[i][7], segs[i][8]);
        Vector3f d(segs[i][9], segs[i][10], segs[i][11]);
        Vector3f out(0,0,0);
        Vector3f::segment_to_segment_closest_point(a, b, c, d, out);
        printf("%d,", i);
        emit3(out);
        printf("\n");
    }

    printf("#pointline\n");
    printf("seg,pt,closest,dist,distseg\n");
    for (int i = 0; i < nsegs; i++) {
        Vector3f w1(segs[i][0], segs[i][1], segs[i][2]);
        Vector3f w2(segs[i][3], segs[i][4], segs[i][5]);
        for (int j = 0; j < npts; j++) {
            Vector3f p(pts[j][0], pts[j][1], pts[j][2]);
            const Vector3f closest =
                Vector3f::point_on_line_closest_to_other_point(w1, w2, p);
            const float dist =
                Vector3f::closest_distance_between_line_and_point(w1, w2, p);
            const float distseg = p.distance_to_segment(w1, w2);
            printf("%d,%d,", i, j);
            emit3(closest);
            printf(",%u,%u\n", fbits(dist), fbits(distseg));
        }
    }

    printf("#plane\n");
    printf("seg,normal,point,hit\n");
    {
        static const float planes[][6] = {
            {0,0,1,  0,0,0},     // z = 0
            {0,0,1,  0,0,5},     // z = 5
            {1,0,0,  5,0,0},     // x = 5
            {1,1,1,  0,0,0},     // diagonal through the origin
            {0,0,0,  0,0,0},     // degenerate normal
        };
        const int np = sizeof(planes)/sizeof(planes[0]);
        for (int i = 0; i < nsegs; i++) {
            Vector3f a(segs[i][0], segs[i][1], segs[i][2]);
            Vector3f b(segs[i][3], segs[i][4], segs[i][5]);
            for (int k = 0; k < np; k++) {
                Vector3f n(planes[k][0], planes[k][1], planes[k][2]);
                Vector3f pp(planes[k][3], planes[k][4], planes[k][5]);
                printf("%d,%d,%d,%d\n", i, k, 0,
                       Vector3f::segment_plane_intersect(a, b, n, pp) ? 1 : 0);
            }
        }
    }

    printf("#matops\n");
    printf("pt,rowtimesmat,mulrowcol\n");
    {
        // a fixed non-symmetric matrix, so a transposed result is visible
        const Matrix3f m(1,2,3, 4,5,6, 7,8,10);
        for (int j = 0; j < npts; j++) {
            Vector3f p(pts[j][0], pts[j][1], pts[j][2]);
            const Vector3f rtm = p.row_times_mat(m);
            const Matrix3f mrc = p.mul_rowcol(Vector3f(1.5f, -2.5f, 0.75f));
            printf("%d,", j);
            emit3(rtm);
            printf(",");
            emit3(mrc.a); printf(" "); emit3(mrc.b); printf(" "); emit3(mrc.c);
            printf("\n");
        }
    }

    printf("#rotxy\n");
    printf("pt,angle,out\n");
    {
        static const float angles[] = { 0.0f, 0.7853981633974483f, 1.5707963267948966f,
                                        3.141592653589793f, -1.0f, 2.5f };
        const int na = sizeof(angles)/sizeof(angles[0]);
        for (int j = 0; j < npts; j++) {
            for (int k = 0; k < na; k++) {
                Vector3f p(pts[j][0], pts[j][1], pts[j][2]);
                p.rotate_xy(angles[k]);
                printf("%d,%u,", j, fbits(angles[k]));
                emit3(p);
                printf("\n");
            }
        }
    }

    printf("#rotinv\n");
    printf("rotation,pt,out\n");
    for (int r = 0; r <= 103; r++) {
        if (r == ROTATION_CUSTOM_1 || r == ROTATION_CUSTOM_2) continue;
        if (r > ROTATION_MAX && r < ROTATION_CUSTOM_OLD) continue;
        if (r == ROTATION_MAX || r == ROTATION_CUSTOM_OLD || r == ROTATION_CUSTOM_END) continue;
        for (int j = 0; j < npts; j++) {
            Vector3f p(pts[j][0], pts[j][1], pts[j][2]);
            p.rotate_inverse((enum Rotation)r);
            printf("%d,%d,", r, j);
            emit3(p);
            printf("\n");
        }
    }

    printf("#pts\n");
    printf("idx,vals\n");
    for (int j = 0; j < npts; j++) {
        printf("%d,", j);
        emit3(Vector3f(pts[j][0], pts[j][1], pts[j][2]));
        printf("\n");
    }

    printf("#segs\n");
    printf("idx,vals\n");
    for (int i = 0; i < nsegs; i++) {
        printf("%d,", i);
        for (int k = 0; k < 12; k++) {
            printf("%s%u", k ? " " : "", fbits(segs[i][k]));
        }
        printf("\n");
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/vector3.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)

    counts, section = {}, None
    for line in text.splitlines():
        if line.startswith("#"):
            section = line[1:]
            counts[section] = -1
        elif section:
            counts[section] += 1
    print("wrote %s" % OUT.name)
    for k, v in counts.items():
        print("  %-10s %d rows" % (k, v))


if __name__ == "__main__":
    main()
