#!/usr/bin/env python3
"""INCOMPLETE. Parity fixture for the multirotor mixing factor model.

DOES NOT BUILD YET, and the reason is worth recording rather than retrying
blindly.

add_motor and normalise_rpy_factors are pure functions of the factor arrays and
touch nothing else. But they are members of AP_MotorsMatrix, and constructing
one runs AP_Motors_Class -> AP_MotorsMulticopter -> AP_MotorsMatrix, whose
constructors and output paths reach the AHRS, the battery monitor, SRV_Channels
and parameter persistence.

# There are no stubs here

This harness links the real firmware -- every ArduCopter object plus the
library archive waf built them all into -- so the AHRS, the battery monitor,
SRV_Channels, AP_Param and the SITL HAL are the ones a vehicle has. See
tools/parity/vehicle_link.py.

That matters more than it sounds. A stub does not merely skip work, it changes
what the fixture measures, and does so invisibly: SRV_Channels::set_output_scaled
doing nothing meant the output-channel path was compared against numbers this
harness made up, while the test still read as coverage. The stubs it used to
have were removed one linker error at a time -- every "multiple definition" is
the linker pointing at a fake the firmware already provides -- and every
fixture reproduced bit-for-bit afterwards, which turned "the stubs are not
hiding anything" from an assumption into a result.

The only firmware behaviour deliberately not taken is the entry point:
Copter.cpp defines main, which this file supplies, so vehicle_link renames that
one symbol with objcopy. A rename, not a stub.

Time is scripted through the SITL scheduler's stopped clock -- the mechanism
SITL's own lockstep uses -- rather than through a clock of the harness's own,
so even the timestamps a fixture feeds a filter come from the firmware's
supported path.

Until then the port's own tests carry the slice: they pin the angle
convention, yaw independence from position, normalisation to exactly 0.5 per
axis, absence of cross-coupling on a symmetric frame, an axis with no
authority being left alone, independent per-axis scaling, throttle clamping,
out-of-range motor numbers, and test ordering.


add_motor and normalise_rpy_factors are `protected`, and so are the factor
arrays. A subclass reaches them with `using` declarations -- ordinary C++
access, no preprocessor tricks -- and adds no members of its own, so the layout
is unchanged. That is checked with a static_assert on sizeof rather than
assumed.

Frames are built by hand rather than through setup_motors(), because
setup_motors is 1,400 lines of frame tables that are their own slice. The
angles here are the standard ones for each layout, which is what those tables
contain.

The object MUST be static: AP_Motors_Class holds AP_Param members and the
add_motor path is guarded by initialised_ok(), so a stack instance would be
reading whatever was there.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402
import vehicle_link  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/motors_parity.csv"
FRAMES_OUT = ROOT / "fixtures/motors_frames.csv"
SPOOL_OUT = ROOT / "fixtures/spool_parity.csv"
OUTPUT_OUT = ROOT / "fixtures/motors_output.csv"
THROTTLE_OUT = ROOT / "fixtures/motors_throttle.csv"
CHANNELS_OUT = ROOT / "fixtures/motors_channels.csv"
BUILD = Path("/tmp/motors_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Motors/AP_MotorsMatrix.cpp.3.o",
    "build/sitl/libraries/AP_Motors/AP_Motors_Class.cpp.0.o",
    "build/sitl/libraries/AP_Motors/AP_MotorsMulticopter.cpp.3.o",
    "build/sitl/libraries/AP_Motors/AP_Motors_Thrust_Linearization.cpp.3.o",
    "build/sitl/libraries/Filter/LowPassFilter.cpp.0.o",
    "build/sitl/libraries/Filter/DerivativeFilter.cpp.0.o",
    "build/sitl/libraries/AP_Param/AP_Param.cpp.0.o",
    "build/sitl/libraries/AP_Param/AP_ParamT.cpp.0.o",
    "build/sitl/libraries/StorageManager/StorageManager.cpp.3.o",
    "build/sitl/libraries/AP_HAL/Semaphores.cpp.0.o",
    "build/sitl/libraries/AP_HAL_SITL/Semaphores.cpp.0.o",
    "build/sitl/libraries/AP_HAL/utility/RingBuffer.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
    "build/sitl/libraries/AP_Math/crc.cpp.0.o",
]

# The real firmware, after the explicit objects above. See vehicle_link: the
# vehicle's own translation units define RC_Channels::var_info and the
# `vehicle` / `copter` globals, and the archive resolves the transitive tail
# without a hand-maintained list that would go stale.
OBJECTS.extend(vehicle_link.objects())

HARNESS = r'''
// Parity harness for AP_Motors/AP_MotorsMatrix factor model.
// Generated by tools/parity/gen_motors_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Motors/AP_MotorsMatrix.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <SRV_Channel/SRV_Channel.h>
#include <AP_Logger/AP_Logger.h>
#include <Filter/LowPassFilter.h>
#include <Filter/DerivativeFilter.h>
#include <AP_Notify/AP_Notify.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_BattMonitor/AP_BattMonitor.h>
#include <AP_Param/AP_Param.h>
#include <AP_Filesystem/AP_Filesystem.h>
#include <GCS_MAVLink/GCS.h>
#include <AP_HAL_SITL/Scheduler.h>
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_ROMFS/AP_ROMFS.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }

}

// SRV_Channels is linked for real, out of the firmware's own objects.
// The parameter trees, the output protocols and the channel mapping are
// the ones a vehicle has, not ones this harness invented.



// ArduPilot's own convention for reaching the HAL from a translation
// unit: declare it, never define it.
extern const AP_HAL::HAL &hal;

// `hal` itself comes from the firmware -- AP_HAL_SITL defines the reference,
// bound to a HAL_SITL constructed at load time. Nothing to declare here: no
// run(), no simulator, no threads, just the object the firmware already has.
// Its scheduler is what makes the clock below drivable.

// Deterministic time, the way SITL does it. AP_HAL_SITL::micros64() returns
// the scheduler's stopped clock when one is set, falling through to the wall
// clock when it is not -- the same mechanism SITL's lockstep uses. Scripting
// time through it keeps the fixture on the firmware's supported path instead
// of substituting a clock of the harness's own.
//
// Never set zero: that is the value that means "not stopped", and the fixture
// would silently start reading the wall clock.
static void harness_set_time_us(uint64_t t)
{
    hal.scheduler->stop_clock(t);
}

// The rest of the chain. AP_Motors_Class -> AP_MotorsMulticopter ->
// AP_MotorsMatrix reaches the AHRS, the battery monitor and parameter
// persistence from its CONSTRUCTOR and its output paths. None of it is on the
// path to add_motor or normalise_rpy_factors, which are pure functions of the
// factor arrays -- so every one of these aborts, and the fixture would die

// AP_Param.cpp is linked for real, so the motors object gets its parameter
// defaults the way a vehicle does. Stubbing setup_object_defaults to nothing
// would leave every parameter at zero -- a state no vehicle is ever in.





static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// Ordinary C++ access to protected members. No new members, so the layout is
// unchanged -- asserted rather than assumed.
class Probe : public AP_MotorsMatrix {
public:
    using AP_MotorsMatrix::add_motor;
    using AP_MotorsMatrix::add_motor_raw;
    using AP_MotorsMatrix::normalise_rpy_factors;
    using AP_MotorsMatrix::setup_motors;
    using AP_MotorsMatrix::_roll_factor;
    using AP_MotorsMatrix::_pitch_factor;
    using AP_MotorsMatrix::_yaw_factor;
    using AP_MotorsMatrix::_throttle_factor;
    using AP_MotorsMatrix::motor_enabled;
    using AP_MotorsMatrix::_test_order;
    // The spool state machine and everything it reads or writes. All of it is
    // protected on AP_MotorsMulticopter, which a subclass may reach.
    using AP_MotorsMulticopter::output_logic;
    using AP_MotorsMulticopter::_spin_up_ratio;
    using AP_MotorsMulticopter::_throttle_thrust_max;
    using AP_MotorsMulticopter::_idle_time;
    using AP_MotorsMulticopter::_disarm_safe_timer;
    using AP_MotorsMulticopter::_spin_up_complete;
    using AP_MotorsMulticopter::_spool_up_time;
    using AP_MotorsMulticopter::_spool_down_time;
    using AP_MotorsMulticopter::_idle_time_delay_s;
    using AP_MotorsMulticopter::_safe_time;
    using AP_MotorsMulticopter::_spin_arm;
    using AP_MotorsMulticopter::_disarm_disable_pwm;
    using AP_MotorsMulticopter::_batt_current_max;
    using AP_MotorsMulticopter::_throttle_hover_learn;
    using AP_Motors::_spool_desired;
    using AP_Motors::_spool_state;
    using AP_Motors::_thrust_boost;
    using AP_Motors::_thrust_boost_ratio;
    using AP_Motors::_thrust_balanced;
    using AP_Motors::_throttle_filter;
    using AP_MotorsMulticopter::output_to_pwm;
    using AP_MotorsMulticopter::set_actuator_with_slew;
    using AP_MotorsMulticopter::actuator_spin_up_to_ground_idle;
    using AP_MotorsMulticopter::check_mot_pwm_params;
    using AP_MotorsMulticopter::_slew_up_time;
    using AP_MotorsMulticopter::_slew_dn_time;
    using AP_MotorsMulticopter::_pwm_min;
    using AP_MotorsMulticopter::_pwm_max;
    using AP_MotorsMulticopter::update_throttle_filter;
    using AP_MotorsMulticopter::update_throttle_hover;
    using AP_MotorsMulticopter::_throttle_hover;
    using AP_Motors::_throttle_in;
    using AP_Motors::_throttle_slew_rate;
    using AP_MotorsMulticopter::update_throttle_range;
    using AP_MotorsMulticopter::output_boost_throttle;
    using AP_MotorsMulticopter::output_rpyt;
    using AP_MotorsMulticopter::_boost_scale;
    using AP_Motors::_pwm_type;
    using AP_Motors::_roll_in_ff;
    using AP_Motors::_pitch_in_ff;
    using AP_Motors::_yaw_in_ff;

    // PWMType is protected, so the cast has to happen in here rather than at
    // the call site.
    void set_pwm_type_raw(int ty) { _pwm_type.set((PWMType)ty); }


    // AP_MotorsMatrix enforces a singleton in its constructor, so the fixture
    // reuses one instance and clears it between frames rather than building
    // six. Clearing is what setup_motors would do; there is no public
    // equivalent.
    void clear_motors() {
        for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
            _roll_factor[i] = 0.0f;
            _pitch_factor[i] = 0.0f;
            _yaw_factor[i] = 0.0f;
            _throttle_factor[i] = 0.0f;
            motor_enabled[i] = false;
            _test_order[i] = 0;
        }
    }
};
static_assert(sizeof(Probe) == sizeof(AP_MotorsMatrix), "probe must not change layout");

struct motor_def { int8_t num; float angle; float yaw; uint8_t order; };

struct frame {
    const char *name;
    uint8_t count;
    struct motor_def motors[8];
};

// Standard layouts. These are the angles upstream's frame tables contain.
static const struct frame frames[] = {
    { "quad_x", 4, {
        {0,   45.0f,  1.0f, 1}, {1, -135.0f,  1.0f, 3},
        {2,  -45.0f, -1.0f, 4}, {3,  135.0f, -1.0f, 2} } },
    { "quad_plus", 4, {
        {0,   90.0f,  1.0f, 2}, {1,  -90.0f,  1.0f, 4},
        {2,    0.0f, -1.0f, 1}, {3,  180.0f, -1.0f, 3} } },
    { "hexa_x", 6, {
        {0,   90.0f,  1.0f, 2}, {1, -90.0f, -1.0f, 5},
        {2,  -30.0f,  1.0f, 6}, {3, 150.0f, -1.0f, 3},
        {4,   30.0f, -1.0f, 1}, {5, -150.0f, 1.0f, 4} } },
    { "hexa_plus", 6, {
        {0,    0.0f,  1.0f, 1}, {1, 180.0f, -1.0f, 4},
        {2, -120.0f, -1.0f, 5}, {3,  60.0f,  1.0f, 2},
        {4,  -60.0f,  1.0f, 6}, {5, 120.0f, -1.0f, 3} } },
    { "octa_x", 8, {
        {0,   22.5f,  1.0f, 1}, {1, -157.5f, 1.0f, 5},
        {2,   67.5f, -1.0f, 2}, {3,  157.5f,-1.0f, 4},
        {4,  112.5f,  1.0f, 3}, {5,  -22.5f,-1.0f, 8},
        {6,  -67.5f,  1.0f, 7}, {7, -112.5f,-1.0f, 6} } },
    { "tri", 3, {
        {0,   60.0f,  1.0f, 1}, {1, -60.0f,  1.0f, 3},
        {2,  180.0f,  0.0f, 2} } },
};

// One instance: AP_MotorsMatrix enforces a singleton. Static, so its
// AP_Param members and initialised_ok() flag start zeroed rather than holding
// whatever was on the stack.
static Probe motors;

// A scripted run of the machine. Times are seconds from the start of the
// scenario; a threshold past the end of the run simply never fires.
struct scenario {
    int steps;
    float spool_up_time, spool_down_time, safe_time, spin_arm, idle_time_delay;
    int disarm_disable_pwm;
    float throttle;
    float arm_at, disarm_at;
    float interlock_at, interlock_off_at;
    float desired_ul_at, desired_down_at, desired_gi_at;
    float clear_block_at;
    float boost_at, unbalanced_at;
};

#define NEVER 1.0e9f

static const scenario SCENARIOS[] = {
    // 0: the whole arc -- arm, idle, spool up, fly, spool down, shut down.
    { 4000, 0.5f, 0.5f, 0.0f, 0.10f, 0.5f, 0, 0.5f,
      0.0f, NEVER, 0.0f, NEVER, 0.05f, 6.0f, NEVER, 1.5f, NEVER, NEVER },
    // 1: interlock dropped in flight -- must slam to SHUT_DOWN, no ramp.
    { 3000, 0.5f, 0.5f, 0.0f, 0.10f, 0.2f, 0, 0.7f,
      0.0f, NEVER, 0.0f, 4.0f, 0.05f, NEVER, NEVER, 1.0f, NEVER, NEVER },
    // 2: SPOOL_TIME below the minimum -- the machine writes the parameter back.
    { 1200, 0.01f, 0.0f, 0.0f, 0.10f, 0.1f, 0, 0.4f,
      0.0f, NEVER, 0.0f, NEVER, 0.05f, NEVER, NEVER, 0.5f, NEVER, NEVER },
    // 3: the disarm-PWM safe-time window gates the exit from SHUT_DOWN.
    { 2000, 0.5f, 0.5f, 1.0f, 0.10f, 0.2f, 1, 0.4f,
      0.5f, NEVER, 0.5f, NEVER, 0.05f, NEVER, NEVER, 2.0f, NEVER, NEVER },
    // 4: thrust boost slews in while unbalanced, then back out.
    { 4000, 0.5f, 0.5f, 0.0f, 0.10f, 0.2f, 0, 0.6f,
      0.0f, NEVER, 0.0f, NEVER, 0.05f, NEVER, NEVER, 1.0f, 3.0f, 3.0f },
    // 5: reversal -- back to THROTTLE_UNLIMITED while spooling down.
    { 4000, 0.5f, 0.5f, 0.0f, 0.10f, 0.2f, 0, 0.5f,
      0.0f, NEVER, 0.0f, NEVER, 0.05f, 5.0f, NEVER, 1.0f, NEVER, NEVER },
    // 6: asymmetric ramps -- a long way down, a short way up.
    { 4000, 0.2f, 2.0f, 0.0f, 0.20f, 0.3f, 0, 0.8f,
      0.0f, NEVER, 0.0f, NEVER, 0.05f, 5.0f, 7.0f, 1.0f, NEVER, NEVER },
    // 7: disarmed mid-flight -- the safety rule, and the timer reset.
    { 3000, 0.5f, 0.5f, 0.5f, 0.10f, 0.2f, 1, 0.5f,
      0.0f, 4.0f, 0.0f, NEVER, 0.05f, NEVER, NEVER, 1.5f, NEVER, NEVER },
};

static const int NUM_SCENARIOS = (int)(sizeof(SCENARIOS) / sizeof(SCENARIOS[0]));

int main(void)
{
    printf("#motors\n");
    printf("frame,motor,stage,roll,pitch,yaw,throttle,enabled,order\n");

    for (unsigned fi = 0; fi < ARRAY_SIZE(frames); fi++) {
        const struct frame &f = frames[fi];
        Probe &m = motors;
        m.clear_motors();

        for (unsigned i = 0; i < f.count; i++) {
            m.add_motor(f.motors[i].num, f.motors[i].angle, f.motors[i].yaw, f.motors[i].order);
        }

        // raw factors, before normalisation
        for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
            printf("%s,%u,raw,%u,%u,%u,%u,%d,%u\n", f.name, i,
                   fbits(m._roll_factor[i]), fbits(m._pitch_factor[i]),
                   fbits(m._yaw_factor[i]), fbits(m._throttle_factor[i]),
                   m.motor_enabled[i] ? 1 : 0, (unsigned)m._test_order[i]);
        }

        m.normalise_rpy_factors();

        for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
            printf("%s,%u,norm,%u,%u,%u,%u,%d,%u\n", f.name, i,
                   fbits(m._roll_factor[i]), fbits(m._pitch_factor[i]),
                   fbits(m._yaw_factor[i]), fbits(m._throttle_factor[i]),
                   m.motor_enabled[i] ? 1 : 0, (unsigned)m._test_order[i]);
        }
    }

    // ---- every frame class and type the Copter build defines ----
    printf("#frames\n");
    printf("class,type,ok,motor,roll,pitch,yaw,throttle,order\n");

    for (int cls = 0; cls <= 17; cls++) {
        for (int typ = 0; typ <= 25; typ++) {
            Probe &m = motors;
            m.clear_motors();

            m.setup_motors((AP_Motors::motor_frame_class)cls,
                           (AP_Motors::motor_frame_type)typ);
            // setup_motors returns void, so success is read from whether it
            // fitted any motors -- which is also what the vehicle cares about.
            unsigned fitted = 0;
            for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
                if (m.motor_enabled[i]) { fitted++; }
            }
            if (fitted == 0) {
                printf("%d,%d,0,-1,0,0,0,0,0\n", cls, typ);
                continue;
            }
            // RAW factors, before normalisation. The port stores these and
            // normalises them itself, which keeps upstream's two-stage shape
            // instead of baking the scaling into the table.
            for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
                if (!m.motor_enabled[i]) {
                    continue;
                }
                printf("%d,%d,1,%u,%u,%u,%u,%u,%u\n", cls, typ, i,
                       fbits(m._roll_factor[i]), fbits(m._pitch_factor[i]),
                       fbits(m._yaw_factor[i]), fbits(m._throttle_factor[i]),
                       (unsigned)m._test_order[i]);
            }
        }
    }

    // ---- the spool state machine ----
    printf("#spool\n");
    printf("scenario,step,state,desired,spin_up_ratio,throttle_thrust_max,"
           "idle_time,disarm_safe_timer,spin_up_complete,spoolup_block,"
           "thrust_boost,thrust_boost_ratio,limit_roll,limit_throttle_lower,"
           "spool_up_time\n");

    for (int sc = 0; sc < NUM_SCENARIOS; sc++) {
        Probe &m = motors;

        // Reset every piece of state the machine owns, so one scenario cannot
        // leak into the next through the shared singleton.
        m.armed(false);
        m.set_interlock(false);
        m._spool_desired = AP_Motors::DesiredSpoolState::SHUT_DOWN;
        m._spool_state = AP_Motors::SpoolState::SHUT_DOWN;
        m._spin_up_ratio = 0.0f;
        m._throttle_thrust_max = 0.0f;
        m._idle_time = 0.0f;
        m._disarm_safe_timer = 0.0f;
        m._spin_up_complete = false;
        m.set_spoolup_block(false);
        m._thrust_boost = false;
        m._thrust_boost_ratio = 0.0f;
        m._thrust_balanced = true;
        m.limit.set_all(true);
        m.set_throttle(0.0f);
        m.set_dt_s(0.0025f);
        m._batt_current_max.set(0.0f);
        // Disarming saves the learned hover throttle, which reaches the
        // storage backend the harness does not have. Hover learning is
        // orthogonal to spooling, so it is switched off rather than stubbed.
        m._throttle_hover_learn.set((int8_t)0);  // HOVER_LEARN_DISABLED (the enum is protected)

        const scenario &s = SCENARIOS[sc];
        m._spool_up_time.set(s.spool_up_time);
        m._spool_down_time.set(s.spool_down_time);
        m._safe_time.set(s.safe_time);
        m._spin_arm.set(s.spin_arm);
        m._idle_time_delay_s.set(s.idle_time_delay);
        m._disarm_disable_pwm.set(s.disarm_disable_pwm);

        for (int step = 0; step < s.steps; step++) {
            // Scripted inputs. Everything the machine reads from outside
            // itself is set here, so a fixture row is fully determined by the
            // scenario and the step number.
            const float tsec = step * 0.0025f;
            m.armed(tsec >= s.arm_at && tsec < s.disarm_at);
            m.set_interlock(tsec >= s.interlock_at && tsec < s.interlock_off_at);
            // get_throttle() reads the FILTERED throttle, and the filter is
            // only advanced by update_throttle_filter(), which the vehicle
            // loop calls and this harness does not. Left alone it reads 0,
            // which would make SPOOLING_UP finish on its first step and the
            // whole throttle ramp go unexercised. Reset it to the demand so
            // get_throttle() returns the scenario's value exactly.
            m.set_throttle(s.throttle);
            m._throttle_filter.reset(s.throttle);
            m._thrust_balanced = !(tsec >= s.unbalanced_at);
            if (tsec >= s.boost_at) {
                m._thrust_boost = true;
            }
            if (tsec >= s.desired_ul_at && tsec < s.desired_down_at) {
                m._spool_desired = AP_Motors::DesiredSpoolState::THROTTLE_UNLIMITED;
            } else if (tsec >= s.desired_gi_at) {
                m._spool_desired = AP_Motors::DesiredSpoolState::GROUND_IDLE;
            } else {
                m._spool_desired = AP_Motors::DesiredSpoolState::SHUT_DOWN;
            }
            // Stand in for the vehicle's pre-takeoff checks clearing the block.
            if (tsec >= s.clear_block_at) {
                m.set_spoolup_block(false);
            }

            m.output_logic();

            printf("%d,%d,%d,%d,%u,%u,%u,%u,%d,%d,%d,%u,%d,%d,%u\n",
                   sc, step, (int)m._spool_state, (int)m._spool_desired,
                   fbits(m._spin_up_ratio), fbits(m._throttle_thrust_max),
                   fbits(m._idle_time), fbits(m._disarm_safe_timer),
                   (int)m._spin_up_complete, (int)m.get_spoolup_block(),
                   (int)m._thrust_boost, fbits(m._thrust_boost_ratio),
                   (int)m.limit.roll, (int)m.limit.throttle_lower,
                   fbits(m._spool_up_time.get()));
        }
    }

    // ---- the output stage ----
    printf("#output\n");

    // output_to_pwm: every spool state, both arming states, both
    // MOT_SAFE_DISARM settings, a couple of endpoint pairs, and actuator
    // values chosen to sit just under integer pulse widths so the truncation
    // shows rather than hides.
    printf("#pwm\n");
    printf("state,armed,disarm_disable,pwm_min,pwm_max,actuator,pwm\n");
    {
        Probe &m = motors;
        static const float ACTUATORS[] = {
            0.0f, 0.0009f, 0.1f, 0.25f, 0.3333333f, 0.5f, 0.6666667f,
            0.75f, 0.9f, 0.999f, 1.0f, 1.5f, -0.25f,
        };
        static const int16_t ENDS[][2] = { {1000, 2000}, {1100, 1900}, {1, 2} };

        for (int st = 0; st <= 4; st++) {
            for (int arm = 0; arm <= 1; arm++) {
                for (int dis = 0; dis <= 1; dis++) {
                    for (unsigned e = 0; e < 3; e++) {
                        m._pwm_min.set(ENDS[e][0]);
                        m._pwm_max.set(ENDS[e][1]);
                        m._disarm_disable_pwm.set((int8_t)dis);
                        m._spool_state = (AP_Motors::SpoolState)st;
                        m.armed(arm != 0);
                        for (unsigned a = 0;
                             a < sizeof(ACTUATORS) / sizeof(ACTUATORS[0]); a++) {
                            const int16_t pwm = m.output_to_pwm(ACTUATORS[a]);
                            printf("%d,%d,%d,%d,%d,%u,%d\n", st, arm, dis,
                                   ENDS[e][0], ENDS[e][1],
                                   fbits(ACTUATORS[a]), (int)pwm);
                        }
                    }
                }
            }
        }
        m.armed(false);
    }

    // set_actuator_with_slew: a grid of slew times against a step in each
    // direction, run for several iterations so the ramp is visible rather
    // than just its first step.
    printf("#slew\n");
    printf("up_time,dn_time,dt,start,input,iter,output\n");
    {
        Probe &m = motors;
        static const float TIMES[] = { 0.0f, 0.05f, 0.2f, 0.5f, 2.0f, -1.0f };
        static const float DTS[] = { 0.0025f, 0.01f };
        static const float STARTS[] = { 0.0f, 0.3f, 1.0f };
        static const float INPUTS[] = { 0.0f, 0.55f, 1.0f, 1.4f, -0.3f };

        for (unsigned u = 0; u < sizeof(TIMES) / sizeof(TIMES[0]); u++) {
            for (unsigned d = 0; d < sizeof(TIMES) / sizeof(TIMES[0]); d++) {
                for (unsigned k = 0; k < sizeof(DTS) / sizeof(DTS[0]); k++) {
                    for (unsigned s = 0; s < sizeof(STARTS) / sizeof(STARTS[0]); s++) {
                        for (unsigned i = 0; i < sizeof(INPUTS) / sizeof(INPUTS[0]); i++) {
                            m._slew_up_time.set(TIMES[u]);
                            m._slew_dn_time.set(TIMES[d]);
                            m.set_dt_s(DTS[k]);
                            float out = STARTS[s];
                            for (int it = 0; it < 6; it++) {
                                m.set_actuator_with_slew(out, INPUTS[i]);
                                printf("%u,%u,%u,%u,%u,%d,%u\n",
                                       fbits(TIMES[u]), fbits(TIMES[d]),
                                       fbits(DTS[k]), fbits(STARTS[s]),
                                       fbits(INPUTS[i]), it, fbits(out));
                            }
                        }
                    }
                }
            }
        }
    }

    // actuator_spin_up_to_ground_idle across the ramp, including the
    // out-of-range values the clamp exists for. SPIN_MIN stays at its default
    // -- it lives inside the thrust linearisation, which a subclass of
    // AP_MotorsMatrix cannot reach -- so the port covers other values by unit
    // test and this pins the default.
    printf("#idle\n");
    printf("spin_up_ratio,spin_min,actuator\n");
    {
        Probe &m = motors;
        static const float RATIOS[] = {
            -0.5f, 0.0f, 0.001f, 0.25f, 0.5f, 0.75f, 0.999f, 1.0f, 1.2f,
        };
        for (unsigned r = 0; r < sizeof(RATIOS) / sizeof(RATIOS[0]); r++) {
            m._spin_up_ratio = RATIOS[r];
            printf("%u,%u,%u\n", fbits(RATIOS[r]),
                   fbits(m.thr_lin.get_spin_min()),
                   fbits(m.actuator_spin_up_to_ground_idle()));
        }
    }

    // check_mot_pwm_params over the interesting endpoint pairs.
    printf("#pwmvalid\n");
    printf("pwm_min,pwm_max,valid\n");
    {
        Probe &m = motors;
        static const int16_t PAIRS[][2] = {
            {1000, 2000}, {0, 2000}, {1, 2}, {2, 1}, {1500, 1500},
            {-1, 2000}, {1, 1}, {1900, 1100}, {1, 32767},
        };
        for (unsigned i = 0; i < sizeof(PAIRS) / sizeof(PAIRS[0]); i++) {
            m._pwm_min.set(PAIRS[i][0]);
            m._pwm_max.set(PAIRS[i][1]);
            printf("%d,%d,%d\n", PAIRS[i][0], PAIRS[i][1],
                   (int)m.check_mot_pwm_params());
        }
    }

    // ---- the throttle input path ----
    printf("#throttle\n");

    // update_throttle_filter across a few stick profiles, both arming states,
    // and two filter cutoffs. The filtered throttle and the slew estimate are
    // both dumped every step: the slew estimate is a seven-sample derivative,
    // so it only agrees if the whole history agrees.
    printf("#filter\n");
    printf("case,step,cutoff,slew_cutoff,armed,throttle_in,now_us,"
           "filtered,slew_rate\n");
    {
        Probe &m = motors;
        static const float CUTOFFS[][2] = { {0.0f, 0.0f}, {2.0f, 25.0f}, {10.0f, 50.0f} };
        const int STEPS = 400;

        // The spool scenarios leave the throttle filter holding a value.
        // Clear it so the first pre-step compares zero against zero, the way
        // it does on a freshly constructed object.
        m._throttle_filter.reset(0.0f);

        int cs = 0;
        int feeds = 0;
        // Starts above zero: stop_clock(0) reads as 'not stopped'.
        uint64_t harness_time = 1000000;
        for (unsigned c = 0; c < 3; c++) {
            for (int profile = 0; profile < 4; profile++) {
                for (int arm = 0; arm <= 1; arm++, cs++) {
                    m.set_throttle_filter_cutoff(CUTOFFS[c][0]);
                    m.set_slew_filter_cutoff(CUTOFFS[c][1]);
                    // Deliberately NOT resetting the slew detector between
                    // cases. DerivativeFilter::reset() does not clear its own
                    // timestamps, so after it slope() computes across stale
                    // timestamps and cleared samples -- a registered divergence
                    // the port fixes, which means a fixture that reset would be
                    // comparing against behaviour the port refuses to have.
                    //
                    // Instead the singleton keeps one continuous history and
                    // the clock never rewinds, which both sides can reproduce.
                    // Disarming still clears the throttle filter, because that
                    // is upstream's own documented behaviour.
                    m.armed(false);
                    m.set_dt_s(0.0025f);
                    m.set_throttle(0.0f);
                    harness_time += 2500u;
                    harness_set_time_us(harness_time);
                    {
                        const float b = m._throttle_filter.get();
                        m.update_throttle_filter();
                        if (!is_equal(b, m._throttle_filter.get())) {
                            feeds++;
                        }
                    }

                    m.armed(arm != 0);
                    for (int step = 0; step < STEPS; step++) {
                        harness_time += 2500u;
                        harness_set_time_us(harness_time);
                        const float ts = step * 0.0025f;
                        float in;
                        switch (profile) {
                        case 0: in = 0.5f; break;                        // step
                        case 1: in = ts < 0.5f ? 0.0f : 1.0f; break;     // late step
                        case 2: in = 0.5f + 0.5f * sinf(ts * 6.0f); break;
                        case 3: in = ts * 0.4f - 0.1f; break;            // ramps out of range
                        default: in = 0.0f; break;
                        }
                        m.set_throttle(in);
                        // The same is_equal test update_throttle_filter makes
                        // internally, replicated so the fixture records whether
                        // the detector was fed rather than only its eventual
                        // effect on the slope.
                        const float before = m._throttle_filter.get();
                        m.update_throttle_filter();
                        const int fed = !is_equal(before, m._throttle_filter.get());
                        feeds += fed;
                        printf("%d,%d,%u,%u,%d,%u,%u,%u,%u,%d,%d\n", cs, step,
                               fbits(CUTOFFS[c][0]), fbits(CUTOFFS[c][1]),
                               arm, fbits(in), (uint32_t)harness_time,
                               fbits(m._throttle_filter.get()),
                               fbits(m._throttle_slew_rate), fed, feeds);
                    }
                }
            }
        }
        m.armed(false);
    }

    // update_throttle_hover: the ten-second lag, including inputs outside the
    // reachable range so the clamp on write is pinned.
    printf("#hover\n");
    printf("case,step,learn,dt,throttle,hover_raw,hover_get\n");
    {
        Probe &m = motors;
        static const float STARTS[] = { 0.35f, 0.125f, 0.6875f, 0.5f };
        static const float TARGETS[] = { 0.0f, 0.2f, 0.45f, 0.9f };
        static const float DTS[] = { 0.01f, 0.0025f };

        int cs = 0;
        for (int learn = 0; learn <= 2; learn++) {
            for (unsigned s = 0; s < 4; s++) {
                for (unsigned g = 0; g < 4; g++) {
                    for (unsigned k = 0; k < 2; k++, cs++) {
                        m._throttle_hover_learn.set((int8_t)learn);
                        m._throttle_hover.set(STARTS[s]);
                        m._throttle_filter.reset(TARGETS[g]);
                        for (int step = 0; step < 30; step++) {
                            m.update_throttle_hover(DTS[k]);
                            printf("%d,%d,%d,%u,%u,%u,%u\n", cs, step, learn,
                                   fbits(DTS[k]), fbits(TARGETS[g]),
                                   fbits(m._throttle_hover.get()),
                                   fbits(m.get_throttle_hover()));
                        }
                    }
                }
            }
        }
        m._throttle_hover_learn.set((int8_t)0);
    }

    // ---- the channel outputs ----
    printf("#channels\n");

    // update_throttle_range across the output types, with a frame fitted so
    // have_digital_outputs() has a real motor mask to answer about.
    printf("#range\n");
    printf("pwm_type,digital,start_min,start_max,end_min,end_max\n");
    {
        Probe &m = motors;
        m.clear_motors();
        m.setup_motors(AP_Motors::MOTOR_FRAME_QUAD, AP_Motors::MOTOR_FRAME_TYPE_X);
        // Both branches. have_digital_outputs() asks SRV_Channels which
        // output CHANNELS are digital, not what MOT_PWM_TYPE says, so a DShot
        // vehicle whose channels are not marked digital still takes the
        // analog branch. Setting digital_mask is what makes the other branch
        // reachable -- with the old stub returning zero it never was.
        for (int digital = 0; digital <= 1; digital++) {
            if (digital) {
                // The public route. It accumulates with |=, so there is no
                // way back -- which is why the analog pass runs first.
                SRV_Channels::set_digital_outputs(m.get_motor_mask(), 0);
            }
            for (int ty = 0; ty <= 9; ty++) {
                m._pwm_min.set(1100);
                m._pwm_max.set(1900);
                m.set_pwm_type_raw(ty);
                m.update_throttle_range();
                printf("%d,%d,%d,%d,%d,%d\n", ty, digital, 1100, 1900,
                       (int)m.get_pwm_output_min(), (int)m.get_pwm_output_max());
            }
        }
    }

    // output_boost_throttle: read the channel back out of the real
    // SRV_Channels rather than trusting that the call happened.
    printf("#boost\n");
    printf("boost_scale,throttle,scaled\n");
    {
        Probe &m = motors;
        static const float SCALES[] = { -1.0f, 0.0f, 0.5f, 1.0f, 2.0f, 5.0f };
        static const float THROTTLES[] = { 0.0f, 0.1f, 0.25f, 0.5f, 0.9f, 1.0f };

        for (unsigned s = 0; s < sizeof(SCALES) / sizeof(SCALES[0]); s++) {
            for (unsigned h = 0; h < sizeof(THROTTLES) / sizeof(THROTTLES[0]); h++) {
                m._boost_scale.set(SCALES[s]);
                m._throttle_filter.reset(THROTTLES[h]);
                m.output_boost_throttle();
                printf("%u,%u,%u\n", fbits(SCALES[s]), fbits(THROTTLES[h]),
                       fbits(SRV_Channels::get_output_scaled(SRV_Channel::k_boost_throttle)));
            }
        }
        m._boost_scale.set(0.0f);
    }

    // output_rpyt, likewise read back.
    printf("#rpyt\n");
    printf("roll,pitch,yaw,throttle,roll_out,pitch_out,yaw_out,thrust_out\n");
    {
        Probe &m = motors;
        static const float VALS[] = { -1.0f, -0.4f, 0.0f, 0.3f, 1.0f };

        for (unsigned a = 0; a < sizeof(VALS) / sizeof(VALS[0]); a++) {
            for (unsigned b = 0; b < sizeof(VALS) / sizeof(VALS[0]); b++) {
                m._roll_in_ff = VALS[a];
                m._pitch_in_ff = VALS[b];
                m._yaw_in_ff = VALS[(a + b) % 5];
                const float thr = (float)((a * 5 + b) % 11) / 10.0f;
                m._throttle_filter.reset(thr);
                m.output_rpyt();
                printf("%u,%u,%u,%u,%u,%u,%u,%u\n",
                       fbits(VALS[a]), fbits(VALS[b]), fbits(VALS[(a + b) % 5]),
                       fbits(thr),
                       fbits(SRV_Channels::get_output_scaled(SRV_Channel::k_roll_out)),
                       fbits(SRV_Channels::get_output_scaled(SRV_Channel::k_pitch_out)),
                       fbits(SRV_Channels::get_output_scaled(SRV_Channel::k_yaw_out)),
                       fbits(SRV_Channels::get_output_scaled(SRV_Channel::k_thrust_out)));
            }
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Motors/AP_MotorsMatrix.cpp",
          link_flags=vehicle_link.LINK_FLAGS)
    text = run(BUILD)
    # The harness emits two documents; split them at the second banner.
    marker = "#frames\n"
    if marker in text:
        first, second = text.split(marker, 1)
        OUT.write_text(first)
        spool_marker = "#spool\n"
        if spool_marker in second:
            second, third = second.split(spool_marker, 1)
            out_marker = "#output\n"
            if out_marker in third:
                third, fourth = third.split(out_marker, 1)
                thr_marker = "#throttle\n"
                if thr_marker in fourth:
                    fourth, fifth = fourth.split(thr_marker, 1)
                    ch_marker = "#channels\n"
                    if ch_marker in fifth:
                        fifth, sixth = fifth.split(ch_marker, 1)
                        CHANNELS_OUT.write_text(ch_marker + sixth)
                        rows = sum(1 for l in sixth.splitlines()
                                   if l and not l.startswith("#") and "," in l
                                   and not l[0].isalpha())
                        print("wrote %s: %d rows" % (CHANNELS_OUT.name, rows))
                    THROTTLE_OUT.write_text(thr_marker + fifth)
                    rows = sum(1 for l in fifth.splitlines()
                               if l and not l.startswith("#") and "," in l
                               and not l[0].isalpha())
                    print("wrote %s: %d rows" % (THROTTLE_OUT.name, rows))
                OUTPUT_OUT.write_text(out_marker + fourth)
                rows = sum(1 for l in fourth.splitlines()
                           if l and not l.startswith("#") and "," in l
                           and not l[0].isalpha())
                print("wrote %s: %d rows" % (OUTPUT_OUT.name, rows))
            SPOOL_OUT.write_text(spool_marker + third)
            rows = sum(1 for l in third.splitlines()
                       if l and not l.startswith("scenario,"))
            print("wrote %s: %d rows" % (SPOOL_OUT.name, rows))
        FRAMES_OUT.write_text(marker + second)
        frames = sum(1 for l in second.splitlines()
                     if l and not l.startswith("class,"))
        print("wrote %s: %d rows" % (FRAMES_OUT.name, frames))
    else:
        OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("frame,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
