#!/usr/bin/env python3
"""Generate the matrix_alg parity fixture by running upstream's own code.

Both the inputs and the outputs travel as raw bit patterns. The LU path is a
long chain of multiply-accumulate, so its last bits depend on the order of
operations; a decimal round-trip on either side would make an exact comparison
impossible and force a tolerance that could hide a real reordering.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/plane-fw-rust/fixtures/matrix_alg_parity.csv")
BUILD = Path("/tmp/matalg_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/matrix_alg.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/matrix_alg.cpp.
// Generated by tools/parity/gen_matrix_alg_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Reached only from AP_Math.cpp paths matrix_alg never takes. They abort, so a
// wrong assumption kills the harness rather than producing a fixture built on
// a different code path than the vehicle takes.
void AP_InternalError::error(const AP_InternalError::error_t e, uint16_t line)
{
    fprintf(stderr, "harness: unexpected internal error %u line %u",
            (unsigned)e, (unsigned)line);
    abort();
}
namespace AP {
AP_InternalError &internalerror() { fputs("harness: internalerror()", stderr); abort(); }
AP_CustomRotations &custom_rotations() { fputs("harness: custom_rotations()", stderr); abort(); }
}
void AP_HAL::panic(const char *m, ...) { fputs(m, stderr); abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// A fixed LCG, so the matrices are reproducible and the same on both sides.
static uint32_t rng_state = 987654321u;
static float next_val(void)
{
    rng_state = rng_state * 1103515245u + 12345u;
    // roughly [-4, 4), in steps that are exactly representable
    return (float)((int32_t)((rng_state >> 16) & 0xFFFF) - 32768) / 8192.0f;
}

// The kinds of matrix worth covering: the identity, a pure diagonal, a
// diagonally dominant one (what a well-conditioned JtJ looks like), a general
// one, and two that must be rejected.
enum kind { K_IDENTITY, K_DIAGONAL, K_DOMINANT, K_GENERAL, K_ZERO_ROW, K_DUPLICATE_ROW, K_COUNT };
static const char *kind_name[K_COUNT] = {
    "identity", "diagonal", "dominant", "general", "zero_row", "duplicate_row"
};

static void fill(float *a, uint16_t n, enum kind k)
{
    for (uint16_t i = 0; i < n; i++) {
        for (uint16_t j = 0; j < n; j++) {
            float v;
            switch (k) {
            case K_IDENTITY: v = (i == j) ? 1.0f : 0.0f; break;
            case K_DIAGONAL: v = (i == j) ? (float)(i + 2) : 0.0f; break;
            case K_DOMINANT: v = (i == j) ? (10.0f + (float)i)
                                          : 1.0f / (1.0f + fabsf((float)i - (float)j)); break;
            case K_GENERAL:  v = next_val(); break;
            case K_ZERO_ROW: v = (i == 1) ? 0.0f : next_val(); break;
            case K_DUPLICATE_ROW: v = next_val(); break;
            default: v = 0.0f; break;
            }
            a[i*n + j] = v;
        }
    }
    if (k == K_DUPLICATE_ROW && n >= 2) {
        // make row 1 a copy of row 0, so the matrix is exactly singular
        for (uint16_t j = 0; j < n; j++) {
            a[1*n + j] = a[0*n + j];
        }
    }
}

int main(void)
{
    static const uint16_t dims[] = { 3, 4, 5, 6, 9 };
    const int ndims = sizeof(dims)/sizeof(dims[0]);

    printf("#cases\n");
    printf("kind,n,rep,ok,in,out\n");

    for (int d = 0; d < ndims; d++) {
        const uint16_t n = dims[d];
        for (int k = 0; k < K_COUNT; k++) {
            // several draws of the randomised kinds, one of the fixed ones
            const int reps = (k == K_GENERAL || k == K_ZERO_ROW || k == K_DUPLICATE_ROW) ? 4 : 1;
            for (int r = 0; r < reps; r++) {
                float a[81], inv[81];
                fill(a, n, (enum kind)k);
                memset(inv, 0, sizeof(inv));
                const bool ok = mat_inverse(a, inv, n);

                printf("%s,%u,%d,%d,", kind_name[k], (unsigned)n, r, ok ? 1 : 0);
                for (uint16_t i = 0; i < (uint16_t)(n*n); i++) {
                    printf("%s%u", i ? " " : "", fbits(a[i]));
                }
                printf(",");
                for (uint16_t i = 0; i < (uint16_t)(n*n); i++) {
                    printf("%s%u", i ? " " : "", fbits(ok ? inv[i] : 0.0f));
                }
                printf("\n");
            }
        }
    }

    // mat_mul and mat_identity, which have no failure mode but are still part
    // of the ported surface
    printf("#mul\n");
    printf("n,a,b,c\n");
    for (int d = 0; d < ndims; d++) {
        const uint16_t n = dims[d];
        float a[81], b[81], c[81];
        fill(a, n, K_GENERAL);
        fill(b, n, K_GENERAL);
        mat_mul(a, b, c, n);
        printf("%u,", (unsigned)n);
        for (uint16_t i = 0; i < (uint16_t)(n*n); i++) printf("%s%u", i ? " " : "", fbits(a[i]));
        printf(",");
        for (uint16_t i = 0; i < (uint16_t)(n*n); i++) printf("%s%u", i ? " " : "", fbits(b[i]));
        printf(",");
        for (uint16_t i = 0; i < (uint16_t)(n*n); i++) printf("%s%u", i ? " " : "", fbits(c[i]));
        printf("\n");
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/matrix_alg.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)

    counts = {}
    section = None
    for line in text.splitlines():
        if line.startswith("#"):
            section = line[1:]
            counts[section] = -1
        elif section:
            counts[section] += 1
    print("wrote %s" % OUT.name)
    for k, v in counts.items():
        print("  %-8s %d rows" % (k, v))


if __name__ == "__main__":
    main()
