#!/usr/bin/env python3
"""Parity fixture for Location's offset operations (FW-029 prerequisite).

offset(), offset_bearing() and line_path_proportion() are what
type_slope_setup_landing_glide_slope uses to place the aim point and work out
where the vehicle sits along the approach. None of them existed in the port.

The cases go where the arithmetic is delicate rather than where it is
comfortable: the dateline, both poles, the equator, large offsets that cross
all three, negative distances (the landing aim point is placed *short* of the
threshold), and points projected beyond both ends of a line.

Both offset() and offset_bearing() mutate in place, so each row carries the
starting coordinates as well as the result.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/location_offset.csv"
BUILD = Path("/tmp/locoff_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Common/Location.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
    "build/sitl/libraries/AP_Math/location.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Common/Location.cpp offset operations.
// Generated by tools/parity/gen_location_offset_fixture.py -- do not edit.
#include <AP_Math/AP_Math.h>
#include <AP_Common/Location.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_Terrain/AP_Terrain.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

// Location.cpp's altitude-frame conversion asks the AHRS for the EKF origin
// and the terrain database for ground height. Neither is on the path to
// offset, offset_bearing or line_path_proportion, which are pure functions of
// latitude, longitude and the arguments. Aborting keeps that claim honest.
namespace AP {
AP_AHRS &ahrs() { fputs("harness: unexpected AP::ahrs()\n", stderr); abort(); }
AP_Terrain *terrain() { fputs("harness: unexpected AP::terrain()\n", stderr); abort(); }
}
bool AP_AHRS::get_origin(Location &) const
{
    fputs("harness: unexpected get_origin\n", stderr);
    abort();
}
bool AP_Terrain::height_amsl(const Location &, float &, bool)
{
    fputs("harness: unexpected height_amsl\n", stderr);
    abort();
}

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// lat, lng in 1e-7 degrees
static const struct { int32_t lat; int32_t lng; } points[] = {
    {          0,          0 },   // the null island
    {  515080000,   -1268000 },   // London
    { -353632621,  1491652374 },  // Canberra, from the replay fixtures
    {  899000000,          0 },   // just short of the north pole
    { -899000000,          0 },   // and the south
    {  450000000,  1799999000 },  // a whisker west of the dateline
    {  450000000, -1799999000 },  // and a whisker east
    {  600000000,          0 },   // high latitude, where meridians converge
    {         10,         10 },   // a hair off the origin
};

// north, east offsets in metres
static const struct { float n; float e; } offsets[] = {
    {      0,      0 },
    {      1,      0 },
    {      0,      1 },
    {   -1,      -1 },
    {    100,    100 },
    {  -100,    -100 },
    {  1000,   5000 },
    { 50000, -50000 },
    { 200000,      0 },   // 200 km north: enough to cross a pole from 89 deg
    {      0, 200000 },   // and enough to cross the dateline
    {  0.05f,  0.05f },   // below the resolution of a 1e-7 degree step
};

// bearing in degrees, distance in metres
static const struct { float bearing; float distance; } bearings[] = {
    {   0,    100 },
    {  90,    100 },
    { 180,    100 },
    { 270,    100 },
    {  45,   1000 },
    { 225,   1000 },
    {   0,   -500 },   // negative: the landing aim point sits short
    {  37,   -500 },
    { 359.9f, 250 },
    { 720,    100 },   // more than a full turn
    { -45,    100 },
};

int main(void)
{
    printf("#location_offset\n");
    printf("kind,lat,lng,a,b,out1,out2\n");

    for (unsigned i = 0; i < ARRAY_SIZE(points); i++) {
        for (unsigned j = 0; j < ARRAY_SIZE(offsets); j++) {
            Location l{};
            l.lat = points[i].lat;
            l.lng = points[i].lng;
            l.offset(offsets[j].n, offsets[j].e);
            printf("offset,%d,%d,%u,%u,%d,%d\n",
                   points[i].lat, points[i].lng,
                   fbits(offsets[j].n), fbits(offsets[j].e),
                   l.lat, l.lng);
        }
        for (unsigned j = 0; j < ARRAY_SIZE(bearings); j++) {
            Location l{};
            l.lat = points[i].lat;
            l.lng = points[i].lng;
            l.offset_bearing(bearings[j].bearing, bearings[j].distance);
            printf("bearing,%d,%d,%u,%u,%d,%d\n",
                   points[i].lat, points[i].lng,
                   fbits(bearings[j].bearing), fbits(bearings[j].distance),
                   l.lat, l.lng);
        }
    }

    // line_path_proportion: every ordered triple of points, so the query point
    // lands on, off, and well beyond both ends of the line.
    for (unsigned a = 0; a < ARRAY_SIZE(points); a++) {
        for (unsigned b = 0; b < ARRAY_SIZE(points); b++) {
            for (unsigned c = 0; c < ARRAY_SIZE(points); c++) {
                Location p1{}, p2{}, q{};
                p1.lat = points[a].lat; p1.lng = points[a].lng;
                p2.lat = points[b].lat; p2.lng = points[b].lng;
                q.lat  = points[c].lat; q.lng  = points[c].lng;
                printf("proportion,%d,%d,%d,%d,%u,%d\n",
                       points[a].lat, points[a].lng,
                       points[b].lat, points[b].lng,
                       fbits(q.line_path_proportion(p1, p2)),
                       points[c].lat);
                // the query point's longitude goes in a companion row, since
                // the row shape is already full
                printf("proportion_q,%d,%d,0,0,0,0\n", points[c].lat, points[c].lng);
            }
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Common/Location.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("kind"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
