#!/usr/bin/env python3
"""Generate the VectorN/MatrixN parity fixture from upstream's own code.

`vectorN.h` is header-only, so any `N` instantiates inline. `matrixN.cpp`
explicitly instantiates only `MatrixN<float,4>`, which is what the soaring EKF
uses, so the matrix cases are all N=4.

`force_symmetry` is included deliberately even though the port diverges from it
(D-014). Recording what upstream actually produces is what lets the port assert
the divergence precisely — that the two agree on every pair except the
sub-diagonal — rather than merely skipping the comparison.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/plane-fw-rust/fixtures/vector_n_parity.csv")
BUILD = Path("/tmp/vecn_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/matrixN.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/vectorN.h and matrixN.{h,cpp}.
// Generated by tools/parity/gen_vector_n_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Math/vectorN.h>
#include <AP_Math/matrixN.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Reached only from AP_Math.cpp paths this harness never takes; they abort so
// a wrong assumption is loud.
void AP_InternalError::error(const AP_InternalError::error_t e, uint16_t line)
{
    fprintf(stderr, "harness: internal error %u line %u", (unsigned)e, (unsigned)line);
    abort();
}
namespace AP {
AP_InternalError &internalerror() { fputs("harness: internalerror()", stderr); abort(); }
AP_CustomRotations &custom_rotations() { fputs("harness: custom_rotations()", stderr); abort(); }
}
void AP_HAL::panic(const char *m, ...) { fputs(m, stderr); abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

static uint32_t rng_state = 24681357u;
static float next_val(void)
{
    rng_state = rng_state * 1103515245u + 12345u;
    return (float)((int32_t)((rng_state >> 16) & 0xFFFF) - 32768) / 4096.0f;
}

template <uint8_t N>
static void emit_vec(const char *op, const VectorN<float,N> &r)
{
    printf("%s,%u,", op, (unsigned)N);
    for (uint8_t i = 0; i < N; i++) {
        printf("%s%u", i ? " " : "", fbits(r[i]));
    }
    printf("\n");
}

template <uint8_t N>
static void vector_cases(void)
{
    VectorN<float,N> a, b;
    for (uint8_t i = 0; i < N; i++) {
        a[i] = next_val();
        b[i] = next_val();
    }
    const float s = next_val();

    emit_vec<N>("in_a", a);
    emit_vec<N>("in_b", b);
    printf("in_s,%u,%u\n", (unsigned)N, fbits(s));

    emit_vec<N>("neg", -a);
    emit_vec<N>("add", a + b);
    emit_vec<N>("sub", a - b);
    emit_vec<N>("mul", a * s);
    emit_vec<N>("div", a / s);

    VectorN<float,N> c = a; c += b; emit_vec<N>("add_assign", c);
    c = a; c -= b; emit_vec<N>("sub_assign", c);
    c = a; c *= s; emit_vec<N>("mul_assign", c);
    c = a; c /= s; emit_vec<N>("div_assign", c);

    // the dot product, whose accumulator upstream declares as float
    printf("dot,%u,%u\n", (unsigned)N, fbits(a * b));

}

int main(void)
{
    printf("#vec\n");
    printf("op,n,vals\n");
    vector_cases<2>();
    vector_cases<3>();
    vector_cases<4>();
    vector_cases<5>();
    vector_cases<9>();

    // MatrixN: only <float,4> is explicitly instantiated upstream, which is
    // what the soaring EKF uses.
    printf("#mat4\n");
    printf("op,vals\n");
    {
        VectorN<float,4> a, b;
        for (uint8_t i = 0; i < 4; i++) { a[i] = next_val(); b[i] = next_val(); }

        printf("in_a,");
        for (uint8_t i = 0; i < 4; i++) printf("%s%u", i ? " " : "", fbits(a[i]));
        printf("\n");
        printf("in_b,");
        for (uint8_t i = 0; i < 4; i++) printf("%s%u", i ? " " : "", fbits(b[i]));
        printf("\n");

        MatrixN<float,4> m;
        m.mult(a, b);   // outer product
        printf("outer,");
        for (uint8_t i = 0; i < 4; i++)
            for (uint8_t j = 0; j < 4; j++)
                printf("%s%u", (i||j) ? " " : "", fbits(*((const float*)&m + i*4 + j)));
        printf("\n");

        // an asymmetric matrix, then upstream's force_symmetry over it
        MatrixN<float,4> s;
        float raw[16];
        for (uint8_t i = 0; i < 16; i++) raw[i] = (float)i;
        memcpy(&s, raw, sizeof(raw));
        printf("sym_in,");
        for (uint8_t i = 0; i < 16; i++) printf("%s%u", i ? " " : "", fbits(raw[i]));
        printf("\n");

        s.force_symmetry();
        printf("sym_out,");
        for (uint8_t i = 0; i < 16; i++)
            printf("%s%u", i ? " " : "", fbits(*((const float*)&s + i)));
        printf("\n");

        // += and -=
        MatrixN<float,4> p, q;
        float rawp[16], rawq[16];
        for (uint8_t i = 0; i < 16; i++) { rawp[i] = next_val(); rawq[i] = next_val(); }
        memcpy(&p, rawp, sizeof(rawp));
        memcpy(&q, rawq, sizeof(rawq));
        printf("in_p,");
        for (uint8_t i = 0; i < 16; i++) printf("%s%u", i ? " " : "", fbits(rawp[i]));
        printf("\n");
        printf("in_q,");
        for (uint8_t i = 0; i < 16; i++) printf("%s%u", i ? " " : "", fbits(rawq[i]));
        printf("\n");

        MatrixN<float,4> r = p; r += q;
        printf("add,");
        for (uint8_t i = 0; i < 16; i++) printf("%s%u", i ? " " : "", fbits(*((const float*)&r + i)));
        printf("\n");
        r = p; r -= q;
        printf("sub,");
        for (uint8_t i = 0; i < 16; i++) printf("%s%u", i ? " " : "", fbits(*((const float*)&r + i)));
        printf("\n");
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/matrixN.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)

    counts = {}
    section = None
    for line in text.splitlines():
        if line.startswith("#"):
            section = line[1:]
            counts[section] = -1
        elif section:
            counts[section] += 1
    print("wrote %s" % OUT.name)
    for k, v in counts.items():
        print("  %-6s %d rows" % (k, v))


if __name__ == "__main__":
    main()
