#!/usr/bin/env python3
"""Parity fixture for SCurve::calculate_path.

calculate_path is the static time-solver: given snap, jerk, start speed,
accel, cruise speed and length, it returns the five numbers a 23-segment
track is built from (Jm, tj, t2, t4, t6).

It is public and takes every piece of state as an argument, so the harness
calls it directly — no `#define private public`, and nothing depends on
class layout. INTERNAL_ERROR is stubbed empty: invalid inputs still return
the same zeroed outputs the vehicle would after logging.

The grids cross every branch: non-positive limits, V0 >= Vm, a length too
short to accelerate, the small-At shrink-tj path from rest, the speed-change
path with V0 != 0, and the four solutions (0 / 2 / 5 / 7).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/worktrees/cop-002-scurve")
OUT = ROOT / "fixtures/scurve_path_parity.csv"
BUILD = Path("/tmp/scurve_path_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/SCurve.cpp.4.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
    "build/sitl/libraries/AP_Math/control.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/SCurve.cpp calculate_path.
// Generated by tools/parity/gen_scurve_path_fixture.py -- do not edit by hand.

#include <AP_Math/AP_Math.h>
#include <AP_Math/SCurve.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

int main(void)
{
    printf("#scurve_path\n");
    printf("sm,jm,v0,am,vm,l,jm_out,tj_out,t2,t4,t6\n");

    static const float sms[] = { 0.0f, -1.0f, 10.0f, 40.0f, 100.0f, 400.0f };
    static const float jms[] = { 0.0f, -1.0f, 1.0f, 5.0f, 20.0f, 40.0f };
    static const float v0s[] = { 0.0f, 1.0f, 5.0f, 10.0f, 15.0f };
    static const float ams[] = { 0.0f, 1.0f, 2.5f, 5.0f, 10.0f };
    static const float vms[] = { 0.0f, 1.0f, 5.0f, 10.0f, 15.0f, 20.0f };
    static const float ls[]  = { 0.0f, 1.0f, 5.0f, 10.0f, 50.0f, 100.0f, 200.0f, 500.0f };

    for (unsigned i0 = 0; i0 < ARRAY_SIZE(sms); i0++) {
        for (unsigned i1 = 0; i1 < ARRAY_SIZE(jms); i1++) {
            for (unsigned i2 = 0; i2 < ARRAY_SIZE(v0s); i2++) {
                for (unsigned i3 = 0; i3 < ARRAY_SIZE(ams); i3++) {
                    for (unsigned i4 = 0; i4 < ARRAY_SIZE(vms); i4++) {
                        for (unsigned i5 = 0; i5 < ARRAY_SIZE(ls); i5++) {
                            float Jm_out, tj_out, t2_out, t4_out, t6_out;
                            SCurve::calculate_path(
                                sms[i0], jms[i1], v0s[i2], ams[i3], vms[i4], ls[i5],
                                Jm_out, tj_out, t2_out, t4_out, t6_out);
                            printf("%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u\n",
                                   fbits(sms[i0]), fbits(jms[i1]), fbits(v0s[i2]),
                                   fbits(ams[i3]), fbits(vms[i4]), fbits(ls[i5]),
                                   fbits(Jm_out), fbits(tj_out),
                                   fbits(t2_out), fbits(t4_out), fbits(t6_out));
                        }
                    }
                }
            }
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/SCurve.cpp")
    text = run(BUILD)
    # SITL builds printf "invalid inputs/outputs" to stdout; keep CSV only.
    kept = []
    for line in text.splitlines():
        s = line.strip()
        if s.startswith("#") or s.startswith("sm,") or (s and s[0].isdigit()):
            kept.append(s)
    text = "\n".join(kept) + "\n"
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("sm,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
