#!/usr/bin/env python3
"""Generate the polygon parity fixture by running upstream's own polygon.cpp.

Compiled with the flags waf used and linked against the objects waf already
built, so the harness sees exactly the definitions the firmware does.

Float results are emitted as raw bit patterns rather than decimal text. These
functions return distances computed through sqrtf, and a decimal round-trip
would blur the last bit — precisely where a port difference would first show
up. The Rust side reads them with `f32::from_bits`, so the comparison is exact
and any tolerance is a deliberate choice rather than an artefact of printing.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/ardumaster-rust/fixtures/polygon_parity.csv")
BUILD = Path("/tmp/poly_parity/harness")

# Only what the polygon path needs. AP_Math.cpp is here for is_equal<>, which
# Vector2's integer comparison operators call; its unreachable internal-error
# references are stubbed in the harness below.
OBJECTS = [
    "build/sitl/libraries/AP_Math/polygon.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/polygon.cpp.
// Generated by tools/parity/gen_polygon_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Math/polygon.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// AP_Math.cpp references the internal-error singleton from float_to_uint32 and
// friends. Nothing on the polygon path reaches them: is_equal<> for integral
// types, which is what Vector2's comparison operators need, is pure. Linking
// the real implementation would pull in AP_HAL and most of the vehicle, so
// these stand in for it.
//
// They abort rather than return. If the assumption above is ever wrong, the
// harness dies loudly instead of quietly emitting a fixture built on a
// different code path than the vehicle takes.
void AP_InternalError::error(const AP_InternalError::error_t e, uint16_t line)
{
    fprintf(stderr, "harness: unexpected internal error %u line %u -- the "
                    "polygon path was assumed not to reach this",
            (unsigned)e, (unsigned)line);
    abort();
}
namespace AP {
AP_InternalError &internalerror()
{
    fputs("harness: unexpected internalerror() call", stderr);
    abort();
}
AP_CustomRotations &custom_rotations()
{
    fputs("harness: unexpected custom_rotations() call", stderr);
    abort();
}
}

void AP_HAL::panic(const char *errormsg, ...)
{
    fputs(errormsg, stderr);
    abort();
}

void AP_CustomRotations::rotate(enum Rotation, Vector3f &)
{
    fputs("harness: unexpected custom rotate()", stderr);
    abort();
}
void AP_CustomRotations::rotate(enum Rotation, Vector3d &)
{
    fputs("harness: unexpected custom rotate()", stderr);
    abort();
}

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// The polygons. Coordinates are whole numbers so they are exactly
// representable as both float and int32, letting the same shapes drive the
// float and integer instantiations of Polygon_outside.
struct poly { const char *name; int n; const int32_t (*pts)[2]; };

static const int32_t square_closed[][2] = {{0,0},{0,100},{100,100},{100,0},{0,0}};
static const int32_t square_open[][2]   = {{0,0},{0,100},{100,100},{100,0}};
static const int32_t tri_closed[][2]    = {{0,0},{100,0},{50,100},{0,0}};
// concave L: a naive even-odd test gets the reflex vertex wrong
static const int32_t ell_closed[][2]    = {{0,0},{0,100},{50,100},{50,50},{100,50},{100,0},{0,0}};
static const int32_t big_closed[][2]    = {{-100,-100},{-100,100},{100,100},{100,-100},{-100,-100}};
// fewer than 4 points, so never "complete"
static const int32_t degenerate[][2]    = {{0,0},{10,0},{0,0}};

static const struct poly polys[] = {
    { "square_closed", 5, square_closed },
    { "square_open",   4, square_open   },
    { "tri_closed",    4, tri_closed    },
    { "ell_closed",    7, ell_closed    },
    { "big_closed",    5, big_closed    },
    { "degenerate",    3, degenerate    },
};
static const int npolys = sizeof(polys)/sizeof(polys[0]);

// Probe points: a grid straddling every boundary, plus the vertices and edge
// midpoints. On-boundary cases are exactly where point-in-polygon
// implementations disagree, so they belong in the fixture rather than being
// avoided.
static const int32_t extra_pts[][2] = {
    {0,0},{0,100},{100,100},{100,0},{50,100},{50,50},{-100,-100},{100,-100},
    {50,0},{0,50},{100,50},{25,100},{50,25},{75,50},{-100,0},{0,-100},
};

// Segments: crossing, missing entirely, touching a vertex, collinear with an
// edge, degenerate (zero length), and fully inside.
static const int32_t segs[][4] = {
    {-50,50,150,50}, {-50,-50,150,150}, {200,200,300,300}, {25,25,75,75},
    {0,0,100,100}, {-50,0,50,0}, {50,-50,50,150}, {0,100,100,100},
    {-10,-10,10,10}, {110,50,90,50}, {50,50,50,50}, {-200,50,-150,50},
};
static const int nsegs = sizeof(segs)/sizeof(segs[0]);

static void load(const struct poly *p, Vector2f *vf, Vector2l *vl)
{
    for (int i = 0; i < p->n; i++) {
        if (vf) vf[i] = Vector2f((float)p->pts[i][0], (float)p->pts[i][1]);
        if (vl) vl[i] = Vector2l(p->pts[i][0], p->pts[i][1]);
    }
}

int main(void)
{
    printf("#polys\n");
    printf("name,n,coords\n");
    for (int p = 0; p < npolys; p++) {
        printf("%s,%d,", polys[p].name, polys[p].n);
        for (int i = 0; i < polys[p].n; i++) {
            printf("%d %d%s", polys[p].pts[i][0], polys[p].pts[i][1],
                   i + 1 < polys[p].n ? " " : "");
        }
        printf("\n");
    }

    printf("#complete\n");
    printf("poly,n,as_float,as_int\n");
    for (int p = 0; p < npolys; p++) {
        Vector2f vf[8]; Vector2l vl[8];
        load(&polys[p], vf, vl);
        // every prefix length, covering the n<4 and last!=first paths
        for (int n = 0; n <= polys[p].n; n++) {
            printf("%s,%d,%d,%d\n", polys[p].name, n,
                   Polygon_complete(vf, n) ? 1 : 0,
                   Polygon_complete(vl, n) ? 1 : 0);
        }
    }

    printf("#outside\n");
    printf("poly,px,py,as_float,as_int\n");
    for (int p = 0; p < npolys; p++) {
        Vector2f vf[8]; Vector2l vl[8];
        load(&polys[p], vf, vl);
        for (int x = -150; x <= 150; x += 25) {
            for (int y = -150; y <= 150; y += 25) {
                printf("%s,%d,%d,%d,%d\n", polys[p].name, x, y,
                       Polygon_outside(Vector2f((float)x,(float)y), vf, polys[p].n) ? 1 : 0,
                       Polygon_outside(Vector2l(x,y), vl, polys[p].n) ? 1 : 0);
            }
        }
        for (unsigned k = 0; k < sizeof(extra_pts)/sizeof(extra_pts[0]); k++) {
            const int32_t x = extra_pts[k][0], y = extra_pts[k][1];
            printf("%s,%d,%d,%d,%d\n", polys[p].name, x, y,
                   Polygon_outside(Vector2f((float)x,(float)y), vf, polys[p].n) ? 1 : 0,
                   Polygon_outside(Vector2l(x,y), vl, polys[p].n) ? 1 : 0);
        }
    }

    printf("#intersects\n");
    printf("poly,p1x,p1y,p2x,p2y,found,ix,iy\n");
    for (int p = 0; p < npolys; p++) {
        Vector2f vf[8];
        load(&polys[p], vf, NULL);
        for (int s = 0; s < nsegs; s++) {
            Vector2f p1((float)segs[s][0], (float)segs[s][1]);
            Vector2f p2((float)segs[s][2], (float)segs[s][3]);
            Vector2f ix(0,0);
            const bool found = Polygon_intersects(vf, polys[p].n, p1, p2, ix);
            printf("%s,%d,%d,%d,%d,%d,%u,%u\n", polys[p].name,
                   segs[s][0], segs[s][1], segs[s][2], segs[s][3],
                   found ? 1 : 0, fbits(ix.x), fbits(ix.y));
        }
    }

    printf("#dist_line\n");
    printf("poly,p1x,p1y,p2x,p2y,dist\n");
    for (int p = 0; p < npolys; p++) {
        Vector2f vf[8];
        load(&polys[p], vf, NULL);
        for (int s = 0; s < nsegs; s++) {
            Vector2f p1((float)segs[s][0], (float)segs[s][1]);
            Vector2f p2((float)segs[s][2], (float)segs[s][3]);
            const float d = Polygon_closest_distance_line(vf, polys[p].n, p1, p2);
            printf("%s,%d,%d,%d,%d,%u\n", polys[p].name,
                   segs[s][0], segs[s][1], segs[s][2], segs[s][3], fbits(d));
        }
    }

    printf("#dist_point\n");
    printf("poly,px,py,ok,cx,cy\n");
    for (int p = 0; p < npolys; p++) {
        Vector2f vf[8];
        load(&polys[p], vf, NULL);
        for (int x = -150; x <= 150; x += 50) {
            for (int y = -150; y <= 150; y += 50) {
                Vector2f c(0,0);
                const bool ok = Polygon_closest_distance_point(
                    vf, polys[p].n, Vector2f((float)x,(float)y), c);
                printf("%s,%d,%d,%d,%u,%u\n", polys[p].name, x, y,
                       ok ? 1 : 0, fbits(c.x), fbits(c.y));
            }
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/polygon.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)

    counts = {}
    section = None
    for line in text.splitlines():
        if line.startswith("#"):
            section = line[1:]
            counts[section] = -1  # discount the column header
        elif section:
            counts[section] += 1
    print("wrote %s" % OUT.name)
    for k, v in counts.items():
        print("  %-12s %d rows" % (k, v))


if __name__ == "__main__":
    main()
