#!/usr/bin/env python3
"""Parity fixture for the IGRF world magnetic model lookup.

A dense sweep of the globe plus every awkward point: the table's four edges,
a hair inside and a hair outside each, exact grid points where both
interpolation fractions are zero, and the poles and dateline where the field
varies fastest against a ten-degree grid.

Dense because it is cheap: the lookup is a table read and six multiplies, so
sixteen thousand points cost nothing and leave no room for an off-by-one in
the indexing to hide in a region nobody sampled.

All three outputs are compared, and so is the coverage flag -- upstream returns
it as the function's value and `get_declination` throws it away, so it is the
part most likely to be got wrong quietly.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/ardumaster-rust")
OUT = ROOT / "fixtures/declination_parity.csv"
BUILD = Path("/tmp/decl_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Declination/AP_Declination.cpp.0.o",
    "build/sitl/libraries/AP_Declination/tables.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Declination.
// Generated by tools/parity/gen_declination_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Declination/AP_Declination.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

static void emit(float lat, float lon)
{
    float intensity = 0, declination = 0, inclination = 0;
    const bool covered = AP_Declination::get_mag_field_ef(lat, lon, intensity,
                                                          declination, inclination);
    printf("%u,%u,%u,%u,%u,%d\n",
           fbits(lat), fbits(lon),
           fbits(intensity), fbits(declination), fbits(inclination),
           covered ? 1 : 0);
}

int main(void)
{
    printf("#declination\n");
    printf("lat,lon,intensity,declination,inclination,covered\n");

    // A dense sweep, two degrees.
    for (int ilat = -90; ilat <= 90; ilat += 2) {
        for (int ilon = -180; ilon <= 180; ilon += 2) {
            emit((float)ilat, (float)ilon);
        }
    }

    // The edges, and a hair either side of each.
    static const float edges[] = {
        -90.0f, -89.999f, -89.99f, 89.99f, 89.999f, 90.0f,
    };
    for (unsigned i = 0; i < ARRAY_SIZE(edges); i++) {
        emit(edges[i], 0.0f);
        emit(edges[i], 45.0f);
    }
    static const float lon_edges[] = {
        -180.0f, -179.999f, -179.99f, 179.99f, 179.999f, 180.0f,
    };
    for (unsigned i = 0; i < ARRAY_SIZE(lon_edges); i++) {
        emit(0.0f, lon_edges[i]);
        emit(45.0f, lon_edges[i]);
    }

    // Exact grid points: both interpolation fractions are zero there, so the
    // answer should be the table entry itself.
    for (int ilat = -90; ilat <= 90; ilat += 10) {
        for (int ilon = -180; ilon <= 180; ilon += 10) {
            emit((float)ilat, (float)ilon);
        }
    }

    // Fractions that are not nice numbers, to catch a rounding that only
    // works on tenths.
    static const struct { float lat, lon; } odd[] = {
        { 51.5074f,   -0.1278f },   // London
        {-35.2809f,  149.1300f },   // Canberra
        { 47.6062f, -122.3321f },   // Seattle
        {-33.8688f,  151.2093f },   // Sydney
        { 64.1466f,  -21.9426f },   // Reykjavik
        {-54.8019f,  -68.3030f },   // Ushuaia
        {  1.3521f,  103.8198f },   // Singapore
        { 78.2232f,   15.6267f },   // Longyearbyen
        {-77.8463f,  166.6683f },   // McMurdo
        {  0.0f,       0.0f    },
        {  0.001f,     0.001f  },
        { -0.001f,    -0.001f  },
        {  9.999f,     9.999f  },
        { 10.001f,    10.001f  },
        {-10.001f,   -10.001f  },
    };
    for (unsigned i = 0; i < ARRAY_SIZE(odd); i++) {
        emit(odd[i].lat, odd[i].lon);
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Declination/AP_Declination.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("lat,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
