#!/usr/bin/env python3
"""Generate the rotations parity fixture from upstream's own Vector3::rotate.

Exhaustive over the enum: every value 0..=103 is attempted, not just the ones
that name a rotation, so the port's handling of `ROTATION_MAX`,
`ROTATION_CUSTOM_OLD` and `ROTATION_CUSTOM_END` is compared too rather than
assumed.

Upstream reports an internal error and leaves the vector alone for those, so
the harness records the vector as unchanged and a flag saying it was rejected.
The port returns `Err` and likewise leaves it alone; the test checks both.

`ROTATION_CUSTOM_1` and `_2` are skipped entirely: upstream compiles them out
unless `AP_CUSTOMROTATIONS_ENABLED`, and with it enabled they call into a
library that is not ported.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/plane-fw-rust/fixtures/rotations_parity.csv")
BUILD = Path("/tmp/rot_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/vector3.cpp's rotate().
// Generated by tools/parity/gen_rotations_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// Upstream reports INTERNAL_ERROR(bad_rotation) for the non-rotations, which
// is a case the fixture deliberately covers -- so this records the call rather
// than aborting, and main() reads it back.
static bool saw_internal_error = false;
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t)
{
    saw_internal_error = true;
}
namespace AP {
AP_InternalError &internalerror()
{
    // returning a reference to a dummy is enough: nothing reads it, and the
    // error() above is what records the event
    static AP_InternalError dummy;
    return dummy;
}
AP_CustomRotations &custom_rotations()
{
    fputs("harness: custom rotations are deliberately not exercised", stderr);
    abort();
}
}
void AP_HAL::panic(const char *m, ...) { fputs(m, stderr); abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// Probe vectors: axis-aligned, so a swapped axis is unmissable; a general one
// where every component differs in magnitude and sign; and one with a large
// and a small component together, which is where the difference between
// "subtract then promote" and "promote then subtract" would show.
static const float probes[][3] = {
    {1.0f, 0.0f, 0.0f},
    {0.0f, 1.0f, 0.0f},
    {0.0f, 0.0f, 1.0f},
    {1.0f, 2.0f, 3.0f},
    {-3.5f, 7.25f, -11.125f},
    {1.0e20f, 1.0f, -1.0f},
    {123.456f, -789.012f, 0.0009765625f},
};
static const int nprobes = sizeof(probes)/sizeof(probes[0]);

int main(void)
{
    printf("#rot\n");
    printf("rotation,probe,rejected,x,y,z\n");

    for (int r = 0; r <= 103; r++) {
        // custom rotations delegate to a library that is not ported
        if (r == ROTATION_CUSTOM_1 || r == ROTATION_CUSTOM_2) {
            continue;
        }
        for (int p = 0; p < nprobes; p++) {
            Vector3f v(probes[p][0], probes[p][1], probes[p][2]);
            saw_internal_error = false;
            v.rotate((enum Rotation)r);
            printf("%d,%d,%d,%u,%u,%u\n", r, p, saw_internal_error ? 1 : 0,
                   fbits(v.x), fbits(v.y), fbits(v.z));
        }
    }

    printf("#probes\n");
    printf("probe,x,y,z\n");
    for (int p = 0; p < nprobes; p++) {
        printf("%d,%u,%u,%u\n", p,
               fbits(probes[p][0]), fbits(probes[p][1]), fbits(probes[p][2]));
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/vector3.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)

    counts, section = {}, None
    for line in text.splitlines():
        if line.startswith("#"):
            section = line[1:]
            counts[section] = -1
        elif section:
            counts[section] += 1
    print("wrote %s" % OUT.name)
    for k, v in counts.items():
        print("  %-8s %d rows" % (k, v))


if __name__ == "__main__":
    main()
