#!/usr/bin/env python3
"""INCOMPLETE. Parity fixture for the multirotor mixing factor model.

DOES NOT BUILD YET, and the reason is worth recording rather than retrying
blindly.

add_motor and normalise_rpy_factors are pure functions of the factor arrays and
touch nothing else. But they are members of AP_MotorsMatrix, and constructing
one runs AP_Motors_Class -> AP_MotorsMulticopter -> AP_MotorsMatrix, whose
constructors and output paths reach the AHRS, the battery monitor, SRV_Channels
and parameter persistence. Roughly twenty aborting stubs get most of the way;
the remaining wall is AP_ParamTBase<int16_t>::set_and_save, which cannot be
specialised after the header has instantiated it, so it needs AP_Param.cpp
linked -- and that drags in the storage manager, the filesystem and the GCS,
which is the swamp every other harness here deliberately avoids.

Two ways forward, neither attempted yet:
  1. Link AP_Param.cpp with --unresolved-symbols=ignore-all, as
     gen_param_fixture.py does. That flag is the documented approach for
     exactly this, but it turns any missed call into a jump to address zero, so
     it needs the aborting stubs to stay.
  2. Build a minimal AP_MotorsMatrix-shaped harness that calls the same
     arithmetic without constructing the class. Cheaper, but it tests a copy
     rather than the shipped object, which is not what parity means here.

Until then the port's own tests carry the slice: they pin the angle
convention, yaw independence from position, normalisation to exactly 0.5 per
axis, absence of cross-coupling on a symmetric frame, an axis with no
authority being left alone, independent per-axis scaling, throttle clamping,
out-of-range motor numbers, and test ordering.


add_motor and normalise_rpy_factors are `protected`, and so are the factor
arrays. A subclass reaches them with `using` declarations -- ordinary C++
access, no preprocessor tricks -- and adds no members of its own, so the layout
is unchanged. That is checked with a static_assert on sizeof rather than
assumed.

Frames are built by hand rather than through setup_motors(), because
setup_motors is 1,400 lines of frame tables that are their own slice. The
angles here are the standard ones for each layout, which is what those tables
contain.

The object MUST be static: AP_Motors_Class holds AP_Param members and the
add_motor path is guarded by initialised_ok(), so a stack instance would be
reading whatever was there.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/motors_parity.csv"
BUILD = Path("/tmp/motors_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Motors/AP_MotorsMatrix.cpp.3.o",
    "build/sitl/libraries/AP_Motors/AP_Motors_Class.cpp.0.o",
    "build/sitl/libraries/AP_Motors/AP_MotorsMulticopter.cpp.3.o",
    "build/sitl/libraries/AP_Motors/AP_Motors_Thrust_Linearization.cpp.3.o",
    "build/sitl/libraries/Filter/LowPassFilter.cpp.0.o",
    "build/sitl/libraries/Filter/DerivativeFilter.cpp.0.o",
    "build/sitl/libraries/AP_Param/AP_Param.cpp.0.o",
    "build/sitl/libraries/AP_Param/AP_ParamT.cpp.0.o",
    "build/sitl/libraries/StorageManager/StorageManager.cpp.3.o",
    "build/sitl/libraries/AP_HAL/Semaphores.cpp.0.o",
    "build/sitl/libraries/AP_HAL_SITL/Semaphores.cpp.0.o",
    "build/sitl/libraries/AP_HAL/utility/RingBuffer.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
    "build/sitl/libraries/AP_Math/crc.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Motors/AP_MotorsMatrix factor model.
// Generated by tools/parity/gen_motors_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Motors/AP_MotorsMatrix.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <SRV_Channel/SRV_Channel.h>
#include <AP_Logger/AP_Logger.h>
#include <Filter/LowPassFilter.h>
#include <Filter/DerivativeFilter.h>
#include <AP_Notify/AP_Notify.h>
#include <AP_AHRS/AP_AHRS.h>
#include <AP_BattMonitor/AP_BattMonitor.h>
#include <AP_Param/AP_Param.h>
#include <AP_Filesystem/AP_Filesystem.h>
#include <GCS_MAVLink/GCS.h>
#include <AP_HAL_SITL/Scheduler.h>
#include <AP_BoardConfig/AP_BoardConfig.h>
#include <AP_ROMFS/AP_ROMFS.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

// SRV_Channels is NOT linked. All add_motor_num does with it is register
// which output channel a motor uses, and linking it would drag in every ESC
// backend in the tree -- CAN, DroneCAN, FETtec, KDECAN, Piccolo, Robotis,
// SBus. None of that can reach the factor arrays this fixture reads, so the
// registration calls are no-ops. That is a claim about what they do, not a
// shortcut: if one of them affected a factor, every value below would be
// wrong and the port's own tests would still pass, which is why it is written
// down here.
bool SRV_Channels::set_aux_channel_default(SRV_Channel::Function, uint8_t) { return true; }
void SRV_Channels::set_angle(SRV_Channel::Function, uint16_t) {}
void SRV_Channels::set_range(SRV_Channel::Function, uint16_t) {}
uint32_t SRV_Channels::get_output_channel_mask(SRV_Channel::Function) { return 0; }
void SRV_Channels::set_output_scaled(SRV_Channel::Function, float) {}
bool SRV_Channels::find_channel(SRV_Channel::Function, uint8_t &) { return false; }
void SRV_Channels::set_output_pwm(SRV_Channel::Function, uint16_t) {}
uint32_t SRV_Channels::digital_mask;
SRV_Channels *SRV_Channels::_singleton;

// These are not on any path this harness takes. Aborting keeps that honest.
namespace AP {
AP_Logger &logger() { fputs("harness: unexpected logger()\n", stderr); abort(); }
}
void AP_Logger::WriteBlock(const void *, uint16_t)
{
    fputs("harness: unexpected WriteBlock\n", stderr);
    abort();
}
int AP_HAL::Util::snprintf(char *, size_t, const char *, ...)
{
    fputs("harness: unexpected snprintf\n", stderr);
    abort();
}

// AP_Notify's flag block. AP_Motors sets a couple of them on arming paths this
// fixture never takes; the storage just has to exist.
struct AP_Notify::notify_flags_and_values_type AP_Notify::flags;

// `hal` is referenced by AP_Motors_Class paths this harness does not take.
// Zeroed storage rather than a null reference: dereferencing it faults
// immediately, which is the same guarantee the aborting stubs give.
alignas(AP_HAL::HAL) static unsigned char hal_storage[sizeof(AP_HAL::HAL)] = {0};
const AP_HAL::HAL &hal = *reinterpret_cast<const AP_HAL::HAL *>(hal_storage);

// The rest of the chain. AP_Motors_Class -> AP_MotorsMulticopter ->
// AP_MotorsMatrix reaches the AHRS, the battery monitor and parameter
// persistence from its CONSTRUCTOR and its output paths. None of it is on the
// path to add_motor or normalise_rpy_factors, which are pure functions of the
// factor arrays -- so every one of these aborts, and the fixture would die
// rather than record a number that came from a fallback.
namespace AP {
AP_AHRS &ahrs() { fputs("harness: unexpected AP::ahrs()\n", stderr); abort(); }
AP_BattMonitor &battery() { fputs("harness: unexpected AP::battery()\n", stderr); abort(); }
}
float AP_AHRS::get_air_density_ratio() const
{
    fputs("harness: unexpected get_air_density_ratio\n", stderr);
    abort();
}
float AP_BattMonitor::voltage(uint8_t) const
{
    fputs("harness: unexpected battery voltage\n", stderr);
    abort();
}
float AP_BattMonitor::voltage_resting_estimate(uint8_t) const
{
    fputs("harness: unexpected battery resting voltage\n", stderr);
    abort();
}

// AP_Param.cpp is linked for real, so the motors object gets its parameter
// defaults the way a vehicle does. Stubbing setup_object_defaults to nothing
// would leave every parameter at zero -- a state no vehicle is ever in.

// The last of the chain, all reached from constructor or output paths.
bool AP_BattMonitor::current_amps(float &, uint8_t) const
{
    fputs("harness: unexpected battery current\n", stderr);
    abort();
}
// AP_Param's persistence layer. setup_object_defaults, which is all the
// motors constructor calls, only copies defaults into memory -- it never
// touches storage. Everything below is therefore off-path, and aborts so that
// a change which put it back on-path would be impossible to miss.
AP_Filesystem &AP::FS()
{
    fputs("harness: unexpected AP::FS()\n", stderr);
    abort();
}
int AP_Filesystem::close(int)
{
    fputs("harness: unexpected FS close\n", stderr);
    abort();
}
int AP_Filesystem::fsync(int)
{
    fputs("harness: unexpected FS fsync\n", stderr);
    abort();
}
int32_t AP_Filesystem::lseek(int, int32_t, int)
{
    fputs("harness: unexpected FS lseek\n", stderr);
    abort();
}
int32_t AP_Filesystem::write(int, const void *, uint32_t)
{
    fputs("harness: unexpected FS write\n", stderr);
    abort();
}
GCS &gcs()
{
    fputs("harness: unexpected gcs()\n", stderr);
    abort();
}
void GCS::send_text(MAV_SEVERITY, const char *, ...)
{
    fputs("harness: unexpected send_text\n", stderr);
    abort();
}

// The SITL scheduler's semaphore bookkeeping. Reached from WithSemaphore,
// which AP_Param takes around its storage access; the flag just has to exist.
bool HALSITL::Scheduler::_in_semaphore_take_wait;
bool HALSITL::Scheduler::semaphore_wait_hack_required() const { return false; }

// The last of AP_Param's reach. All of it is on the load and error paths, and
// setup_object_defaults takes neither.
int AP_Filesystem::open(const char *, int, bool)
{
    fputs("harness: unexpected FS open\n", stderr);
    abort();
}
int32_t AP_Filesystem::read(int, void *, uint32_t)
{
    fputs("harness: unexpected FS read\n", stderr);
    abort();
}
bool AP_Filesystem::fgets(char *, uint8_t, int)
{
    fputs("harness: unexpected FS fgets\n", stderr);
    abort();
}
void AP_BoardConfig::config_error(const char *, ...)
{
    fputs("harness: AP_BoardConfig::config_error\n", stderr);
    abort();
}
void AP_BoardConfig::allocation_error(const char *, ...)
{
    fputs("harness: AP_BoardConfig::allocation_error\n", stderr);
    abort();
}
void GCS::send_parameter_value(const char *, enum ap_var_type, float) {}

// The embedded-defaults reader. AP_Param looks for a defaults file in ROMFS on
// load; there is none here and load is not called anyway.
AP_BoardConfig *AP_BoardConfig::_singleton;
const uint8_t *AP_ROMFS::find_decompress(const char *, uint32_t &) { return nullptr; }
void AP_ROMFS::free(const uint8_t *) {}

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// Ordinary C++ access to protected members. No new members, so the layout is
// unchanged -- asserted rather than assumed.
class Probe : public AP_MotorsMatrix {
public:
    using AP_MotorsMatrix::add_motor;
    using AP_MotorsMatrix::add_motor_raw;
    using AP_MotorsMatrix::normalise_rpy_factors;
    using AP_MotorsMatrix::_roll_factor;
    using AP_MotorsMatrix::_pitch_factor;
    using AP_MotorsMatrix::_yaw_factor;
    using AP_MotorsMatrix::_throttle_factor;
    using AP_MotorsMatrix::motor_enabled;
    using AP_MotorsMatrix::_test_order;

    // AP_MotorsMatrix enforces a singleton in its constructor, so the fixture
    // reuses one instance and clears it between frames rather than building
    // six. Clearing is what setup_motors would do; there is no public
    // equivalent.
    void clear_motors() {
        for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
            _roll_factor[i] = 0.0f;
            _pitch_factor[i] = 0.0f;
            _yaw_factor[i] = 0.0f;
            _throttle_factor[i] = 0.0f;
            motor_enabled[i] = false;
            _test_order[i] = 0;
        }
    }
};
static_assert(sizeof(Probe) == sizeof(AP_MotorsMatrix), "probe must not change layout");

struct motor_def { int8_t num; float angle; float yaw; uint8_t order; };

struct frame {
    const char *name;
    uint8_t count;
    struct motor_def motors[8];
};

// Standard layouts. These are the angles upstream's frame tables contain.
static const struct frame frames[] = {
    { "quad_x", 4, {
        {0,   45.0f,  1.0f, 1}, {1, -135.0f,  1.0f, 3},
        {2,  -45.0f, -1.0f, 4}, {3,  135.0f, -1.0f, 2} } },
    { "quad_plus", 4, {
        {0,   90.0f,  1.0f, 2}, {1,  -90.0f,  1.0f, 4},
        {2,    0.0f, -1.0f, 1}, {3,  180.0f, -1.0f, 3} } },
    { "hexa_x", 6, {
        {0,   90.0f,  1.0f, 2}, {1, -90.0f, -1.0f, 5},
        {2,  -30.0f,  1.0f, 6}, {3, 150.0f, -1.0f, 3},
        {4,   30.0f, -1.0f, 1}, {5, -150.0f, 1.0f, 4} } },
    { "hexa_plus", 6, {
        {0,    0.0f,  1.0f, 1}, {1, 180.0f, -1.0f, 4},
        {2, -120.0f, -1.0f, 5}, {3,  60.0f,  1.0f, 2},
        {4,  -60.0f,  1.0f, 6}, {5, 120.0f, -1.0f, 3} } },
    { "octa_x", 8, {
        {0,   22.5f,  1.0f, 1}, {1, -157.5f, 1.0f, 5},
        {2,   67.5f, -1.0f, 2}, {3,  157.5f,-1.0f, 4},
        {4,  112.5f,  1.0f, 3}, {5,  -22.5f,-1.0f, 8},
        {6,  -67.5f,  1.0f, 7}, {7, -112.5f,-1.0f, 6} } },
    { "tri", 3, {
        {0,   60.0f,  1.0f, 1}, {1, -60.0f,  1.0f, 3},
        {2,  180.0f,  0.0f, 2} } },
};

// One instance: AP_MotorsMatrix enforces a singleton. Static, so its
// AP_Param members and initialised_ok() flag start zeroed rather than holding
// whatever was on the stack.
static Probe motors;

int main(void)
{
    printf("#motors\n");
    printf("frame,motor,stage,roll,pitch,yaw,throttle,enabled,order\n");

    for (unsigned fi = 0; fi < ARRAY_SIZE(frames); fi++) {
        const struct frame &f = frames[fi];
        Probe &m = motors;
        m.clear_motors();

        for (unsigned i = 0; i < f.count; i++) {
            m.add_motor(f.motors[i].num, f.motors[i].angle, f.motors[i].yaw, f.motors[i].order);
        }

        // raw factors, before normalisation
        for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
            printf("%s,%u,raw,%u,%u,%u,%u,%d,%u\n", f.name, i,
                   fbits(m._roll_factor[i]), fbits(m._pitch_factor[i]),
                   fbits(m._yaw_factor[i]), fbits(m._throttle_factor[i]),
                   m.motor_enabled[i] ? 1 : 0, (unsigned)m._test_order[i]);
        }

        m.normalise_rpy_factors();

        for (unsigned i = 0; i < AP_MOTORS_MAX_NUM_MOTORS; i++) {
            printf("%s,%u,norm,%u,%u,%u,%u,%d,%u\n", f.name, i,
                   fbits(m._roll_factor[i]), fbits(m._pitch_factor[i]),
                   fbits(m._yaw_factor[i]), fbits(m._throttle_factor[i]),
                   m.motor_enabled[i] ? 1 : 0, (unsigned)m._test_order[i]);
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Motors/AP_MotorsMatrix.cpp",
          )
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("frame,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
