#!/usr/bin/env python3
"""Emit ap-math's CRC lookup tables from the ones extracted from upstream.

Generated, not typed. The five distinct tables hold 1,280 constants between
them; a single wrong byte would corrupt one input in 256 and pass any spot
check. Re-run this after an upstream re-baseline and diff the result.

Where a table is derivable from a polynomial the Rust side also asserts that,
so the table is self-checking rather than merely faithfully copied. Only
crc8_table_rds02uf is not derivable -- it is a vendor table for one rangefinder
and matches no standard polynomial.
"""
import json
from pathlib import Path

FIXT = Path("/srv/ardumaster/ports/ardumaster-rust/fixtures/crc_tables.json")
OUT = Path("/srv/ardumaster/ports/ardumaster-rust/crates/ap-math/src/crc_tables.rs")

# crc_table (function-local in crc_crc16_ibm) is extracted twice by the two
# patterns in gen_crc_fixture.py; they are the same table
ALIASES = {"crc_table": "crc_table_ibm"}

DOC = {
    "crc8_table":         "CRC-8 with polynomial 0x07, MSB-first. Used by `crc_crc8`.",
    "crc8_table_maxim":   "CRC-8/MAXIM (Dallas 1-Wire), polynomial 0x31 reflected to 0x8C.",
    "crc8_table_sae":     "CRC-8/SAE-J1850, polynomial 0x1D, MSB-first.",
    "crc8_table_rds02uf": "Vendor table for the RDS02UF rangefinder. Matches no\n\
/// standard polynomial, so unlike the others it cannot be checked by\n\
/// re-derivation -- it is verified only against upstream's bytes.",
    "crc16tab":           "CRC-16/CCITT, polynomial 0x1021, MSB-first.",
    "crc_table_ibm":      "CRC-16 with polynomial 0x8005, MSB-first. Used by\n\
/// `crc_crc16_ibm`; note this is the non-reflected form, not CRC-16/ARC.",
    "crc32_tab":          "CRC-32, polynomial 0xEDB88320 (0x04C11DB7 reflected).",
}

RUST_TY = {"uint8_t": "u8", "uint16_t": "u16", "uint32_t": "u32"}
WIDTH = {"u8": 4, "u16": 6, "u32": 10}
PER_LINE = {"u8": 12, "u16": 10, "u32": 6}

tables = json.loads(FIXT.read_text())
for dup, keep in ALIASES.items():
    if dup in tables and keep in tables:
        assert tables[dup]["values"] == tables[keep]["values"], \
            "%s and %s differ -- the extraction is wrong" % (dup, keep)
        del tables[dup]

lines = [
    "//! CRC lookup tables, ported from upstream `AP_Math/crc.cpp`.",
    "//!",
    "//! GENERATED by `tools/parity/gen_crc_tables.py` -- do not edit. The tables",
    "//! hold 1,280 constants between them, and a single mistyped byte would",
    "//! corrupt one input in 256 while passing any spot check.",
    "//!",
    "//! Every table except `CRC8_TABLE_RDS02UF` is re-derived from its polynomial",
    "//! in this module's tests, so a transcription error fails the build rather",
    "//! than reaching a vehicle.",
    "",
]

for name in sorted(tables):
    ty = RUST_TY[tables[name]["type"]]
    vals = tables[name]["values"]
    lines.append("/// %s" % DOC.get(name, "Lookup table from upstream."))
    lines.append("pub const %s: [%s; %d] = [" % (name.upper(), ty, len(vals)))
    per = PER_LINE[ty]
    w = WIDTH[ty]
    for i in range(0, len(vals), per):
        chunk = ", ".join(("0x{:0%dx}" % (w - 2)).format(v) for v in vals[i:i + per])
        lines.append("    %s," % chunk)
    lines.append("];")
    lines.append("")

OUT.write_text("\n".join(lines))
print("wrote %s: %d tables" % (OUT.name, len(tables)))
for name in sorted(tables):
    print("  %-20s %s x %d" % (name.upper(), RUST_TY[tables[name]["type"]],
                               len(tables[name]["values"])))
