#!/usr/bin/env python3
"""Generate the AC_PID parity fixture from upstream's own AC_PID.

Harness-driven rather than replayed from a flight log. AC_PID is stateful --
integrator, three low-pass filters, a slew limiter -- and a scripted sequence
gives exact control over dt and the limit flag, which is what reaches the
awkward branches: integrator clamping while saturated, the reset path on the
first call, the P+D sum limit, a zero I gain clearing the integrator, and the
slew limiter engaging under oscillation. A flight log would exercise whichever
of those that flight happened to hit.

`SlewLimiter::modifier` calls `AP_HAL::millis()`, so the harness stubs the
clock and steps it explicitly. That makes the fixture deterministic and lets
the port be driven with the same timestamps -- the port takes `now_ms` as a
parameter, since ADR-0004 rules out reading a global clock.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/ardumaster-rust/fixtures/ac_pid_parity.csv")
BUILD = Path("/tmp/pid_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AC_PID/AC_PID.cpp.0.o",
    "build/sitl/libraries/Filter/SlewLimiter.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
    # SlewLimiter needs the low-pass filter, and AC_PID's notch hooks are
    # compiled in even though both pointers stay null here
    "build/sitl/libraries/Filter/LowPassFilter.cpp.0.o",
    "build/sitl/libraries/Filter/NotchFilter.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AC_PID/AC_PID.cpp.
// Generated by tools/parity/gen_pid_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AC_PID/AC_PID.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <Filter/AP_Filter.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

// The controlled clock. SlewLimiter::modifier reads AP_HAL::millis(), so the
// harness owns it and steps it explicitly; the port takes the same value as a
// parameter.
static uint32_t g_millis = 0;
namespace AP_HAL {
    uint32_t millis() { return g_millis; }
    uint64_t micros64() { return (uint64_t)g_millis * 1000ULL; }
    uint32_t micros() { return g_millis * 1000U; }
    uint64_t millis64() { return g_millis; }
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
}

void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

// Reachable only from AC_PID::set_notch_sample_rate, which this harness never
// calls -- the notch pointers stay null, which is the configuration the port
// reproduces. Aborting rather than returning keeps that assumption honest.
namespace AP {
AP_Filters &filters() { fputs("harness: unexpected AP::filters()", stderr); abort(); }
}
AP_Filter *AP_Filters::get_filter(uint8_t) { abort(); }

// AC_PID's constructor calls this to copy its default_* members into its
// AP_Float parameters. Linking the real AP_Param drags in the storage manager,
// the filesystem and the GCS -- none of which has anything to do with the PID
// arithmetic under test. It is a no-op here and the harness sets every gain
// explicitly through the public setters instead, which is exactly the shape
// the port has: gains are plain values, and binding them to storage is FW-004.
void AP_Param::setup_object_defaults(const void *, const struct AP_Param::GroupInfo *) {}

// Reached only from AC_PID::save_gains and load_gains, which persist tuning to
// EEPROM. Neither is called here, and neither has anything to do with the
// arithmetic under test. Aborting keeps that assumption honest.
void AP_Param::save(bool) { fputs("harness: unexpected AP_Param::save", stderr); abort(); }
bool AP_Param::load(void) { fputs("harness: unexpected AP_Param::load", stderr); abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

static void emit(int scenario, int step, float out, const AP_PIDInfo &pi, float integ)
{
    printf("%d,%d,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u,%d,%d,%d,%u\n",
           scenario, step, fbits(out),
           fbits(pi.target), fbits(pi.actual), fbits(pi.error),
           fbits(pi.P), fbits(pi.I), fbits(pi.D),
           fbits(pi.FF), fbits(pi.DFF),
           fbits(pi.Dmod), fbits(pi.slew_rate),
           pi.limit ? 1 : 0, pi.PD_limit ? 1 : 0, pi.reset ? 1 : 0,
           fbits(integ));
}

// A scenario is a gain set plus a driving function.
struct scenario {
    const char *name;
    float p, i, d, ff, imax, filt_T, filt_E, filt_D, srmax, srtau, dff, pdmax;
};

static const struct scenario scenarios[] = {
    // plain PID, no filtering, no limits
    {"plain",     2.0f, 0.5f, 0.1f, 0.0f, 10.0f,  0.0f,  0.0f,  0.0f, 0.0f, 1.0f, 0.0f, 0.0f},
    // with the three low-pass filters active
    {"filtered",  2.0f, 0.5f, 0.1f, 0.25f,10.0f, 20.0f, 15.0f, 10.0f, 0.0f, 1.0f, 0.0f, 0.0f},
    // integrator clamped hard, so imax binds quickly
    {"tight_imax",1.0f, 5.0f, 0.0f, 0.0f,  0.5f,  0.0f,  0.0f,  0.0f, 0.0f, 1.0f, 0.0f, 0.0f},
    // zero I gain: upstream clears the integrator outright
    {"no_i",      2.0f, 0.0f, 0.1f, 0.0f, 10.0f,  0.0f,  0.0f,  0.0f, 0.0f, 1.0f, 0.0f, 0.0f},
    // P+D sum limit binding
    {"pdmax",     5.0f, 0.1f, 0.5f, 0.0f, 10.0f,  0.0f,  0.0f,  0.0f, 0.0f, 1.0f, 0.0f, 1.0f},
    // slew limiter active
    {"slew",      4.0f, 0.2f, 0.3f, 0.0f, 10.0f,  0.0f,  0.0f, 20.0f, 5.0f, 1.0f, 0.0f, 0.0f},
    // derivative feed-forward
    {"dff",       1.0f, 0.1f, 0.0f, 0.5f, 10.0f, 10.0f, 10.0f, 10.0f, 0.0f, 1.0f, 0.7f, 0.0f},
};
static const int nscen = sizeof(scenarios)/sizeof(scenarios[0]);

// AC_PID must have STATIC storage duration here. Its notch-filter members
//     NotchFilterFloat* _target_notch;
//     NotchFilterFloat* _error_notch;
// are declared with no initialiser and the constructor never assigns them, so
// they are only null because every AC_PID in ArduPilot lives in static storage
// and is zero-initialised before its constructor runs. A stack-allocated
// AC_PID has garbage there, `_target_notch != nullptr` is true, and update_all
// filters through a wild pointer -- which is exactly what the first version of
// this harness did, producing plausible-looking but meaningless numbers.
static AC_PID pid0(0,0,0,0,0,0,0,0);
static AC_PID pid1(0,0,0,0,0,0,0,0);
static AC_PID pid2(0,0,0,0,0,0,0,0);
static AC_PID pid3(0,0,0,0,0,0,0,0);
static AC_PID pid4(0,0,0,0,0,0,0,0);
static AC_PID pid5(0,0,0,0,0,0,0,0);
static AC_PID pid6(0,0,0,0,0,0,0,0);
static AC_PID *pids[nscen] = { &pid0, &pid1, &pid2, &pid3, &pid4, &pid5, &pid6 };

int main(void)
{
    printf("#pid\n");
    printf("scenario,step,out,target,actual,error,P,I,D,FF,DFF,Dmod,srate,limit,pdlimit,reset,integrator\n");

    for (int s = 0; s < nscen; s++) {
        const struct scenario &sc = scenarios[s];
        AC_PID &pid = *pids[s];
        // the parameter machinery is stubbed out, so set every gain here
        pid.set_kP(sc.p);
        pid.set_kI(sc.i);
        pid.set_kD(sc.d);
        pid.set_ff(sc.ff);
        pid.set_imax(sc.imax);
        pid.set_pdmax(sc.pdmax);
        pid.filt_T_hz().set(sc.filt_T);
        pid.filt_E_hz().set(sc.filt_E);
        pid.filt_D_hz().set(sc.filt_D);
        pid.slew_limit().set(sc.srmax);
        pid.kDff().set(sc.dff);
        pid.reset_filter();

        g_millis = 0;
        const float dt = 0.02f;

        for (int step = 0; step < 120; step++) {
            g_millis = (uint32_t)(step * 20);

            // a step demand, then a reversal, then an oscillation -- so the
            // integrator winds up, unwinds, and the slew limiter has something
            // to bite on
            float target;
            if (step < 30) {
                target = 10.0f;
            } else if (step < 60) {
                target = -10.0f;
            } else {
                target = (step % 2 == 0) ? 20.0f : -20.0f;
            }

            // the measurement lags the target, and the output is reported as
            // limited for a stretch in the middle so wind-up protection runs
            const float measurement = target * 0.25f;
            const bool limit = (step >= 40 && step < 50);

            const float out = pid.update_all(target, measurement, dt, limit);
            emit(s, step, out, pid.get_pid_info(), pid.get_i());
        }

        // an explicit reset partway, to cover the reset path outside step 0
        pid.reset_filter();
        g_millis += 20;
        const float out = pid.update_all(5.0f, 1.0f, dt, false);
        emit(s, 200, out, pid.get_pid_info(), pid.get_i());

        // a zero dt, which must not divide
        g_millis += 20;
        const float out0 = pid.update_all(5.0f, 1.0f, 0.0f, false);
        emit(s, 201, out0, pid.get_pid_info(), pid.get_i());
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AC_PID/AC_PID.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("scenario"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
