#!/usr/bin/env python3
"""Generate the NotchFilter parity fixture from upstream's own filter.

Harness-driven. The interesting paths are all configuration- and
sequence-dependent: the five-percent slew limit on retuning, the unchanged-
configuration early return, a rejected configuration keeping its cached centre
while disabling the filter, Q coming out zero for a bandwidth that reaches down
through zero, the deferred reset, and the ringing transient a notch shows when
brought into service without one.

Inputs are emitted alongside outputs so the port replays the same sequence.
Coefficients are emitted too, through a probe subclass reaching the protected
members -- comparing only outputs would let a wrong coefficient hide behind a
compensating state error.

The filters MUST be static. NotchFilter is declared with NO CONSTRUCTOR AT ALL,
so every member of a non-static instance is indeterminate: both flags, all five
coefficients, all four state vectors and the three cached frequencies. Static
storage zero-initialises them, which is what a real vehicle gets and what the
port reproduces. See D-005.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/ardumaster-rust")
OUT = ROOT / "fixtures/notch_parity.csv"
COEFFS_OUT = ROOT / "fixtures/notch_coeffs.csv"
BUILD = Path("/tmp/notch_parity/harness")

OBJECTS = [
    "build/sitl/libraries/Filter/NotchFilter.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for Filter/NotchFilter.cpp.
// Generated by tools/parity/gen_notch_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <Filter/NotchFilter.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { abort(); }
    uint64_t micros64() { abort(); }
    uint32_t micros() { abort(); }
    uint64_t millis64() { abort(); }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// The coefficients and flags are protected. Reaching them through a subclass
// is the only way to compare them directly rather than inferring them.
template <class T>
class Probe : public NotchFilter<T> {
public:
    float pb0() const { return this->b0; }
    float pb1() const { return this->b1; }
    float pb2() const { return this->b2; }
    float pa1() const { return this->a1; }
    float pa2() const { return this->a2; }
    bool  pinit() const { return this->initialised; }
};

enum action {
    ACT_NONE = 0,
    ACT_RESET_AT_START,   // the way upstream brings a notch into service
    ACT_RESET_MIDWAY,
    ACT_RETUNE_FAR_UP,    // asks for a jump the slew limit must refuse
    ACT_RETUNE_FAR_DOWN,
    ACT_RETUNE_SAME,      // hits the unchanged-configuration early return
    ACT_RETUNE_REJECTED,  // above half the sample rate: disables, keeps centre
    ACT_DISABLE,
};

struct scenario {
    const char *name;
    float sample_freq;
    float center_freq;
    float bandwidth;
    float attenuation_db;
    enum action act;
    float act_arg;
};

static const struct scenario scenarios[] = {
    {"plain",          1000.0f, 100.0f,  40.0f, 30.0f, ACT_NONE,           0.0f},
    {"serviced",       1000.0f, 100.0f,  40.0f, 30.0f, ACT_RESET_AT_START, 0.0f},
    {"ins_rate",       8000.0f, 188.0f,  60.0f, 30.0f, ACT_RESET_AT_START, 0.0f},
    {"narrow",         1000.0f, 100.0f,  10.0f, 40.0f, ACT_RESET_AT_START, 0.0f},
    {"wide",           1000.0f, 200.0f, 150.0f, 20.0f, ACT_RESET_AT_START, 0.0f},
    // Q comes out zero: bandwidth reaches down through zero
    {"degenerate",     1000.0f,  20.0f,  40.0f, 30.0f, ACT_NONE,           0.0f},
    // centre above half the sample rate: init refuses outright
    {"too_high",       1000.0f, 600.0f,  40.0f, 30.0f, ACT_NONE,           0.0f},
    // slew limiting
    {"slew_up",        1000.0f, 100.0f,  40.0f, 30.0f, ACT_RETUNE_FAR_UP,  400.0f},
    {"slew_down",      1000.0f, 100.0f,  40.0f, 30.0f, ACT_RETUNE_FAR_DOWN,  1.0f},
    {"retune_same",    1000.0f, 100.0f,  40.0f, 30.0f, ACT_RETUNE_SAME,    0.0f},
    {"retune_bad",     1000.0f, 100.0f,  40.0f, 30.0f, ACT_RETUNE_REJECTED, 900.0f},
    {"reset_midway",   1000.0f, 100.0f,  40.0f, 30.0f, ACT_RESET_MIDWAY,   0.0f},
    {"disabled",       1000.0f, 100.0f,  40.0f, 30.0f, ACT_DISABLE,        0.0f},
};
static const int nscen = sizeof(scenarios)/sizeof(scenarios[0]);

// MUST be static -- see the generator's docstring.
static Probe<float>    nf[nscen];
static Probe<Vector3f> nv[nscen];

// A drive with energy at the notch centre and away from it, plus a step and an
// impulse, so both the stopband and the passband are exercised.
static float drive(int step)
{
    const float t = (float)step / 1000.0f;
    float v = 0.6f * sinf(2.0f * (float)M_PI * 100.0f * t);   // at the notch
    v += 0.4f * sinf(2.0f * (float)M_PI * 15.0f * t);         // well below
    if (step >= 20) v += 1.0f;                                // step
    if (step == 70) v += 5.0f;                                // impulse
    return v;
}

int main(void)
{
    FILE *cf = fopen("COEFFS_PATH", "w");
    if (!cf) { perror("coeffs"); abort(); }
    fprintf(cf, "#notch_coeffs\n");
    fprintf(cf, "scenario,initialised,center_freq,sample_freq,b0,b1,b2,a1,a2\n");

    printf("#notch\n");
    printf("scenario,step,in,out_f,out_x,out_y,out_z\n");

    for (int s = 0; s < nscen; s++) {
        const struct scenario &sc = scenarios[s];
        Probe<float>    &ff = nf[s];
        Probe<Vector3f> &fv = nv[s];

        ff.init(sc.sample_freq, sc.center_freq, sc.bandwidth, sc.attenuation_db);
        fv.init(sc.sample_freq, sc.center_freq, sc.bandwidth, sc.attenuation_db);

        if (sc.act == ACT_RESET_AT_START) { ff.reset(); fv.reset(); }

        float A, Q;
        NotchFilter<float>::calculate_A_and_Q(sc.center_freq, sc.bandwidth,
                                              sc.attenuation_db, A, Q);

        for (int step = 0; step < 120; step++) {
            if (step == 50) {
                switch (sc.act) {
                case ACT_RESET_MIDWAY:
                    ff.reset(); fv.reset();
                    break;
                case ACT_RETUNE_FAR_UP:
                case ACT_RETUNE_FAR_DOWN:
                case ACT_RETUNE_REJECTED:
                    ff.init_with_A_and_Q(sc.sample_freq, sc.act_arg, A, Q);
                    fv.init_with_A_and_Q(sc.sample_freq, sc.act_arg, A, Q);
                    break;
                case ACT_RETUNE_SAME:
                    ff.init_with_A_and_Q(sc.sample_freq, sc.center_freq, A, Q);
                    fv.init_with_A_and_Q(sc.sample_freq, sc.center_freq, A, Q);
                    break;
                case ACT_DISABLE:
                    ff.disable(); fv.disable();
                    break;
                default:
                    break;
                }
            }

            const float in = drive(step);
            const float of = ff.apply(in);
            const Vector3f ov = fv.apply(Vector3f(in, 2.0f*in, -in));

            printf("%s,%d,%u,%u,%u,%u,%u\n", sc.name, step,
                   fbits(in), fbits(of), fbits(ov.x), fbits(ov.y), fbits(ov.z));
        }

        fprintf(cf, "%s,%d,%u,%u,%u,%u,%u,%u,%u\n", sc.name, ff.pinit() ? 1 : 0,
                fbits(ff.center_freq_hz()), fbits(ff.sample_freq_hz()),
                fbits(ff.pb0()), fbits(ff.pb1()), fbits(ff.pb2()),
                fbits(ff.pa1()), fbits(ff.pa2()));
    }
    fclose(cf);
    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    src = HARNESS.replace("COEFFS_PATH", str(COEFFS_OUT))
    build(src, OBJECTS, BUILD, "Filter/NotchFilter.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("scenario"))
    print("wrote %s: %d rows" % (OUT.name, rows))
    print("wrote %s" % COEFFS_OUT.name)


if __name__ == "__main__":
    main()
