#!/usr/bin/env python3
"""Generate the AP_Common parity fixture from upstream's own helpers.

Three things worth comparing against upstream rather than reasoning about:

  float16 — every one of the 65,536 bit patterns through get(), and a sweep of
  floats through set(). An exhaustive sweep is cheap here and it is the only
  way to be sure about subnormals, the infinity boundary and the NaN
  canonicalisation, which are exactly where a hand-transcribed bit-twiddling
  routine goes wrong.

  ap_mktime — dates across the epoch, leap years, the century rule and the
  end-of-month boundaries.

  the byte helpers — hex_to_uint8 and char_to_hex over all 256 input bytes,
  and is_bounded_int32 over a grid that includes reversed ranges.

strncpy_noterm is not here: it writes through a pointer with a length the
caller owns, so the interesting cases are about buffer sizing rather than
arithmetic, and the port's own tests cover them. Adding it would mean the
harness inventing buffer layouts, which proves nothing about upstream.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/common_parity.csv"
BUILD = Path("/tmp/common_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Common/AP_Common.cpp.0.o",
    "build/sitl/libraries/AP_Common/time.cpp.0.o",
    "build/sitl/libraries/AP_Common/float16.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Common.
// Generated by tools/parity/gen_common_fixture.py -- do not edit by hand.
#include <AP_Common/AP_Common.h>
#include <AP_Common/time.h>
#include <AP_Common/float16.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

int main(void)
{
    printf("#common\n");
    printf("kind,a,b,c,out\n");

    // --- every half-precision bit pattern through get() ---
    for (uint32_t p = 0; p < 65536; p++) {
        Float16_t h;
        h.v16 = (uint16_t)p;
        printf("f16_get,%u,0,0,%u\n", p, fbits(h.get()));
    }

    // --- a sweep of floats through set() ---
    // powers of two either side of the representable range, the subnormal
    // boundary, the rounding boundary, and a spread of ordinary values
    static const float inputs[] = {
        0.0f, -0.0f, 1.0f, -1.0f, 0.5f, -0.5f, 0.25f, 2.0f, 3.0f,
        1.0f/3.0f, 0.1f, -0.1f, 65504.0f, -65504.0f, 65505.0f, 65536.0f,
        1.0e6f, -1.0e6f, 6.103515625e-5f, 5.960464477539063e-8f,
        1.0e-8f, -1.0e-8f, 1.0e-45f, 123.456f, -987.654f, 1024.0f,
        2048.5f, 0.000030517578125f, 1e30f, -1e30f,
    };
    for (unsigned i = 0; i < ARRAY_SIZE(inputs); i++) {
        Float16_t h;
        h.set(inputs[i]);
        printf("f16_set,%u,0,0,%u\n", fbits(inputs[i]), (unsigned)h.v16);
    }
    // infinities and NaN separately, since they are not constant-expressible
    {
        Float16_t h;
        const float inf = 1.0f/0.0f;
        h.set(inf);   printf("f16_set,%u,0,0,%u\n", fbits(inf), (unsigned)h.v16);
        h.set(-inf);  printf("f16_set,%u,0,0,%u\n", fbits(-inf), (unsigned)h.v16);
        const float nan = inf - inf;
        h.set(nan);   printf("f16_set,%u,0,0,%u\n", fbits(nan), (unsigned)h.v16);
    }

    // --- byte helpers over every input ---
    for (uint32_t a = 0; a < 256; a++) {
        uint8_t res = 0;
        const bool ok = hex_to_uint8((uint8_t)a, res);
        printf("hex_to_uint8,%u,0,0,%d\n", a, ok ? (int)res : -1);
        printf("char_to_hex,%u,0,0,%u\n", a, (unsigned)char_to_hex((char)a));
    }

    // --- bounds, including reversed ranges ---
    static const int32_t vals[] = {-2147483648, -100, -1, 0, 1, 5, 10, 100, 2147483647};
    for (unsigned i = 0; i < ARRAY_SIZE(vals); i++) {
        for (unsigned j = 0; j < ARRAY_SIZE(vals); j++) {
            for (unsigned k = 0; k < ARRAY_SIZE(vals); k++) {
                printf("bounded,%d,%d,%d,%d\n", (int)vals[i], (int)vals[j], (int)vals[k],
                       is_bounded_int32(vals[i], vals[j], vals[k]) ? 1 : 0);
            }
        }
    }

    // --- ap_mktime over dates that matter ---
    static const struct { int year, mon, mday, hour, min, sec; } dates[] = {
        {  70,  0,  1,  0,  0,  0 },   // the epoch
        {  69, 11, 31, 23, 59, 59 },   // before it: must fail
        {  70,  0,  1,  0,  0,  1 },
        {  71,  0,  1,  0,  0,  0 },
        {  72,  1, 28, 12,  0,  0 },   // 1972, a leap year
        {  72,  1, 29, 12,  0,  0 },
        {  72,  2,  1,  0,  0,  0 },
        { 100,  0,  1,  0,  0,  0 },   // 2000
        { 100,  1, 28, 23, 59, 59 },   // the century leap rule
        { 100,  1, 29,  0,  0,  0 },
        { 100,  2,  1,  0,  0,  0 },
        { 124,  1, 29, 12, 34, 56 },   // 2024 leap day
        { 125,  6,  4, 15, 30,  0 },
        { 130, 11, 31, 23, 59, 59 },
        { 200,  1, 28, 12,  0,  0 },   // 2100, NOT a leap year
        { 200,  2,  1, 12,  0,  0 },
        { 138,  0, 19,  3, 14,  7 },   // the 32-bit time_t rollover
        { 206,  0,  1,  0,  0,  0 },   // 2106: the last year the 32-bit
        { 207,  0,  1,  0,  0,  0 },   // intermediate survives, and the first
        { 250,  0,  1,  0,  0,  0 },   // it does not -- see D-022
    };
    for (unsigned i = 0; i < ARRAY_SIZE(dates); i++) {
        struct tm t;
        memset(&t, 0, sizeof(t));
        t.tm_year = dates[i].year;
        t.tm_mon  = dates[i].mon;
        t.tm_mday = dates[i].mday;
        t.tm_hour = dates[i].hour;
        t.tm_min  = dates[i].min;
        t.tm_sec  = dates[i].sec;
        printf("mktime,%d,%d,%d,%lld\n", dates[i].year, dates[i].mon, dates[i].mday,
               (long long)ap_mktime(&t));
        // the time-of-day fields go in a companion row so the port can rebuild
        // exactly the same struct
        printf("mktime_tod,%d,%d,%d,0\n", dates[i].hour, dates[i].min, dates[i].sec);
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Common/AP_Common.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("kind"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
