#!/usr/bin/env python3
"""Generate the Rust world-magnetic-model tables from upstream's tables.cpp.

The tables are 19x37 floats each, three of them, and upstream's own file says
"auto-generated from the IGRF tables. Do not edit". Retyping 2,109 numbers by
hand would be absurd and unverifiable; this parses them out and emits Rust,
so the port's tables are the same numbers by construction.

Emitted as f32 hex bit patterns rather than decimal literals. The decimals in
tables.cpp are what Python read; writing them back as decimals would round-trip
through two more parsers, and a single ulp of drift in a table this size would
be invisible and permanent.
"""
import re
import struct
from pathlib import Path

SRC = Path("/srv/ardumaster/upstream/plane-4.7.0/libraries/AP_Declination/tables.cpp")
OUT = Path("/srv/ardumaster/ports/ardumaster-rust/crates/ap-declination/src/tables.rs")

text = SRC.read_text()

LAT, LON = 19, 37


def parse_table(name):
    """Pull one [LAT][LON] table out of the C++ source."""
    start = text.index("%s[LAT_TABLE_SIZE][LON_TABLE_SIZE] = {" % name)
    end = text.index("};", start)
    body = text[start:end]
    rows = re.findall(r"\{([^{}]*)\}", body)
    assert len(rows) == LAT, "%s: got %d rows, expected %d" % (name, len(rows), LAT)
    out = []
    for r in rows:
        vals = [v.strip().rstrip("f") for v in r.split(",") if v.strip()]
        assert len(vals) == LON, "%s: got %d columns, expected %d" % (name, len(vals), LON)
        out.append([float(v) for v in vals])
    return out


def bits(x):
    """The f32 bit pattern for a value, so nothing is lost in a decimal round trip."""
    return struct.unpack("<I", struct.pack("<f", x))[0]


tables = {n: parse_table(n) for n in ("declination_table", "inclination_table", "intensity_table")}

# Sanity: the tables are not all the same and not empty.
assert tables["declination_table"][0][0] != tables["inclination_table"][0][0]

lines = [
    "//! World magnetic model tables, upstream `AP_Declination/tables.cpp`.",
    "//!",
    "//! GENERATED by `tools/parity/gen_declination_tables.py` from upstream's own",
    "//! `tables.cpp`, which is itself generated from the IGRF model. Do not edit.",
    "//!",
    "//! Values are `f32::from_bits` of the exact patterns upstream compiles, not",
    "//! decimal literals — a table this size could drift by an ulp through a",
    "//! decimal round trip and nobody would ever see it.",
    "",
    "/// Latitude rows in each table.",
    "pub const LAT_TABLE_SIZE: usize = %d;" % LAT,
    "",
    "/// Longitude columns in each table.",
    "pub const LON_TABLE_SIZE: usize = %d;" % LON,
    "",
    "/// Degrees between samples, upstream `SAMPLING_RES`.",
    "pub const SAMPLING_RES: f32 = 10.0;",
    "",
    "/// Southern edge of the table, degrees.",
    "pub const SAMPLING_MIN_LAT: f32 = -90.0;",
    "",
    "/// Northern edge of the table, degrees.",
    "pub const SAMPLING_MAX_LAT: f32 = 90.0;",
    "",
    "/// Western edge of the table, degrees.",
    "pub const SAMPLING_MIN_LON: f32 = -180.0;",
    "",
    "/// Eastern edge of the table, degrees.",
    "pub const SAMPLING_MAX_LON: f32 = 180.0;",
    "",
]

DOC = {
    "declination_table": "Magnetic declination, degrees east of true north.",
    "inclination_table": "Magnetic inclination (dip), degrees below horizontal.",
    "intensity_table": "Field intensity, gauss.",
}

for name, tbl in tables.items():
    rust_name = name.upper()
    lines.append("/// %s" % DOC[name])
    lines.append(
        "pub static %s: [[u32; LON_TABLE_SIZE]; LAT_TABLE_SIZE] = ["
        % rust_name
    )
    for row in tbl:
        cells = ", ".join("0x%08X" % bits(v) for v in row)
        lines.append("    [%s]," % cells)
    lines.append("];")
    lines.append("")

lines.append("/// One entry of a table, decoded.")
lines.append("#[must_use]")
lines.append("pub fn cell(table: &[[u32; LON_TABLE_SIZE]; LAT_TABLE_SIZE], lat: usize, lon: usize) -> f32 {")
lines.append("    match table.get(lat).and_then(|row| row.get(lon)) {")
lines.append("        Some(&b) => f32::from_bits(b),")
lines.append("        None => 0.0,")
lines.append("    }")
lines.append("}")
lines.append("")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines))
print("wrote %s: 3 tables of %dx%d" % (OUT, LAT, LON))
