#!/usr/bin/env python3
"""Generate the AP_GPS time-conversion parity fixture.

Two things are compared, and they are reached differently.

  BCD_to_gps_time is a static member of AP_GPS_Backend, so it is called
  directly out of the linked GPS_Backend.cpp object. It carries the whole
  chain: BCD field extraction, ap_mktime underneath, the leap-second and epoch
  offsets, and the narrowing to uint32.

  istate_time_to_epoch_ms lives in AP_GPS.cpp, which references most of the
  vehicle. Linking it to reach a three-term addition would be absurd, so the
  harness recomputes that expression from upstream's OWN MACROS -- included
  from AP_GPS.h, not retyped. The only thing that could differ between the port
  and upstream here is the value of UNIX_OFFSET_MSEC and AP_MSEC_PER_WEEK, and
  that is exactly what this pins.

fill_3d_velocity is an instance method reading `state`, so it is not here. It
is `speed * cosf(radians(course))` and the transcendentals it uses are already
covered by D-017; the port's own tests check the four cardinal directions and
that the magnitude is preserved.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/gps_time_parity.csv"
BUILD = Path("/tmp/gps_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_GPS/GPS_Backend.cpp.0.o",
    "build/sitl/libraries/AP_Common/time.cpp.0.o",
    "build/sitl/libraries/AP_Common/AP_Common.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_GPS time conversion.
// Generated by tools/parity/gen_gps_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_GPS/AP_GPS.h>
#include <AP_GPS/GPS_Backend.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <GCS_MAVLink/GCS.h>
#include <AP_Logger/AP_Logger.h>
#include <AP_AHRS/AP_AHRS.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

// GPS_Backend.cpp carries the whole backend, so the object references the
// logger, the GCS, the AHRS and the frontend's lag and rate accessors. None of
// them is on the path to BCD_to_gps_time, which is a static function over its
// arguments. Aborting rather than returning keeps that claim honest: if any of
// these were reached the process would die instead of producing a plausible
// wrong answer.
GCS &gcs() { fputs("harness: unexpected gcs()\n", stderr); abort(); }
namespace AP {
AP_Logger &logger() { fputs("harness: unexpected logger()\n", stderr); abort(); }
AP_AHRS &ahrs() { fputs("harness: unexpected ahrs()\n", stderr); abort(); }
}
void AP_Logger::Write_Message(const char *)
{
    fputs("harness: unexpected Write_Message\n", stderr);
    abort();
}
void AP_Logger::WriteStreaming(const char *, const char *, const char *,
                               const char *, const char *, ...)
{
    fputs("harness: unexpected WriteStreaming\n", stderr);
    abort();
}
bool AP_GPS::get_lag(uint8_t, float &) const
{
    fputs("harness: unexpected get_lag\n", stderr);
    abort();
}
uint16_t AP_GPS::get_rate_ms(uint8_t) const
{
    fputs("harness: unexpected get_rate_ms\n", stderr);
    abort();
}
bool AP_GPS::should_log() const
{
    fputs("harness: unexpected should_log\n", stderr);
    abort();
}
int AP_HAL::Util::snprintf(char *, size_t, const char *, ...)
{
    fputs("harness: unexpected snprintf\n", stderr);
    abort();
}

int main(void)
{
    printf("#gps_time\n");
    printf("kind,a,b,c,d\n");

    // The constants themselves, straight out of upstream's macros.
    printf("consts,%llu,%llu,%llu,%llu\n",
           (unsigned long long)UNIX_OFFSET_MSEC,
           (unsigned long long)AP_MSEC_PER_WEEK,
           (unsigned long long)AP_SEC_PER_WEEK,
           (unsigned long long)GPS_LEAPSECONDS_MILLIS);

    // istate_time_to_epoch_ms, recomputed from upstream's own macros.
    static const struct { unsigned week; unsigned ms; } wk[] = {
        {0, 0}, {0, 1}, {1, 0}, {1000, 0}, {1000, 604799999},
        {2000, 12345}, {2300, 86400000}, {2380, 302400000},
        {32767, 0}, {65535, 0}, {65535, 604799999},
    };
    for (unsigned i = 0; i < ARRAY_SIZE(wk); i++) {
        const uint64_t v = UNIX_OFFSET_MSEC
                         + (uint64_t)(uint16_t)wk[i].week * AP_MSEC_PER_WEEK
                         + wk[i].ms;
        printf("epoch_ms,%u,%u,%llu,0\n", wk[i].week, wk[i].ms, (unsigned long long)v);
    }

    // BCD_to_gps_time across dates that matter: month ends, leap days, the
    // century boundary, midnight and the last millisecond of a day.
    static const struct { uint32_t date; uint32_t time_ms; } bcd[] = {
        { 60180,         0 },          // 2080-01-06 -- the two-digit year is ALWAYS 2000+YY, so 1980 is unreachable
        { 10100,         0 },          // 2000-01-01 midnight
        { 10100, 235959999 },          // and its last millisecond
        { 290224, 123456789 },         // 2024-02-29, a leap day
        { 280224, 123456789 },         // the day before it
        { 10324,         0 },          // 2024-03-01
        { 280225, 120000000 },         // 2025-02-28, not a leap year
        { 10325,         0 },          // 2025-03-01
        { 311225, 235959000 },         // year end
        { 10126,         1 },          // and the next day
        { 150625,  73015500 },
        { 10100,  86399999 },
        { 280200, 235959999 },         // 2000-02-28
        { 290200,         0 },         // 2000-02-29 -- 2000 IS a leap year
        { 10399,         0 },          // 2099, the last year the two-digit
        { 311299, 235959999 },         // form can express
    };
    for (unsigned i = 0; i < ARRAY_SIZE(bcd); i++) {
        uint16_t week = 0;
        uint32_t tow = 0;
        AP_GPS_Backend::BCD_to_gps_time(bcd[i].date, bcd[i].time_ms, week, tow);
        printf("bcd,%u,%u,%u,%u\n", bcd[i].date, bcd[i].time_ms, (unsigned)week, tow);
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    # GPS_Backend.cpp is one translation unit of a backend that references the
    # logger, the GCS, the MAVLink send path, the HAL singleton and jitter
    # correction. None is on the path to BCD_to_gps_time, which is a static
    # function over its arguments. Leaving them unresolved is the documented
    # use of this flag: a call to one would fault immediately rather than
    # return a wrong answer, and the fixture carries the GPS epoch itself as a
    # row so a harness producing nonsense is visible at a glance.
    build(HARNESS, OBJECTS, BUILD, "AP_GPS/GPS_Backend.cpp",
          link_flags=("-Wl,--unresolved-symbols=ignore-all",))
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("kind"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
