#!/usr/bin/env python3
"""Generate the location parity fixture from upstream's AP_Math/location.cpp.

The integer latitude and longitude probes deliberately straddle the bound in
single-float steps. Upstream compares `labs(lat) <= 90*1e7` where the bound is
a float (D-015), and at 9e8 the gap between representable floats is 64 -- so
values just past 90 degrees may round onto the bound and be accepted. This
fixture records what upstream actually does rather than leaving that as
analysis.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

OUT = Path("/srv/ardumaster/ports/plane-fw-rust/fixtures/location_parity.csv")
BUILD = Path("/tmp/loc_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/location.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/location.cpp.
// Generated by tools/parity/gen_location_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Math/location.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_HAL::panic(const char *m, ...) { fputs(m, stderr); abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

int main(void)
{
    printf("#bearing\n");
    printf("ox,oy,dx,dy,rad,cd,dist\n");
    {
        static const float pts[][4] = {
            {0,0,  1,0},  {0,0,  0,1},  {0,0, -1,0},  {0,0,  0,-1},
            {0,0,  1,1},  {0,0, -1,1},  {0,0, -1,-1}, {0,0,  1,-1},
            {3,4,  3,4},  {-7.5f,2.25f, 11.125f,-6.0f},
            {1e6f,1e6f, -1e6f,-1e6f},  {0,0, 1e-8f,1e-8f},
        };
        const int n = sizeof(pts)/sizeof(pts[0]);
        for (int i = 0; i < n; i++) {
            const Vector2f o(pts[i][0], pts[i][1]);
            const Vector2f d(pts[i][2], pts[i][3]);
            printf("%u,%u,%u,%u,%u,%u,%u\n",
                   fbits(o.x), fbits(o.y), fbits(d.x), fbits(d.y),
                   fbits(get_bearing_rad(o, d)),
                   fbits(get_bearing_cd(o, d)),
                   fbits(get_horizontal_distance(o, d)));
        }
    }

    printf("#checkdeg\n");
    printf("val,lat,lng\n");
    {
        static const float vals[] = {
            0.0f, 45.0f, -45.0f, 89.9f, 90.0f, 90.1f, -90.0f, -90.1f,
            179.9f, 180.0f, 180.1f, -180.0f, -180.1f, 1e9f, -1e9f,
        };
        const int n = sizeof(vals)/sizeof(vals[0]);
        for (int i = 0; i < n; i++) {
            printf("%u,%d,%d\n", fbits(vals[i]),
                   check_lat(vals[i]) ? 1 : 0, check_lng(vals[i]) ? 1 : 0);
        }
    }

    printf("#checkint\n");
    printf("val,lat,lng\n");
    {
        // straddling the bounds in single units and in float-spacing steps:
        // at 9e8 the gap between representable floats is 64
        static const int32_t vals[] = {
            0, 450000000, -450000000,
            899999999, 900000000, 900000001, 900000002, 900000032, 900000033,
            900000064, 900000065,
            -900000000, -900000001, -900000032, -900000064,
            1799999999, 1800000000, 1800000001, 1800000064, 1800000128,
            -1800000000, -1800000001, -1800000128,
            2147483647, -2147483648,
        };
        const int n = sizeof(vals)/sizeof(vals[0]);
        for (int i = 0; i < n; i++) {
            printf("%d,%d,%d\n", vals[i],
                   check_lat(vals[i]) ? 1 : 0, check_lng(vals[i]) ? 1 : 0);
        }
    }

    printf("#cdconv\n");
    printf("in,cd_to_rad,rad_to_cd\n");
    {
        static const float vals[] = {
            0.0f, 1.0f, -1.0f, 100.0f, 4500.0f, 18000.0f, -18000.0f,
            36000.0f, 0.5f, 1e-6f, 1e6f,
        };
        const int n = sizeof(vals)/sizeof(vals[0]);
        for (int i = 0; i < n; i++) {
            printf("%u,%u,%u\n", fbits(vals[i]),
                   fbits(cd_to_rad(vals[i])), fbits(rad_to_cd(vals[i])));
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/location.cpp")
    text = run(BUILD)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)

    counts, section = {}, None
    for line in text.splitlines():
        if line.startswith("#"):
            section = line[1:]
            counts[section] = -1
        elif section:
            counts[section] += 1
    print("wrote %s" % OUT.name)
    for k, v in counts.items():
        print("  %-10s %d rows" % (k, v))

    # report what upstream actually does at the latitude bound
    print()
    print("upstream check_lat at the boundary:")
    in_int = False
    for line in text.splitlines():
        if line.startswith("#"):
            in_int = line == "#checkint"
            continue
        if in_int and "," in line and not line.startswith("val"):
            v, lat, _lng = line.split(",")
            if 899999999 <= int(v) <= 900000065:
                print("  %-12s lat_ok=%s" % (v, lat))


if __name__ == "__main__":
    main()
