#!/usr/bin/env python3
"""Parity fixture for AP_Math/control.cpp's scalar shaping functions.

Grids over every branch of each function rather than a plausible trajectory:
sqrt_controller has three top-level branches and two sub-branches inside the
third, and the join between the linear and square-root regions is where a
transcription error would be least visible and most damaging.

The closed-loop functions are driven as loops too -- a thousand steps of
shape_pos_vel_accel feeding update_pos_vel_accel -- because their state
compounds and a small per-step difference would show there and nowhere else.

Only valid arguments are driven. Upstream answers a malformed limit with
INTERNAL_ERROR and an untouched output, so there is nothing numeric to compare;
the port's own tests cover that it refuses and leaves the value alone.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/control_parity.csv"
BUILD = Path("/tmp/control_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/control.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/control.cpp.
// Generated by tools/parity/gen_control_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Math/control.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}

// Aborting. Every call below passes valid limits, so this must not fire -- if
// it did, the output would be untouched and the fixture would record a value
// that came from nowhere.
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t)
{
    fputs("harness: INTERNAL_ERROR -- an argument set was not valid\n", stderr);
    abort();
}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static uint64_t dbits(double d) { uint64_t u; memcpy(&u, &d, 8); return u; }

int main(void)
{
    printf("#control\n");
    printf("kind,a,b,c,d,e,f,out1,out2\n");

    // ---- sqrt_controller: every branch, and the join between them ----
    static const float ps[]   = { 0.0f, 0.5f, 1.0f, 2.0f, 10.0f };
    static const float lims[] = { -1.0f, 0.0f, 0.5f, 2.0f, 10.0f, 100.0f };
    static const float dts[]  = { 0.0f, 0.0025f, 0.02f, 0.1f };
    for (unsigned ip = 0; ip < ARRAY_SIZE(ps); ip++) {
        for (unsigned il = 0; il < ARRAY_SIZE(lims); il++) {
            for (unsigned id = 0; id < ARRAY_SIZE(dts); id++) {
                // errors across zero, through the join, and far beyond
                for (int ie = -60; ie <= 60; ie++) {
                    const float error = (float)ie * 0.25f;
                    printf("sqrt,%u,%u,%u,%u,0,0,%u,0\n",
                           fbits(error), fbits(ps[ip]), fbits(lims[il]), fbits(dts[id]),
                           fbits(sqrt_controller(error, ps[ip], lims[il], dts[id])));
                }
            }
        }
    }

    // ---- inv_sqrt_controller and stopping_distance ----
    for (unsigned ip = 0; ip < ARRAY_SIZE(ps); ip++) {
        for (unsigned il = 0; il < ARRAY_SIZE(lims); il++) {
            for (int io = -40; io <= 40; io++) {
                const float out = (float)io * 0.5f;
                printf("inv,%u,%u,%u,0,0,0,%u,%u\n",
                       fbits(out), fbits(ps[ip]), fbits(lims[il]),
                       fbits(inv_sqrt_controller(out, ps[ip], lims[il])),
                       fbits(stopping_distance(out, ps[ip], lims[il])));
            }
        }
    }

    // ---- sqrt_controller_accel ----
    static const float rates[] = { -5.0f, -0.5f, 0.0f, 0.5f, 5.0f };
    for (unsigned ip = 0; ip < ARRAY_SIZE(ps); ip++) {
        for (unsigned il = 0; il < ARRAY_SIZE(lims); il++) {
            for (unsigned ic = 0; ic < ARRAY_SIZE(rates); ic++) {
                for (unsigned is = 0; is < ARRAY_SIZE(rates); is++) {
                    for (int ie = -8; ie <= 8; ie += 2) {
                        const float error = (float)ie * 1.5f;
                        printf("sqrt_accel,%u,%u,%u,%u,%u,0,%u,0\n",
                               fbits(error), fbits(rates[ic]), fbits(rates[is]),
                               fbits(ps[ip]), fbits(lims[il]),
                               fbits(sqrt_controller_accel(error, rates[ic], rates[is],
                                                           ps[ip], lims[il])));
                    }
                }
            }
        }
    }

    // ---- update_vel_accel: the limit logic ----
    //
    // The 0.01 velocities and the 30 accelerations are what make the clamp
    // inside the suppression branch bind. It limits the step to the
    // velocity's own magnitude, so it does nothing unless |accel * dt|
    // exceeds |vel|; with dt at 0.02 the step needs an acceleration in the
    // tens to beat even a small velocity. Without both, the branch is entered
    // and the clamp never fires.
    static const float vels[]   = { -30.0f, -2.0f, -0.5f, -0.01f, 0.0f,
                                    0.01f, 0.5f, 2.0f, 30.0f };
    static const float limits[] = { -1.0f, 0.0f, 1.0f };
    for (unsigned iv = 0; iv < ARRAY_SIZE(vels); iv++) {
        for (unsigned ia = 0; ia < ARRAY_SIZE(vels); ia++) {
            for (unsigned il = 0; il < ARRAY_SIZE(limits); il++) {
                for (unsigned ie = 0; ie < ARRAY_SIZE(limits); ie++) {
                    float vel = vels[iv];
                    update_vel_accel(vel, vels[ia], 0.02f, limits[il], limits[ie]);
                    printf("upd_vel,%u,%u,%u,%u,0,0,%u,0\n",
                           fbits(vels[iv]), fbits(vels[ia]),
                           fbits(limits[il]), fbits(limits[ie]), fbits(vel));
                }
            }
        }
    }

    // ---- update_pos_vel_accel: position suppressed independently ----
    //
    // The position step is dropped on its own two conditions while the
    // velocity follows the three-condition rule above, so a vehicle can be
    // held in place while still being allowed to slow down. A sweep that
    // moved both together could not tell the two rules apart.
    static const float perrs[] = { -1.0f, 0.0f, 1.0f };
    for (unsigned iv = 0; iv < ARRAY_SIZE(vels); iv++) {
        for (unsigned ia = 0; ia < ARRAY_SIZE(vels); ia++) {
            for (unsigned il = 0; il < ARRAY_SIZE(limits); il++) {
                for (unsigned ip = 0; ip < ARRAY_SIZE(perrs); ip++) {
                    for (unsigned ie = 0; ie < ARRAY_SIZE(limits); ie++) {
                        postype_t pos = 7.5;
                        float vel = vels[iv];
                        update_pos_vel_accel(pos, vel, vels[ia], 0.02f,
                                             limits[il], perrs[ip], limits[ie]);
                        printf("upd_pos,%u,%u,%u,%u,%u,0,%u,%.17g\n",
                               fbits(vels[iv]), fbits(vels[ia]),
                               fbits(limits[il]), fbits(perrs[ip]),
                               fbits(limits[ie]), fbits(vel), (double)pos);
                    }
                }
            }
        }
    }

    // ---- shape_accel ----
    for (int id = 0; id <= 20; id++) {
        for (int ia = -10; ia <= 10; ia += 2) {
            float accel = (float)ia * 0.5f;
            const float before = accel;
            shape_accel((float)id - 10.0f, accel, 5.0f, 0.02f);
            printf("shape_accel,%u,%u,0,0,0,0,%u,0\n",
                   fbits((float)id - 10.0f), fbits(before), fbits(accel));
        }
    }

    // ---- kinematic_limit: a sphere of directions against asymmetric limits ----
    static const struct { float xy, zneg, zpos; } klims[] = {
        { 5.0f, 2.0f, 3.0f },
        { 5.0f, 5.0f, 5.0f },
        { 0.0f, 2.0f, 3.0f },   // degenerate: returns zero
        { 10.0f, 1.0f, 8.0f },
        { 1.0f, 10.0f, 10.0f },
    };
    for (unsigned ik = 0; ik < ARRAY_SIZE(klims); ik++) {
        // sweep a hemisphere of directions, including the pure axes
        for (int iaz = 0; iaz < 8; iaz++) {
            for (int iel = -6; iel <= 6; iel++) {
                const float az = (float)iaz * (float)M_PI / 4.0f;
                const float el = (float)iel * (float)M_PI / 12.0f;
                Vector3f dir(cosf(el) * cosf(az), cosf(el) * sinf(az), sinf(el));
                printf("kin,%u,%u,%u,%u,%u,%u,%u,0\n",
                       fbits(dir.x), fbits(dir.y), fbits(dir.z),
                       fbits(klims[ik].xy), fbits(klims[ik].zneg), fbits(klims[ik].zpos),
                       fbits(kinematic_limit(dir, klims[ik].xy, klims[ik].zneg, klims[ik].zpos)));
            }
        }
        // and the zero vector
        printf("kin,%u,%u,%u,%u,%u,%u,%u,0\n",
               fbits(0.0f), fbits(0.0f), fbits(0.0f),
               fbits(klims[ik].xy), fbits(klims[ik].zneg), fbits(klims[ik].zpos),
               fbits(kinematic_limit(Vector3f(0,0,0), klims[ik].xy, klims[ik].zneg, klims[ik].zpos)));
    }

    // ---- closed loops, where the state compounds ----
    {
        float vel = 0.0f, accel = 0.0f;
        for (int i = 0; i < 500; i++) {
            shape_vel_accel(5.0f, 0.0f, vel, accel, -3.0f, 3.0f, 10.0f, 0.01f, true);
            update_vel_accel(vel, accel, 0.01f, 0.0f, 0.0f);
            printf("loop_vel,%d,0,0,0,0,0,%u,%u\n", i, fbits(vel), fbits(accel));
        }
    }
    {
        postype_t pos = 0.0; float vel = 0.0f, accel = 0.0f;
        for (int i = 0; i < 1000; i++) {
            shape_pos_vel_accel(100.0, 0.0f, 0.0f, pos, vel, accel,
                                -10.0f, 10.0f, -3.0f, 3.0f, 10.0f, 0.01f, true);
            update_pos_vel_accel(pos, vel, accel, 0.01f, 0.0f, 0.0f, 0.0f);
            printf("loop_pos,%d,0,0,0,0,0,%llu,%u\n", i,
                   (unsigned long long)dbits(pos), fbits(accel));
        }
    }
    {
        float angle = 3.0f, angle_vel = 0.0f, angle_accel = 0.0f;
        for (int i = 0; i < 500; i++) {
            shape_angle_vel_accel(-3.0f, 0.0f, 0.0f, angle, angle_vel, angle_accel,
                                  -1.0f, 1.0f, 2.0f, 5.0f, 0.01f, true);
            postype_t p = angle;
            update_pos_vel_accel(p, angle_vel, angle_accel, 0.01f, 0.0f, 0.0f, 0.0f);
            angle = (float)p;
            printf("loop_angle,%d,0,0,0,0,0,%u,%u\n", i,
                   fbits(angle), fbits(angle_accel));
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/control.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("kind,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
