#!/usr/bin/env python3
"""Parity fixture for SCurve's segment kinematics.

The three calc_javp_for_segment_* functions are the mathematical core of the
snap-limited trajectory: a raised-cosine jerk profile integrated up to
position, in closed form.

They are declared `private`. Access specifiers are not part of C++ name
mangling, so `#define private public` before the header relaxes only the
compiler's access check in this harness's view -- the object linked is the one
waf built and the vehicle runs, unchanged.

That trick is safe HERE specifically because all three are `const` and take
every piece of state as an argument: they read no members, so nothing depends
on the class layout. It is not extended to the segment-array functions, which
do touch members; those are covered by the port's own tests and their parity
comes with calculate_track in the next slice.

The grids cross every branch: the non-positive-tj early return, times inside
and beyond the segment, negative jerk references, and start states with
non-zero acceleration, velocity and position so no term can be dropped
unnoticed.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/ardumaster-rust")
OUT = ROOT / "fixtures/scurve_parity.csv"
BUILD = Path("/tmp/scurve_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/SCurve.cpp.4.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
    "build/sitl/libraries/AP_Math/control.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/SCurve.cpp segment kinematics.
// Generated by tools/parity/gen_scurve_fixture.py -- do not edit by hand.

// Access specifiers are not part of C++ name mangling, so this relaxes only
// the compiler's access check in this translation unit's view of the class.
// The object linked below is the one waf built and the vehicle runs.
//
// Safe here because every function called through it is `const` and takes all
// its state as arguments -- none reads a member, so class layout is irrelevant.
// Everything else first, so the board configuration headers load normally --
// the redefinition below must not be in scope while they are parsed.
#include <AP_Math/AP_Math.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>

#define private public
#include <AP_Math/SCurve.h>
#undef private
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

static SCurve sc;

int main(void)
{
    printf("#scurve\n");
    printf("kind,t,tj,jm,a0,v0,p0,jt,at,vt,pt\n");

    static const float tjs[] = { 0.0f, -0.1f, 0.05f, 0.25f, 0.5f, 1.0f, 2.0f };
    static const float jms[] = { -8.0f, -1.0f, 0.0f, 1.0f, 8.0f, 40.0f };
    static const struct { float a, v, p; } starts[] = {
        {  0.0f,  0.0f,  0.0f },
        {  1.0f,  0.0f,  0.0f },
        {  0.0f,  2.5f,  0.0f },
        {  0.0f,  0.0f,  7.0f },
        { -1.5f, -2.5f,  3.0f },
        {  2.0f,  5.0f, 10.0f },
    };

    for (unsigned ij = 0; ij < ARRAY_SIZE(jms); ij++) {
        for (unsigned is = 0; is < ARRAY_SIZE(starts); is++) {
            const float A0 = starts[is].a, V0 = starts[is].v, P0 = starts[is].p;

            // constant jerk: no tj involved
            for (int it = -4; it <= 40; it++) {
                const float t = (float)it * 0.05f;
                float Jt, At, Vt, Pt;
                sc.calc_javp_for_segment_const_jerk(t, jms[ij], A0, V0, P0, Jt, At, Vt, Pt);
                printf("const,%u,0,%u,%u,%u,%u,%u,%u,%u,%u\n",
                       fbits(t), fbits(jms[ij]), fbits(A0), fbits(V0), fbits(P0),
                       fbits(Jt), fbits(At), fbits(Vt), fbits(Pt));
            }

            // rising and falling: times inside the segment and past its end
            for (unsigned itj = 0; itj < ARRAY_SIZE(tjs); itj++) {
                for (int it = -2; it <= 30; it++) {
                    const float t = (float)it * 0.05f;
                    float Jt, At, Vt, Pt;

                    sc.calc_javp_for_segment_incr_jerk(t, tjs[itj], jms[ij], A0, V0, P0,
                                                       Jt, At, Vt, Pt);
                    printf("incr,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u\n",
                           fbits(t), fbits(tjs[itj]), fbits(jms[ij]),
                           fbits(A0), fbits(V0), fbits(P0),
                           fbits(Jt), fbits(At), fbits(Vt), fbits(Pt));

                    sc.calc_javp_for_segment_decr_jerk(t, tjs[itj], jms[ij], A0, V0, P0,
                                                       Jt, At, Vt, Pt);
                    printf("decr,%u,%u,%u,%u,%u,%u,%u,%u,%u,%u\n",
                           fbits(t), fbits(tjs[itj]), fbits(jms[ij]),
                           fbits(A0), fbits(V0), fbits(P0),
                           fbits(Jt), fbits(At), fbits(Vt), fbits(Pt));
                }
            }
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/SCurve.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("kind,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
