#!/usr/bin/env python3
"""Emit the closed-form 3x3 and 4x4 cofactor expansions from upstream's source.

`inverse4x4` is sixteen six-term expressions, each a product of three indexed
elements with alternating signs — 96 subscripts in total. Retyping them is the
same transcription risk as the CRC tables, and a single wrong index would give
a plausible-looking matrix that is simply not the inverse. Worse, floating-point
addition is not associative, so even a *correctly* reordered expression would
produce different last bits and fail a bit-exact parity test for a reason that
looks like a real defect.

The expressions are syntactically identical in C and Rust, so they are
extracted verbatim rather than translated.
"""
import re
from pathlib import Path

SRC = Path("/srv/ardumaster/upstream/plane-4.7.0/libraries/AP_Math/matrix_alg.cpp")
OUT = Path("/srv/ardumaster/ports/plane-fw-rust/crates/ap-math/src/matrix_alg_gen.rs")


def body_between(text, start_marker, end_marker):
    i = text.index(start_marker)
    j = text.index(end_marker, i)
    return text[i:j]


def assignments(block):
    """Every `inv[k] = <expr>;`, whitespace-normalised."""
    out = {}
    for m in re.finditer(r"inv\[(\d+)\]\s*=\s*(.*?);", block, re.S):
        idx = int(m.group(1))
        expr = " ".join(m.group(2).split())
        out[idx] = expr
    return out


text = SRC.read_text()

b3 = body_between(text, "static bool inverse3x3", "static bool inverse4x4")
b4 = body_between(text, "static bool inverse4x4", "bool mat_inverse(")

a3 = assignments(b3)
a4 = assignments(b4)
assert sorted(a3) == list(range(9)), "3x3: got %s" % sorted(a3)
assert sorted(a4) == list(range(16)), "4x4: got %s" % sorted(a4)

# the determinants, also extracted rather than retyped
det3 = re.search(r"T\s+det\s*=\s*(.*?);", b3, re.S).group(1)
det3 = " ".join(det3.split())
det4 = re.search(r"det\s*=\s*(m\[0\].*?);", b4, re.S).group(1)
det4 = " ".join(det4.split())

lines = [
    "//! Closed-form matrix inverses, ported from `AP_Math/matrix_alg.cpp`.",
    "//!",
    "//! GENERATED by `tools/parity/gen_matrix_alg.py` -- do not edit. The 4x4",
    "//! expansion alone is sixteen six-term expressions, 96 subscripts, and a",
    "//! single wrong index would yield a plausible matrix that is not the",
    "//! inverse. Floating-point addition is also not associative, so even a",
    "//! correctly reordered expression would change the last bits and fail the",
    "//! parity test for a reason that looks like a real defect. The expressions",
    "//! are therefore extracted from upstream verbatim.",
    "//!",
    "//! Upstream returns a bool and writes through an out-parameter; these",
    "//! return `Option`, which cannot be ignored the way a bool can. Upstream",
    "//! marks its own declarations `WARN_IF_UNUSED` for exactly that reason.",
    "",
    "use crate::scalar::{is_zero, Real};",
    "",
    "/// Inverse of a 3x3 matrix in row-major order.",
    "///",
    "/// `None` if the matrix is singular or its determinant overflows, matching",
    "/// upstream's `is_zero(det) || isinf(det)` test.",
    "pub fn inverse3x3<T: Real>(m: &[T; 9]) -> Option<[T; 9]> {",
    "    let det = %s;" % det3,
    "    if is_zero(det) || det.is_infinite() {",
    "        return None;",
    "    }",
    "    let invdet = T::one() / det;",
    "",
    "    let mut inv = [T::zero(); 9];",
]
for k in range(9):
    lines.append("    inv[%d] = %s;" % (k, a3[k]))
lines += [
    "    Some(inv)",
    "}",
    "",
    "/// Inverse of a 4x4 matrix in row-major order.",
    "///",
    "/// The `gluInvertMatrix` expansion, as upstream notes. `None` if the matrix",
    "/// is singular or its determinant overflows.",
    "///",
    "/// Upstream brackets this with `fedisableexcept(FE_INEXACT | FE_OVERFLOW)`",
    "/// under SITL, because the expansion raises inexact and overflow flags that",
    "/// made macOS CI fail. Rust does not enable float exception traps, so there",
    "/// is nothing to disable and nothing to restore; the arithmetic is",
    "/// unchanged.",
    "pub fn inverse4x4<T: Real>(m: &[T; 16]) -> Option<[T; 16]> {",
    "    let mut inv = [T::zero(); 16];",
]
for k in range(16):
    lines.append("    inv[%d] = %s;" % (k, a4[k]))
lines += [
    "",
    "    let det = %s;" % det4,
    "    if is_zero(det) || det.is_infinite() {",
    "        return None;",
    "    }",
    "    let det = T::one() / det;",
    "",
    "    for e in inv.iter_mut() {",
    "        *e = *e * det;",
    "    }",
    "    Some(inv)",
    "}",
    "",
]

OUT.write_text("\n".join(lines))
print("wrote %s" % OUT.name)
print("  inverse3x3: 9 expressions, det extracted")
print("  inverse4x4: 16 expressions, det extracted")
