#!/usr/bin/env python3
"""Generate the HarmonicNotchFilter parity fixture from upstream's own bank.

HarmonicNotchFilter keeps its bank and shaping constants private, so unlike the
biquad and notch fixtures this one cannot reach in and compare coefficients. It
compares what the filter actually does instead: a deterministic broadband
signal through the whole bank, sample for sample. A notch placed at the wrong
frequency changes the output, so the placement arithmetic is covered even
though it is not read directly.

The `quintuple` scenario is here to pin D-021. Upstream clamps the composite
count to three, so its quintuple output should be identical to its triple
output -- and the Rust side asserts exactly that, which is a much sharper
statement of the defect than "the port differs".

The filters MUST be static: HarmonicNotchFilter has no constructor initialising
_initialised, and the NotchFilter bank it allocates with `new NotchFilter<T>[n]`
is default-initialised, which leaves every member of every notch indeterminate.
See D-005.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/harmonic_parity.csv"
BUILD = Path("/tmp/harmonic_parity/harness")

OBJECTS = [
    "build/sitl/libraries/Filter/HarmonicNotchFilter.cpp.4.o",
    "build/sitl/libraries/Filter/NotchFilter.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for Filter/HarmonicNotchFilter.cpp.
// Generated by tools/parity/gen_harmonic_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <Filter/HarmonicNotchFilter.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <AP_Param/AP_Param.h>
#include <GCS_MAVLink/GCS.h>
#include <AP_Logger/AP_Logger.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

// The params object is an AP_Param group. Binding it to storage would drag in
// the storage manager, the filesystem and the GCS, none of which touches the
// arithmetic under test. The harness sets every field through the public
// setters instead, which is the shape the port has -- its params are plain
// values, and binding them to storage is FW-004.
void AP_Param::setup_object_defaults(const void *, const struct AP_Param::GroupInfo *) {}

// HarmonicNotchFilterParams::save_params and the parameter-width conversion
// helpers persist tuning to EEPROM. Neither is called here and neither has
// anything to do with the arithmetic under test.
void AP_Param::save(bool)
{
    fputs("harness: unexpected AP_Param::save\n", stderr);
    abort();
}
bool AP_Param::_convert_parameter_width(ap_var_type, float, bool)
{
    fputs("harness: unexpected _convert_parameter_width\n", stderr);
    abort();
}

// Reached only from allocate_filters' out-of-memory path and from
// log_notch_centers, neither of which this harness takes: the bank always
// allocates and nothing here logs. Aborting rather than returning keeps that
// assumption honest -- if either were ever reached the process would die
// immediately instead of producing a plausible wrong answer.
GCS &gcs() { fputs("harness: unexpected gcs()\n", stderr); abort(); }
void GCS::send_text(MAV_SEVERITY, const char *, ...)
{
    fputs("harness: unexpected send_text\n", stderr);
    abort();
}
namespace AP {
AP_Logger &logger() { fputs("harness: unexpected logger()\n", stderr); abort(); }
}
void AP_Logger::WriteStreaming(const char *, const char *, const char *,
                               const char *, const char *, ...)
{
    fputs("harness: unexpected WriteStreaming\n", stderr);
    abort();
}

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// _tracking_mode is private with no setter, so every scenario runs in the
// default Fixed mode and retunes are driven by calling update() explicitly.
// update() does not consult the mode -- only init() does, to decide whether to
// place the notches itself -- so the placement path is exercised either way.
// The port test uses Fixed for the same reason.

enum opt {
    OPT_NONE      = 0,
    OPT_DOUBLE    = 1<<0,
    OPT_TRIPLE    = 1<<4,
    OPT_LOW_AS_MIN= 1<<5,
    OPT_QUINTUPLE = 1<<6,
};

struct scenario {
    const char *name;
    float sample_freq;
    float center_freq;
    float bandwidth;
    float attenuation_db;
    float freq_min_ratio;
    uint32_t harmonics;
    uint16_t options;
    uint8_t retune;          // non-zero: call update() at steps 40 and 80
    uint8_t num_centers;
    float centers[3];        // used when tracking, at step 40 and 80
    float centers2[3];
};

static const struct scenario scenarios[] = {
    {"single_h1",   1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x1,  OPT_NONE,       0, 1, {0,0,0}, {0,0,0}},
    {"single_h12",  1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x3,  OPT_NONE,       0, 1, {0,0,0}, {0,0,0}},
    {"single_h124", 1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0xB,  OPT_NONE,       0, 1, {0,0,0}, {0,0,0}},
    {"double_h1",   1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x1,  OPT_DOUBLE,     0, 1, {0,0,0}, {0,0,0}},
    {"triple_h1",   1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x1,  OPT_TRIPLE,     0, 1, {0,0,0}, {0,0,0}},
    {"triple_h12",  1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x3,  OPT_TRIPLE,     0, 1, {0,0,0}, {0,0,0}},
    // D-021: upstream clamps to three, so this must equal triple_h1
    {"quintuple_h1",1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x1,  OPT_QUINTUPLE,  0, 1, {0,0,0}, {0,0,0}},
    {"ins_rate",    8000.0f, 188.0f, 60.0f, 30.0f, 1.0f, 0x3,  OPT_DOUBLE,     0, 1, {0,0,0}, {0,0,0}},
    // third harmonic lands past the nyquist cutoff
    {"past_nyquist",1000.0f, 200.0f, 40.0f, 30.0f, 1.0f, 0x7,  OPT_NONE,       0, 1, {0,0,0}, {0,0,0}},
    // tracking: retuned at step 40 and again at 80
    {"tracked",     1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x1,  OPT_NONE,       2, 1, {150,0,0}, {90,0,0}},
    // fades out below the minimum frequency, then disables
    {"fade_out",    1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x1,  OPT_NONE,       2, 1, {50,0,0},  {10,0,0}},
    // low frequencies treated as the minimum instead of disabling
    {"low_as_min",  1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x1,  OPT_LOW_AS_MIN, 2, 1, {50,0,0},  {10,0,0}},
    // several independent centres, one per motor
    {"multi",       1000.0f, 100.0f, 40.0f, 30.0f, 1.0f, 0x3,  OPT_NONE,       3, 3, {100,150,200}, {120,170,220}},
};
static const int nscen = sizeof(scenarios)/sizeof(scenarios[0]);

// MUST be static -- see the generator's docstring.
static HarmonicNotchFilter<float>    hf[nscen];
static HarmonicNotchFilter<Vector3f> hv[nscen];
static HarmonicNotchFilterParams     hp[nscen];

// Energy at the fundamental, at the second harmonic, well below, plus a step
// and an impulse.
static float drive(int step)
{
    const float t = (float)step / 1000.0f;
    float v = 0.5f * sinf(2.0f * (float)M_PI * 100.0f * t);
    v += 0.3f * sinf(2.0f * (float)M_PI * 200.0f * t);
    v += 0.4f * sinf(2.0f * (float)M_PI * 12.0f * t);
    if (step >= 20) v += 1.0f;
    if (step == 70) v += 4.0f;
    return v;
}

int main(void)
{
    printf("#harmonic\n");
    printf("scenario,step,in,out_f,out_x,out_y,out_z\n");

    for (int s = 0; s < nscen; s++) {
        const struct scenario &sc = scenarios[s];
        HarmonicNotchFilterParams &p = hp[s];

        p.set_center_freq_hz(sc.center_freq);
        p.set_bandwidth_hz(sc.bandwidth);
        p.set_attenuation(sc.attenuation_db);
        p.set_freq_min_ratio(sc.freq_min_ratio);
        p.set_harmonics(sc.harmonics);
        p.set_options(sc.options);

        hf[s].allocate_filters(sc.num_centers, sc.harmonics, p.num_composite_notches());
        hv[s].allocate_filters(sc.num_centers, sc.harmonics, p.num_composite_notches());
        hf[s].init(sc.sample_freq, p);
        hv[s].init(sc.sample_freq, p);
        hf[s].reset();
        hv[s].reset();

        for (int step = 0; step < 120; step++) {
            if (sc.retune != 0 && step == 40) {
                hf[s].update(sc.num_centers, sc.centers);
                hv[s].update(sc.num_centers, sc.centers);
            }
            if (sc.retune != 0 && step == 80) {
                hf[s].update(sc.num_centers, sc.centers2);
                hv[s].update(sc.num_centers, sc.centers2);
            }

            const float in = drive(step);
            const float of = hf[s].apply(in);
            const Vector3f ov = hv[s].apply(Vector3f(in, 2.0f*in, -in));

            printf("%s,%d,%u,%u,%u,%u,%u\n", sc.name, step,
                   fbits(in), fbits(of), fbits(ov.x), fbits(ov.y), fbits(ov.z));
        }
    }
    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "Filter/HarmonicNotchFilter.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("scenario"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
