#!/usr/bin/env python3
"""Parity fixture for the chirp frequency sweep.

Several configurations driven over a dense time grid that runs from before the
record starts to after it ends, so every branch of the window and every branch
of the waveform is crossed: the silence either side, both raised-cosine fades,
the unity middle, the constant-frequency dwell, the exponential sweep, and the
constant-frequency special case where the exponent is zero and upstream tests
for it rather than dividing by it.

A descending sweep is included -- stop below start -- because the exponent is
then negative and nothing in the code says it must not be.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/chirp_parity.csv"
BUILD = Path("/tmp/chirp_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/chirp.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/chirp.cpp.
// Generated by tools/parity/gen_chirp_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Math/chirp.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

struct config {
    const char *name;
    float record, f_start, f_stop, fade_in, fade_out, const_freq, magnitude;
};

static const struct config configs[] = {
    // an ordinary sweep with a dwell
    { "sweep",      30.0f,  0.5f, 10.0f, 2.0f, 2.0f, 3.0f, 1.0f },
    // no dwell
    { "no_dwell",   20.0f,  1.0f, 20.0f, 1.0f, 1.0f, 0.0f, 0.5f },
    // constant frequency: the exponent is zero and is tested for
    { "steady",     10.0f,  2.0f,  2.0f, 1.0f, 1.0f, 0.0f, 1.0f },
    // constant frequency with a dwell, so the dwell branch and the equal
    // branch both run
    { "steady_dwell",10.0f, 3.0f,  3.0f, 1.0f, 1.0f, 4.0f, 0.25f },
    // a wide sweep
    { "wide",       60.0f,  0.1f, 40.0f, 5.0f, 5.0f, 8.0f, 1.0f },
    // descending: the exponent is negative
    { "descending", 25.0f, 10.0f,  0.5f, 2.0f, 2.0f, 2.0f, 1.0f },
    // no fades at all
    { "no_fade",    15.0f,  1.0f,  5.0f, 0.0f, 0.0f, 0.0f, 1.0f },
    // the dwell fills the whole record, so the sweep branch never runs
    { "all_dwell",  10.0f,  1.0f, 10.0f, 1.0f, 1.0f, 12.0f, 1.0f },
    // frequencies close but not equal: the exponent is tiny and the phase
    // multiplier correspondingly huge
    { "near_equal", 20.0f,  2.0f,  2.0001f, 1.0f, 1.0f, 0.0f, 1.0f },
};

int main(void)
{
    printf("#chirp\n");
    printf("config,time,output,freq_rads,complete\n");

    for (unsigned i = 0; i < ARRAY_SIZE(configs); i++) {
        const struct config &c = configs[i];
        Chirp chirp;
        chirp.init(c.record, c.f_start, c.f_stop, c.fade_in, c.fade_out, c.const_freq);

        // From before the start to after the end, in 10 ms steps.
        for (int step = -200; step <= (int)(c.record * 100.0f) + 200; step++) {
            const float t = (float)step * 0.01f;
            const float out = chirp.update(t, c.magnitude);
            printf("%s,%u,%u,%u,%d\n", c.name, fbits(t), fbits(out),
                   fbits(chirp.get_frequency_rads()),
                   chirp.completed() ? 1 : 0);
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/chirp.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("config,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
