#!/usr/bin/env python3
"""Generate the LowPassFilter2p parity fixture from upstream's own filter.

Harness-driven rather than replayed. The filter is stateful and its awkward
paths are all configuration-dependent -- the Nyquist clamp, a zero cutoff
falling through to pass-through, a zero sample rate doing the same, a cutoff
under FLT_EPSILON that is_positive rejects, the first-sample seeding, reset,
reset-to-value and retuning mid-stream. A flight log exercises exactly one
configuration.

Inputs are emitted alongside outputs, so the port replays the same sequence
with no shared generator to agree about.

Both template instantiations are driven. LowPassFilter2pFloat and
LowPassFilter2pVector3f are separately instantiated in upstream's .cpp, and a
port that got the scalar case right could still have the vector one wrong.

The coefficients themselves are emitted too, via a probe subclass reaching the
protected _params. Comparing only outputs would let a wrong coefficient hide
behind a compensating state error.

The filters MUST have static storage duration. DigitalBiquadFilter's
constructor sets the two delay elements and never sets `initialised`, so a
stack-allocated filter reads an indeterminate bool on its first sample -- the
D-005 defect in a second class. Static storage zero-initialises it to false
before the constructor runs, which is what every filter in a real vehicle gets
and what the port reproduces.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/biquad_parity.csv"
PARAMS_OUT = ROOT / "fixtures/biquad_params.csv"
BUILD = Path("/tmp/biquad_parity/harness")

OBJECTS = [
    "build/sitl/libraries/Filter/LowPassFilter2p.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for Filter/LowPassFilter2p.cpp.
// Generated by tools/parity/gen_biquad_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <Filter/LowPassFilter2p.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { abort(); }
    uint64_t micros64() { abort(); }
    uint32_t micros() { abort(); }
    uint64_t millis64() { abort(); }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// _params is protected. Reaching it through a subclass is the only way to
// compare the coefficients themselves rather than inferring them from outputs,
// where a wrong coefficient could hide behind a compensating state error.
template <class T>
class Probe : public LowPassFilter2p<T> {
public:
    const struct DigitalBiquadFilter<T>::biquad_params &params() const {
        return this->_params;
    }
};

enum action { ACT_NONE = 0, ACT_RESET, ACT_RESET_TO, ACT_RETUNE };

struct scenario {
    const char *name;
    float sample_freq;
    float cutoff_freq;
    enum action act;
    float act_arg;
};

static const struct scenario scenarios[] = {
    {"ins_gyro",       8000.0f,  188.0f, ACT_NONE,     0.0f},
    {"ins_accel",      1000.0f,   20.0f, ACT_NONE,     0.0f},
    {"loop_rate",       400.0f,   10.0f, ACT_NONE,     0.0f},
    {"slow",             50.0f,    5.0f, ACT_NONE,     0.0f},
    {"clamped",        1000.0f,  900.0f, ACT_NONE,     0.0f},
    {"at_boundary",    1000.0f,  400.0f, ACT_NONE,     0.0f},
    {"zero_cutoff",    1000.0f,    0.0f, ACT_NONE,     0.0f},
    {"zero_rate",         0.0f,   20.0f, ACT_NONE,     0.0f},
    {"neg_cutoff",     1000.0f,  -20.0f, ACT_NONE,     0.0f},
    {"sub_epsilon",    1000.0f, 1.0e-8f, ACT_NONE,     0.0f},
    {"reset",          1000.0f,   20.0f, ACT_RESET,    0.0f},
    {"reset_to",       1000.0f,   20.0f, ACT_RESET_TO, 3.5f},
    {"retune",         1000.0f,   20.0f, ACT_RETUNE,  60.0f},
    {"retune_to_zero", 1000.0f,   20.0f, ACT_RETUNE,   0.0f},
};
static const int nscen = sizeof(scenarios)/sizeof(scenarios[0]);

// MUST be static -- see the generator's docstring.
static Probe<float>    lpf_f[nscen];
static Probe<Vector3f> lpf_v[nscen];

// A deterministic broadband drive: a step, a tone, an impulse, and an
// alternation near Nyquist, so the filter sees DC, passband and stopband.
static float drive(int step)
{
    float v = 0.0f;
    if (step >= 5)  v += 1.0f;
    v += 0.5f * sinf(0.35f * (float)step);
    if (step == 30) v += 10.0f;
    if (step >= 60) v += ((step & 1) ? 0.75f : -0.75f);
    return v;
}

int main(void)
{
    FILE *pf = fopen("PARAMS_PATH", "w");
    if (!pf) { perror("params"); abort(); }
    fprintf(pf, "#biquad_params\n");
    fprintf(pf, "scenario,cutoff_freq,sample_freq,a1,a2,b0,b1,b2\n");

    printf("#biquad\n");
    printf("scenario,step,in,out_f,out_x,out_y,out_z\n");

    for (int s = 0; s < nscen; s++) {
        const struct scenario &sc = scenarios[s];
        Probe<float>    &ff = lpf_f[s];
        Probe<Vector3f> &fv = lpf_v[s];

        ff.set_cutoff_frequency(sc.sample_freq, sc.cutoff_freq);
        fv.set_cutoff_frequency(sc.sample_freq, sc.cutoff_freq);

        for (int step = 0; step < 100; step++) {
            if (step == 40) {
                switch (sc.act) {
                case ACT_RESET:
                    ff.reset(); fv.reset();
                    break;
                case ACT_RESET_TO:
                    ff.reset(sc.act_arg);
                    fv.reset(Vector3f(sc.act_arg, 2.0f*sc.act_arg, -sc.act_arg));
                    break;
                case ACT_RETUNE:
                    ff.set_cutoff_frequency(sc.sample_freq, sc.act_arg);
                    fv.set_cutoff_frequency(sc.sample_freq, sc.act_arg);
                    break;
                default:
                    break;
                }
            }

            const float in = drive(step);
            const float of = ff.apply(in);
            const Vector3f ov = fv.apply(Vector3f(in, 2.0f*in, -in));

            printf("%s,%d,%u,%u,%u,%u,%u\n", sc.name, step,
                   fbits(in), fbits(of), fbits(ov.x), fbits(ov.y), fbits(ov.z));
        }

        // As they stand at the end, which for the retune scenarios is the
        // retuned set.
        const struct DigitalBiquadFilter<float>::biquad_params &p = ff.params();
        fprintf(pf, "%s,%u,%u,%u,%u,%u,%u,%u\n", sc.name,
                fbits(p.cutoff_freq), fbits(p.sample_freq),
                fbits(p.a1), fbits(p.a2), fbits(p.b0), fbits(p.b1), fbits(p.b2));
    }
    fclose(pf);
    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    src = HARNESS.replace("PARAMS_PATH", str(PARAMS_OUT))
    build(src, OBJECTS, BUILD, "Filter/LowPassFilter2p.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("scenario"))
    print("wrote %s: %d rows" % (OUT.name, rows))
    print("wrote %s" % PARAMS_OUT.name)


if __name__ == "__main__":
    main()
