#!/usr/bin/env python3
"""Generate the 1976 standard atmosphere parity fixture from upstream.

Covers the whole model: the geometric/geopotential conversions, temperature,
pressure, density and EAS2TAS forward from altitude, and altitude back from
pressure.

Six of these are static and need no object. Three are const members --
get_altitude_from_pressure, get_temperature_from_altitude and
get_EAS2TAS_extended -- and all three read only file-scope tables on the paths
this harness drives. They are called through a zeroed, correctly aligned buffer
rather than a constructed AP_Baro, because constructing one would drag in the
parameter system, the logger, the GCS and every sensor backend, none of which
touches the arithmetic under test.

That is only sound because the paths taken never dereference `this`. The one
place any of them would -- get_altitude_from_pressure's fallback to
get_altitude_AMSL() when the pressure ratio is not positive -- is guarded by
stubbing INTERNAL_ERROR to abort, and by feeding only pressures a working
sensor could produce. If that path is ever reached the harness dies rather than
emitting a plausible wrong number.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/plane-fw-rust")
OUT = ROOT / "fixtures/atmosphere_parity.csv"
BUILD = Path("/tmp/atmos_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Baro/AP_Baro_atmosphere.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Baro/AP_Baro_atmosphere.cpp.
// Generated by tools/parity/gen_atmosphere_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Baro/AP_Baro.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}

// Aborting, not ignoring. get_altitude_from_pressure raises this and then
// falls back to get_altitude_AMSL(), which WOULD read the object -- the one
// path where the zeroed-storage trick below would be unsound. Dying here
// means that can never silently happen.
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t)
{
    fputs("harness: INTERNAL_ERROR reached -- a driven path touches the object\n", stderr);
    abort();
}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

// Reached only from get_altitude_difference_simple and get_EAS2TAS_simple,
// the two functions of the *simple* model. Both are private and neither is
// driven here, so this is unreachable -- and it genuinely would read the
// object, which is the one thing the zeroed storage cannot survive. Aborting
// keeps that assumption honest.
float AP_Baro::get_ground_temperature(void) const
{
    fputs("harness: get_ground_temperature reached -- it reads the object\n", stderr);
    abort();
}

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

// See the generator's docstring for why this is a zeroed buffer and not a
// constructed AP_Baro.
//
// get_EAS2TAS_extended and get_temperature_by_altitude_layer are private
// rather than protected, so not even a subclass can re-export them. Neither is
// a hole: the first is sqrt(SSL_AIR_DENSITY/density) over a density that is
// parity-tested directly, with the same sqrt path reached through the public
// get_EAS2TAS_for_alt_amsl; the second is called by all three of the forward
// entry points driven below, so a wrong layer temperature would move them.
alignas(AP_Baro) static unsigned char baro_storage[sizeof(AP_Baro)] = {0};
static AP_Baro *baro = reinterpret_cast<AP_Baro *>(baro_storage);

// Altitudes spanning every layer boundary and both sides of each, plus below
// sea level, which the table extends to -5000 m for.
static const float altitudes[] = {
    -4900, -4000, -1000, -400, -100, 0, 100, 500, 1000, 2000, 5000, 8000,
    10000, 10900, 11000, 11100, 15000, 19900, 20000, 20100, 25000, 31900,
    32000, 32100, 40000, 46900, 47000, 47100, 50000, 50900, 51000, 51100,
    60000, 70900, 71000, 71100, 80000, 84000, 84852, 90000,
};

// Pressures from well above sea level standard down past the top of the
// table. All are values a sensor or the model itself could produce, so the
// error path is never taken.
static const float pressures[] = {
    177000, 120000, 101325, 95000, 89876, 79495, 70108, 61640, 54019, 47181,
    41060, 35599, 30742, 26436, 22632, 19330, 12044, 5474.89, 2549, 1197,
    868.019, 372, 110.906, 66.9389, 25.5, 3.95642, 1.05, 0.37338, 0.1,
};

int main(void)
{
    printf("#atmosphere\n");
    printf("kind,input,a,b\n");

    // Conversions both ways.
    for (unsigned i = 0; i < ARRAY_SIZE(altitudes); i++) {
        const float alt = altitudes[i];
        printf("geo2pot,%u,%u,0\n", fbits(alt),
               fbits(AP_Baro::geometric_alt_to_geopotential(alt)));
        printf("pot2geo,%u,%u,0\n", fbits(alt),
               fbits(AP_Baro::geopotential_alt_to_geometric(alt)));
    }

    // Forward model: pressure, temperature, density, EAS2TAS from altitude.
    for (unsigned i = 0; i < ARRAY_SIZE(altitudes); i++) {
        const float alt = altitudes[i];
        float p, t;
        AP_Baro::get_pressure_temperature_for_alt_amsl(alt, p, t);
        printf("pt,%u,%u,%u\n", fbits(alt), fbits(p), fbits(t));
        printf("density,%u,%u,0\n", fbits(alt),
               fbits(AP_Baro::get_air_density_for_alt_amsl(alt)));
        printf("eas2tas_sitl,%u,%u,0\n", fbits(alt),
               fbits(AP_Baro::get_EAS2TAS_for_alt_amsl(alt)));
        printf("temp_from_alt,%u,%u,0\n", fbits(alt),
               fbits(baro->get_temperature_from_altitude(alt)));

    }

    // Inverse: altitude from pressure.
    for (unsigned i = 0; i < ARRAY_SIZE(pressures); i++) {
        const float p = pressures[i];
        printf("alt_from_p,%u,%u,0\n", fbits(p),
               fbits(baro->get_altitude_from_pressure(p)));
    }

    // Altitude difference against a sea-level standard base.
    for (unsigned i = 0; i < ARRAY_SIZE(pressures); i++) {
        const float p = pressures[i];
        printf("alt_diff,%u,%u,0\n", fbits(p),
               fbits(baro->get_altitude_difference(101325.0f, p)));
    }

    // The numerical sea-level solver.
    for (unsigned i = 0; i < ARRAY_SIZE(altitudes); i++) {
        const float alt = altitudes[i];
        if (alt < -4000 || alt > 20000) {
            continue;   // the solver is for flight altitudes
        }
        float p, t;
        AP_Baro::get_pressure_temperature_for_alt_amsl(alt, p, t);
        printf("sealevel,%u,%u,%u\n", fbits(alt), fbits(p),
               fbits(baro->get_sealevel_pressure(p, alt)));
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Baro/AP_Baro_atmosphere.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("kind"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
