#!/usr/bin/env python3
"""Parity fixture for SplineCurve, driven through the public API.

Deliberately public-only. The internals could be reached the way the SCurve
harness reaches SCurve's, but update_solution and calc_target_pos_vel read and
write `_hermite_solution` -- a member -- so that would put a class-layout
assumption in the middle of the test. The public surface is the whole
observable behaviour anyway.

Each scenario sets limits and a segment, records the two speed maxima the
setup computes, then walks the curve to completion recording position and
velocity at every step. Walking it is what exercises calc_dt_speed_max,
including the braking clamp whose behaviour differs between the setup and
stepping call sites because upstream's out-parameter aliases a member there.

The scenarios cover: a straight leg, a right-angle turn, a climb, a descent, a
segment short enough for the velocity guard to bind, one with a zero
destination velocity (the vehicle must stop), and a zero-length segment.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/ardumaster-rust")
OUT = ROOT / "fixtures/spline_parity.csv"
BUILD = Path("/tmp/spline_parity/harness")

OBJECTS = [
    "build/sitl/libraries/AP_Math/SplineCurve.cpp.0.o",
    "build/sitl/libraries/AP_Math/control.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for AP_Math/SplineCurve.cpp.
// Generated by tools/parity/gen_spline_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <AP_Math/SplineCurve.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
// NOT aborting: calc_dt_speed_max raises this legitimately on a degenerate
// step and marks the segment finished, which is behaviour the port reproduces
// and the fixture should record rather than die on.
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }
static uint64_t dbits(double d) { uint64_t u; memcpy(&u, &d, 8); return u; }

struct scenario {
    const char *name;
    float sxy, sup, sdn, axy, az;             // limits
    double ox, oy, oz, dx, dy, dz;            // origin and destination
    float ovx, ovy, ovz, dvx, dvy, dvz;       // end velocities
    float start_speed;                        // initial target speed
};

static const struct scenario scenarios[] = {
    { "straight",   500,250,150,250,100,   0,0,0,      2000,0,0,      200,0,0,    200,0,0,   200 },
    { "right_turn", 500,250,150,250,100,   0,0,0,      2000,2000,0,   300,0,0,    0,300,0,   300 },
    { "climb",      500,250,150,250,100,   0,0,0,      2000,0,-500,   200,0,0,    200,0,-50, 200 },
    { "descend",    500,250,150,250,100,   0,0,0,      2000,0,500,    200,0,0,    200,0,50,  200 },
    { "short_leg",  500,250,150,250,100,   0,0,0,      100,0,0,       500,0,0,    500,0,0,   100 },
    { "stop_at_end",500,250,150,250,100,   0,0,0,      1500,500,0,    250,0,0,    0,0,0,     250 },
    { "zero_length",500,250,150,250,100,   100,200,-50, 100,200,-50,  100,0,0,    0,0,0,     100 },
    { "tight",      500,250,150,250,100,   0,0,0,      500,50,0,      400,0,0,    -400,0,0,  400 },
    { "slow_limits",100,50,50,50,25,       0,0,0,      1000,1000,0,   80,0,0,     0,80,0,    80 },
};

int main(void)
{
    printf("#spline\n");
    printf("scenario,step,px,py,pz,vx,vy,vz,reached\n");

    for (unsigned i = 0; i < ARRAY_SIZE(scenarios); i++) {
        const struct scenario &s = scenarios[i];
        // MUST be static. SplineCurve has NO CONSTRUCTOR and no member
        // initialisers, and set_origin_and_destination reads
        // _destination_speed_max -- through calc_dt_speed_max's braking clamp
        // -- before ever writing it. On the stack that read picks up whatever
        // the previous iteration left there: the first version of this harness
        // used a local and got 218.1241 for short_leg's origin_speed_max,
        // which is a function of the previous scenario's stack frame and
        // nothing else. Static storage zero-initialises it, which is what a
        // real vehicle gets. See D-005.
        static SplineCurve pool[ARRAY_SIZE(scenarios)];
        SplineCurve &sc = pool[i];
        sc.set_speed_accel(s.sxy, s.sup, s.sdn, s.axy, s.az);
        sc.set_origin_and_destination(Vector3p(s.ox, s.oy, s.oz),
                                      Vector3p(s.dx, s.dy, s.dz),
                                      Vector3f(s.ovx, s.ovy, s.ovz),
                                      Vector3f(s.dvx, s.dvy, s.dvz));

        // step -1 carries the two speed maxima the setup computed
        printf("%s,-1,%u,%u,0,0,0,0,%d\n", s.name,
               fbits(sc.get_origin_speed_max()),
               fbits(sc.get_destination_speed_max()),
               sc.reached_destination() ? 1 : 0);

        Vector3p pos(s.ox, s.oy, s.oz);
        Vector3f vel(s.ovx, s.ovy, s.ovz);
        if (vel.length() > 0) {
            vel = vel.normalized() * s.start_speed;
        }

        for (int step = 0; step < 3000 && !sc.reached_destination(); step++) {
            sc.advance_target_along_track(0.01f, pos, vel);
            printf("%s,%d,%llu,%llu,%llu,%u,%u,%u,%d\n", s.name, step,
                   (unsigned long long)dbits(pos.x),
                   (unsigned long long)dbits(pos.y),
                   (unsigned long long)dbits(pos.z),
                   fbits(vel.x), fbits(vel.y), fbits(vel.z),
                   sc.reached_destination() ? 1 : 0);
        }
    }

    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "AP_Math/SplineCurve.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("scenario,"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
