#!/usr/bin/env python3
"""Generate the DerivativeFilter parity fixture from upstream's own filter.

Drives all four instantiated sizes through the sequences that reach the
interesting paths: an unfilled buffer, a straight line, irregular spacing, a
zig-zag the smoothing is supposed to reject, a repeated timestamp that must be
dropped, and a microsecond counter wrapping past its maximum mid-buffer.

Samples and timestamps are emitted alongside the slope, so the port replays
exactly the same sequence.

The filters MUST be static. DerivativeFilter's constructor body is empty --
it delegates to FilterWithBuffer, which clears the sample buffer and the index
and leaves _new_data, _last_slope and the entire _timestamps array
indeterminate. Worse, the "we haven't filled the buffer yet" guard in slope()
is implemented as a test on two of those timestamp slots being equal, so with
garbage in them it does not fire. See D-005.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from parity_build import build, run  # noqa: E402

ROOT = Path("/srv/ardumaster/ports/ardumaster-rust")
OUT = ROOT / "fixtures/derivative_parity.csv"
BUILD = Path("/tmp/deriv_parity/harness")

OBJECTS = [
    "build/sitl/libraries/Filter/DerivativeFilter.cpp.0.o",
    "build/sitl/libraries/AP_Math/AP_Math.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector2.cpp.0.o",
    "build/sitl/libraries/AP_Math/vector3.cpp.0.o",
    "build/sitl/libraries/AP_Math/matrix3.cpp.0.o",
]

HARNESS = r'''
// Parity harness for Filter/DerivativeFilter.cpp.
// Generated by tools/parity/gen_derivative_fixture.py -- do not edit by hand.
#include <AP_Math/AP_Math.h>
#include <Filter/DerivativeFilter.h>
#include <AP_InternalError/AP_InternalError.h>
#include <AP_HAL/AP_HAL.h>
#include <AP_CustomRotations/AP_CustomRotations.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

namespace AP_HAL {
    void panic(const char *m, ...) { fputs(m, stderr); abort(); }
    uint32_t millis() { return 0; }
    uint64_t micros64() { return 0; }
    uint32_t micros() { return 0; }
    uint64_t millis64() { return 0; }
}
void AP_InternalError::error(const AP_InternalError::error_t, uint16_t) {}
namespace AP {
AP_InternalError &internalerror() { static AP_InternalError d; return d; }
AP_CustomRotations &custom_rotations() { abort(); }
}
void AP_CustomRotations::rotate(enum Rotation, Vector3f &) { abort(); }
void AP_CustomRotations::rotate(enum Rotation, Vector3d &) { abort(); }

static uint32_t fbits(float f) { uint32_t u; memcpy(&u, &f, 4); return u; }

#define NSTEPS 40

enum kind { K_LINE = 0, K_IRREGULAR, K_ZIGZAG, K_REPEAT, K_WRAP };

struct scenario {
    const char *name;
    enum kind k;
};

static const struct scenario scenarios[] = {
    {"line",      K_LINE},
    {"irregular", K_IRREGULAR},
    {"zigzag",    K_ZIGZAG},
    {"repeat",    K_REPEAT},
    {"wrap",      K_WRAP},
};
static const int nscen = sizeof(scenarios)/sizeof(scenarios[0]);

static const uint32_t gaps[7] = {1000, 2500, 700, 1800, 900, 3000, 1200};

// Produce the (sample, timestamp) pair for one step of one scenario.
static void gen(enum kind k, int i, float *sample, uint32_t *ts)
{
    switch (k) {
    case K_LINE:
        *sample = 2.0f * (float)i;
        *ts = (uint32_t)i * 1000u;
        break;
    case K_IRREGULAR: {
        uint32_t t = 0;
        for (int j = 0; j <= i; j++) { t += gaps[j % 7]; }
        *sample = 2.0f * (float)t;
        *ts = t;
        break;
    }
    case K_ZIGZAG:
        *sample = 0.5f * (float)i + ((i % 2 == 0) ? 1.0f : -1.0f);
        *ts = (uint32_t)i * 1000u;
        break;
    case K_REPEAT:
        // every third sample repeats the previous timestamp
        *sample = 2.0f * (float)i;
        *ts = (uint32_t)((i % 3 == 2) ? (i - 1) : i) * 1000u;
        break;
    case K_WRAP:
        *sample = 2.0f * (float)i;
        *ts = (uint32_t)(0xFFFFFFFFu - 5000u) + (uint32_t)i * 1000u;
        break;
    }
}

// MUST be static -- see the generator's docstring.
static DerivativeFilter<float,5>  f5[nscen];
static DerivativeFilter<float,7>  f7[nscen];
static DerivativeFilter<float,9>  f9[nscen];
static DerivativeFilter<float,11> f11[nscen];

int main(void)
{
    printf("#derivative\n");
    printf("scenario,size,step,sample,timestamp,slope\n");

    for (int s = 0; s < nscen; s++) {
        for (int step = 0; step < NSTEPS; step++) {
            float sample; uint32_t ts;
            gen(scenarios[s].k, step, &sample, &ts);

            f5[s].update(sample, ts);
            f7[s].update(sample, ts);
            f9[s].update(sample, ts);
            f11[s].update(sample, ts);

            printf("%s,5,%d,%u,%u,%u\n",  scenarios[s].name, step, fbits(sample), ts, fbits(f5[s].slope()));
            printf("%s,7,%d,%u,%u,%u\n",  scenarios[s].name, step, fbits(sample), ts, fbits(f7[s].slope()));
            printf("%s,9,%d,%u,%u,%u\n",  scenarios[s].name, step, fbits(sample), ts, fbits(f9[s].slope()));
            printf("%s,11,%d,%u,%u,%u\n", scenarios[s].name, step, fbits(sample), ts, fbits(f11[s].slope()));
        }
    }
    return 0;
}
'''


def main():
    BUILD.parent.mkdir(parents=True, exist_ok=True)
    OUT.parent.mkdir(parents=True, exist_ok=True)
    build(HARNESS, OBJECTS, BUILD, "Filter/DerivativeFilter.cpp")
    text = run(BUILD)
    OUT.write_text(text)
    rows = sum(1 for l in text.splitlines()
               if l and not l.startswith("#") and not l.startswith("scenario"))
    print("wrote %s: %d rows" % (OUT.name, rows))


if __name__ == "__main__":
    main()
